### ISSUE TITLE
Why reserved word 'default' as key

### ISSUE THREAD

**Issue by ismay** [danielspaniel/ember-data-factory-guy#101]
This might be a stupid question, but I was wondering whether the use of the reserved word `default`, as the default key in factories is intentional. And whether it wouldn't be better to use a non-reserved keyword, such as `defaults`.

Eslint has a `no-reserved-keys` rule that trips over this in my tests (see http://eslint.org/docs/rules/no-reserved-keys.html). Now I understand that this is only an issue when you want to support ECMAscript 3, and it might be overly cautious. But on the other hand, it isn't that difficult to use non-reserved keywords (maybe at the cost of some naming troubles). So I'm interested in hearing your thoughts about this.

**Comment by danielspaniel** [comment]
Not a stupid question at all .. @ismay .
  Well, at the time, I thought about it, and realized it might be alittle unusual to use a reserved word like that in a key, but figured, what the heck, and just did it. 
 If I had heard this idea at the time I would have used 'defaults' as you are suggesting.

**Comment by ismay** [comment]
Ah right, and it's probably too much of a breaking change (with not enough actual advantages) to change this now, right?

**Comment by danielspaniel** [comment]
Hmm .. you know .. I could change it and not break things by issuing a deprecation warning when people use 'default' instead of 'defaults', but the only thing that stops me is that ember no longer supports IE8 ( as of ember 2.0) so I wonder if anyone will notice?

**Comment by ismay** [comment]
> the only thing that stops me is that ember no longer supports IE8 ( as of ember 2.0) so I wonder if anyone will notice?

That's true. Only reason I noticed it is because I'm using the airbnb eslintrc preset, which has this rule turned on by default. Not sure what the current best practice would be.

**Comment by danielspaniel** [comment]
Right .. so I will close this .. but good discussion topic anyway :)

**Comment by ismay** [comment]
:) ok, thanks for sharing your thoughts on this!
