### ISSUE TITLE
Couldn't find module after installing ember-data-factory-guy 1.13.0

### ISSUE THREAD

**Issue by rachid** [danielspaniel/ember-data-factory-guy#103]
I am working with the latest versions of Ember-cli (0.2.7)
Latest stable version of Ember.js and Ember-data 1.13.0

When running a test I am getting a message which states the module cannot be found. 

Died on test #1     at http://localhost:7357/assets/test-support.js:2846
    at http://localhost:7357/assets/test-support.js:5611
    at http://localhost:7357/assets/test-loader.js:31
    at http://localhost:7357/assets/test-loader.js:21
    at http://localhost:7357/assets/test-loader.js:40
    at http://localhost:7357/assets/test-support.js:5618: Could not find module `ember-data-factory-guy` imported from `frontend/tests/unit/models/person-test`

Am I missing something here? 

Already tried to reinitiate the test part of my ember-cli applications, remove packages and reinstalled (bower / npm) 

However, I can run `ember g factory ....` succesfully 

Am I missing something, do I need to initialize the addon manually?

**Comment by danielspaniel** [comment]
which version of ember-data are you using?

**Comment by danielspaniel** [comment]
Oops, ok .. I see you said ember-data 1.3.0 .. can you send me the test? and then switch to ember-data 1.3.4 ( much more stable that 1.3.0 )

**Comment by rachid** [comment]
@danielspaniel I created a new project, now it works. I think screwed something somewhere in upgrading to latest versions. I'll digg further and I will inform you when something interesting pops up.

**Comment by danielspaniel** [comment]
Ok .. glad to hear it worked @rachid .. I was hoping it would be something like that.

**Comment by azuruce** [comment]
have the same issue but is resolved after runing "npm prune", "ember install ember-data-factory-guy

**Comment by danielspaniel** [comment]
glad you got it working @azuruce
