### ISSUE TITLE
Allow handleFindAll to return 0 items

### ISSUE THREAD

**Issue by mcm-ham** [danielspaniel/ember-data-factory-guy#107]
I had in my unit tests calls like this:
```TestHelper.handleFindAll('offer', 0)```

Since upgrading ember-data-factory-guy it now gives me a `buildList needs a name and a number ( at least ) to build with` error.

**Comment by danielspaniel** [comment]
Thanks for the report on this one @mcm-ham. It is fixed in new version v1.13.2
