### ISSUE TITLE
handleFindAll with no records

### ISSUE THREAD

**Issue by FilmKnurd** [danielspaniel/ember-data-factory-guy#109]
This is a fantastic tool. Thanks for building it.

I'd like to suggest enhancing the test helper to handle the case where there are no records. It would be nice to write tests for how the app responds when zero models are returned.

```JS
handleFindAll('modelType', 0);

visit('/some-route');

andThen(function() {
  var message_found = $('#ember-testing').text().includes('No models found!');
  assert.ok(message_found);
});
```

**Comment by danielspaniel** [comment]
@FilmKnurd, thanks for the idea, and luckily someone asked me to fix that feature recently, and in version 1.3.2  ( the latest )  this handleFindAll('blah', 0 ) .. now works. 
 Let me know if upgrading works for you.

**Comment by FilmKnurd** [comment]
It works!

You should probably update the version number in the installation instructions. Also, after installing I had to run: ```ember g ember-data-factory-guy``` in order to install the bundled mockjax.

**Comment by danielspaniel** [comment]
Opps .. did I forget that . rats .. will do 
Really! ..  crumbsky ..  I forgot to put that in the docs .. how did I get away with that for so long .. man that is terrible .. aaaaaaaaahhhhhhhh .. fixing asap

**Comment by danielspaniel** [comment]
@FilmKnurd .. did you install like ember install ember-data-factory-guy ?? that should install the bower mockjax automatically .. I am double checking that again and again

**Comment by FilmKnurd** [comment]
I did ```ember install ember-data-factory-guy@1.13.1```, but it did not add mockjax to my bower.json until I ran the generator.  I have not tried it install 1.13.2 fresh.

**Comment by danielspaniel** [comment]
that is a bummer .. which version of ember-cli are you using .. I am betting something changed

**Comment by FilmKnurd** [comment]
CLI: 1.13.1
Node: 0.12.2
NPM: 2.12.1

**Comment by danielspaniel** [comment]
and which versions of ember/ember data

**Comment by FilmKnurd** [comment]
I just did a fresh ember install after upgrading cli to 1.13.5 and it worked fine. It ran the bower install like it should.

**Comment by danielspaniel** [comment]
I guess I will close this since I think all issues are taken care of .. let me know otherwise or open it up again.
