### ISSUE TITLE
Simplify the find stub for one record

### ISSUE THREAD

**Issue by GCorbel** [danielspaniel/ember-data-factory-guy#112]
I have this simple test : 

    test('Show the list of skills', function(assert) {
      visit('/skills/1');
      var skills = FactoryGuy.makeList('skill', 1);

      TestHelper.handleFindQuery('skill', ['id'], skills);

      andThen(function() {
        assert.equal(find('#skill #name').text(), skills[0].get('name'));
        assert.equal(currentURL(), '/skills/1');
      });
    });

And this route : 

    import Ember from 'ember';

    export default Ember.Route.extend({
      model: function(params) {
        return this.store.find('skill', params.id);
      }
    });

I find it a little bit complicated. It would be nice if we can do : 

    test('Show the list of skills', function(assert) {
      visit('/skills/1');
      var skill = FactoryGuy.make('skill');

      TestHelper.handleFindQuery('skill', skill);

      andThen(function() {
        assert.equal(find('#skill #name').text(), skills.get('name'));
        assert.equal(currentURL(), '/skills/1');
      });
    });

Or that : 

    test('Show the list of skills', function(assert) {
      visit('/skills/1');
      var skill = TestHelper.handleFind('skill');

      andThen(function() {
        assert.equal(find('#skill #name').text(), skills[0].get('name'));
        assert.equal(currentURL(), '/skills/1');
      });
    });

What you think?

**Comment by danielspaniel** [comment]
It's a good idea @GCorbel , I was just waiting for someone to suggest a good way to implement handleFind .. 
 should handleFind have the same parameters as make  and if so its tricky to say 
 handleFind('skil')
 and then 
visit('skill/1') 
 because how do you know the id of the skill  ( it might not be 1 ) .. if you have other skill in the store already. 
 maybe handleFind('skil'), has to return the id of the skill it will be building? 

 ideas?

**Comment by danielspaniel** [comment]
I think I can get to this next week or this weekend .. and I am going to have handleFind return the id that it is going to 'find'  so you can visit with that id

**Comment by danielspaniel** [comment]
@GCorbel .. if you use the new version I just made ( v1.3.4 ) .. there is now a method called 
 handleFind  on the FactoryGuyTestHelper, that will return the id of the record it is about to find
 when you call visit/id  if you know what I mean. 
  Anyway .. can you give it a try and let me know how it works, and then let me know if I can close this issue, if it works nicely for you

**Comment by danielspaniel** [comment]
So, now you can do this:
```javascript

test('Show the list of skills', function(assert) {
  var skillId = TestHelper.handleFind('skill');  
  visit('/skills/'+skillId);

  andThen(function() {
    assert.equal(find('#skill #name').text(), skills[0].get('name'));
    assert.equal(currentURL(), '/skills/'+skillId);
  });
});
```

**Comment by GCorbel** [comment]
Sorry for the late answer. Your script can't work because `skills` is not defined. Is there a way to return the skill instead of the skillId?

**Comment by danielspaniel** [comment]
No, @GCorbel, trying to return the model would be impossible ( sort of ) .. but I think you could do this instead:

```javascript
test('Show the list of skills', function(assert) {
  var name = 'my fun name';
  var skillId = TestHelper.handleFind('skill', {name:name});  
  visit('/skills/'+skillId);

  andThen(function() {
    assert.equal(find('#skill #name').text(), name);
    assert.equal(currentURL(), '/skills/'+skillId);
  });
});
```

**Comment by GCorbel** [comment]
I have this message `ReferenceError: Can't find variable: define at http://localhost:7357/assets/test-loader.js, line 47` with the version 1.3.4. Not with the 1.3.3.

Here is the file : 

    /* globals requirejs, require */
    (function() {
    define("ember-cli/test-loader",
      [],
      function() {
        "use strict";

        var TestLoader = function() {
        };

        TestLoader.prototype = {
          shouldLoadModule: function(moduleName) {
            return (moduleName.match(/[-_]test$/));
          },

          loadModules: function() {
            var moduleName;

            for (moduleName in requirejs.entries) {
              if (this.shouldLoadModule(moduleName)) {
                this.require(moduleName);
              }
            }
          }
        };

        TestLoader.prototype.require = function(moduleName) {
          try {
            require(moduleName);
          } catch(e) {
            this.moduleLoadFailure(moduleName, e);
          }
        };

        TestLoader.prototype.moduleLoadFailure = function(moduleName, error) {
          console.error('Error loading: ' + moduleName, error.stack);
        };

        TestLoader.load = function() {
          new TestLoader().loadModules();
        };

        return {
          'default': TestLoader
        }
      }
    );
    })();
The line 47 is the last line. Do you have an idea?

**Comment by danielspaniel** [comment]
@GCorbel ... gulp ... hard to say what is going on really ... since I can't see the context of what your files are etc .. is this related to the issue at hand though? .. want to start new issue? or close this one first?

**Comment by danielspaniel** [comment]
Can you close this issue @GCorbel, not sure I can help much with the define error ( maybe put that in another issue for clarity ) but I think the handleFind method ( done in v1.13.4 ) solves this original issue

**Comment by GCorbel** [comment]
Yes thanks for your job.
