### ISSUE TITLE
using .andFail with a status that isn't an error code

### ISSUE THREAD

**Issue by ismay** [danielspaniel/ember-data-factory-guy#115]
When using:

```javascript
handleUpdate().andFail({
  status: 304 // won't fail
})
```

the update doesn't fail if the status code isn't an error code. Now this makes sense, but it would help with debugging if `ember-data-factory-guy` threw an error when using status codes that aren't actual error status codes. I took quite some time to figure that this was why the request wasn't failing.

@pgvandelden

**Comment by danielspaniel** [comment]
This is a funny one actually .. because I never thought anyone would do that .. but sure .. why not .. 
If you have any time .. do you feel like doing a pull request to add this?  If not I can do it .. but it might take a while, since I have a few other issues that are before this and are nagging me

**Comment by ismay** [comment]
Yeah it's clearly a user error. But how would you prefer ember-data-factory-guy to handle this? Do you think it should throw an error when anything but an error status code is used?

**Comment by danielspaniel** [comment]
Yes, that would be the way to do it .. that way they see the error and tests stop right there.

**Comment by ismay** [comment]
Ok cool. I won't have time to work on this anytime soon, but if it's not too late I can submit a PR in about two weeks.

**Comment by danielspaniel** [comment]
That is fine @ismay .. get to it when you can.

**Comment by danielspaniel** [comment]
v2.6.4 adds this check for only setting 4XX and 5XX values for status options on a `fails()` method call
