### ISSUE TITLE
How do I test `store.filter`

### ISSUE THREAD

**Issue by trisrael** [danielspaniel/ember-data-factory-guy#118]
I've been using live arrays pretty extensively, and would like to be able to just test the filtered results after building up a store using FactoryGuy. I see handle types for query, find and other types but not filter. How would I accomplish this task?

For now I am going to stub `store.filter` and return results and apply the filter giving in myself...

**Comment by danielspaniel** [comment]
@trisrael, it's a good question .. I wonder if you can take a look at the ember data source, and then come up with a plan that might work for use in factory guy.  I am on vacation right now, or I would be more helpful.

**Comment by danielspaniel** [comment]
@trisrael .. after reading the docs myself for store.filter -> 
 
 http://emberjs.com/api/data/classes/DS.Store.html#method_filter

and looking at the opening paragraph: 

Takes a type and filter function, and returns a live RecordArray that remains up to date as new records are loaded into the store or created locally.


My first conclusion is that all you have to do is to first create some models with factory guy, before you use the store.filter function. 

```javascript
 var post1 = FactoryGuy.make('post', {unread: true});
 var post2 = FactoryGuy.make('post', {unread: false});

store.filter('post', function(post) {
  return post.get('unread');
}).then(function(unreadPosts) {
  unreadPosts.get('length'); // 1  => post1
  var unreadPost = unreadPosts.objectAt(0);
  unreadPost.set('unread', false);
  unreadPosts.get('length'); // 0
});

```

If you mean to be able to actually do the find query as well with this kind of filter:

```javascript
store.filter('post', { unread: true }, function(post) {
  return post.get('unread');
}).
```

then let me know.

**Comment by danielspaniel** [comment]
any further thoughts about this @trisrael ??

**Comment by trisrael** [comment]
This makes sense to me. Ideally yes there would be a `handleFilter` but maybe `handleQuery` will cover this case as well

**Comment by danielspaniel** [comment]
the latest version of factoryguy handles it pretty will I think ( I changed up a few things ) .. maybe give it a try and let me know what you find?
