### ISSUE TITLE
Fix => DEPRECATION: `InvalidError` expects json-api formatted errors.

### ISSUE THREAD

**Issue by danielspaniel** [danielspaniel/ember-data-factory-guy#123]
Need to write a function to properly format the errors for JSONAPI adapter

**Comment by begedin** [comment]
Is there an instance in the addon where errors are generated automatically (not using `andFail`)? 

The reason I ask is because, for instance, this approach seems to be working fine on our side:

```
TestHelper.handleCreate('subscription').andFail({
  status: 422, response: {
    errors: {
      base: {
        param: "cvc",
        message: "Your card's security code is incorrect."
      }
    }
  }
});
```

`InvokeError` wraps this format (which we are getting from our AMS-based API as well) just fine.

**Comment by danielspaniel** [comment]
Yes @begedin .. the problem is in testing only ( and is kind of annoying ) .. where I have to make tests for the different adapters that all look the same .. but the errors style is different for JSONAPI .. so it's not a big big deal, because the andFail method just sets status to 500, and the users normally enter their own errors in whatever format they need.

**Comment by danielspaniel** [comment]
I reckon v 2.7.0-beta.9 solves my original problem because I am formatting automatically and giving the option to skip that formatting with convertErrors flag
