### ISSUE TITLE
dependancy on jQuery^2.1

### ISSUE THREAD

**Issue by Andrew-Max** [danielspaniel/ember-data-factory-guy#130]
Seems unnecessary given that there weren't api changes between 1.9 and 2.1 and the jquery < 2 allow use of older browsers.

Would it be possible to switch the Bower.json to 

``"jquery": ">1.9",``

**Comment by danielspaniel** [comment]
sure thing @Andrew-Max .. this setting for query has been there for months .. never really thought about it till now. change on the way.

**Comment by danielspaniel** [comment]
v2.0.2 has this fix .. happy factorying!

**Comment by Andrew-Max** [comment]
Woah! Warp speed patches. 

Thank you so much!

**Comment by danielspaniel** [comment]
Your super welcome @Andrew-Max , and sure thing, next time a PR would be nice ( just fun to contribute I think )
