### ISSUE TITLE
Issues Getting Started

### ISSUE THREAD

**Issue by Andrew-Max** [danielspaniel/ember-data-factory-guy#131]
Had two issues while installing. Resolved both but thought the solutions may be useful for updating documention or possible as fixes.

I'm happy to put in fixes if desired but I don't quite understand if my fixes apply to everyone.

issue one: app failed to boot with error ``Path or pattern "bower_components/jquery-mockjax/jquery.mockjax.js" did not match any files``

resolution: in lib/ember-addon/index.js:12 I changed ``'/jquery-mockjax/jquery.mockjax.js');`` to ``'/jquery-mockjax/dist/jquery.mockjax.min.js');``

issue-two: Docs show importing the library via ``import FactoryGuy from 'ember-data-factory-guy';`` which was not resolving for me

resolution: ``import FactoryGuy from 'factory-guy'`` resolves itself based on lib/ember-addon/index.js:15

Please let me know if it would be useful for me to put in pr's regarding any of this

**Comment by Andrew-Max** [comment]
It appears that this stemmed from using the ember cli app located at  https://github.com/cristinawithout/ember-cli-data-factory-guy

not actually  an issue with this repo although very confusing. I'll put in an issue over there but might be worth getting in touch with cristinawithout and just getting that repo to link to the cli repo here

**Comment by danielspaniel** [comment]
Hmm .. I talked to christina ( from that cli-factory-guy-repo ) and told her to mark as deprecated, which I think she did? ) ... not sure.  But I will check on that again.

**Comment by danielspaniel** [comment]
Looks like that other repo already has a notice ( which I think I put there ) that says it is deprecated .. I can put that in bold letters maybe ..?
