### ISSUE TITLE
Suggestion: Multiple handleFindAll calls should override the previous mock

### ISSUE THREAD

**Issue by begedin** [danielspaniel/ember-data-factory-guy#132]
In our app, after a sucessfull login, we always get redirected to the same route, let's say /cars.

Due to that, each test that involves being logged in requires us to mock `handleFindAll('car', 0)`, just so it doesn't fail. It would make sense for our standard integration module config to include a `handleFindAll('car', 0)` in the `beforeEach`. However, if we do that, then there's no way to mock `handleFindAll` in tests that require us having actual car data returned.

Because of that, I feel that subsequent "handleFinds" should overwrite the previous calls. It makes sense with `handleFindAll` but it might also make sense with `handleFind` if we provide an id and the id is identical to a previous one.

Any thoughts on that?

**Comment by danielspaniel** [comment]
Well, let's see .. I think what you just said, was that most of the time you don't need cars, so you just stub the find('cars') with  => handleFindAll('cars', 0)   in the beforeEach for all test just to get that covered. 

 But sometimes, you do want to have cars. So you kind of want to cancel that and do handleFindAll('cars', 2 )

 2 and 1/2  thoughts:

 1. You could just do:  handleFindAll('cars', 2 ) for all tests so you always have cars. 
 2. You have to be more clever in how you set up your tests to allow you to determine what is setup ( can't use beforeEach for everything if it really is not for everything .. but just a whole lot ) 
 I struggle with this every time I write tests. ( your exact problem comes up often ). 
 I have done something like get rid of beforeEach call like you have and have a method which does the setup so each test has the exact setup it needs. It seems like this is the best approach ( it's what I do ) 
 2 1/2 .. You could do a mockjax.clear() before that test that needs to do the same call again. then do handleFindAll('cars', 2 ) to get your 2 cars.

**Comment by danielspaniel** [comment]
I think I have this fixed in the new version 2.3.2 

take a look at the last test in this file: [users-view-test.js](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/tests/acceptance/users-view-test.js)  .. let me know if that does what you want

**Comment by begedin** [comment]
@danielspaniel Yes, that test seems to do exactly what we would like, so you can consider this closed.
