### ISSUE TITLE
handleFindAll() mockjax return always includes embedded reccords

### ISSUE THREAD

**Issue by Andrew-Max** [danielspaniel/ember-data-factory-guy#134]
I have two models: map and flight.

When I call: 
```
TestHelper.handleFindAll('map', 3);
```

I get an error 

``Error: Assertion Failed: Ember Data expected a number or string to represent the record(s) in the `flight` relationship instead it found an object. If this is a polymorphic relationship please specify a `type` key. If this is an embedded relationship please include the `DS.EmbeddedRecordsMixin` and specify the `flight` property in your serializer's attrs object.``

Because a flight object is embedded in the returned record instead of the id which the serializer is looking for.

If I create a custom serializer for map which specifies that flights should be embedded with DS.EmbeddedRecordsMixin, this error goes away but I can't do this because my backend does not embed that record so the app breaks.

As far as I can see I have two options:

1) Create a test only serializer for flight which seems undesirable and I wouldn't even know how to do it.

2) Prevent mockjax from embedding the flight record and ask factory-guy to create it seperately.

Are either of these feasible or am I missing something here?

**Comment by danielspaniel** [comment]
you puzzle me @Andrew-Max  
 you said you had two models ( map and site ) .. is there also a flight object? 
  huh? 
 Me confused. 

 Would be nice if you laid this out alittle better ( more detail ) .
 As it is I kinda am just guessing as to what your talking about/ and need help on.

**Comment by Andrew-Max** [comment]
Fixed! I am not a smart man ...

**Comment by danielspaniel** [comment]
whew .. was about to call my mommy and start crying .. thanks for saving me the embarrasment :)

**Comment by Andrew-Max** [comment]
@danielspaniel  I should have clarified, I fixed my typo in the original post but I did not resolve the issue. I still get the serializer error with this setup. 

I added more code examples in the original comment

**Comment by Andrew-Max** [comment]
@danielspaniel  Sorry I should have specified, I fixed the typo in the original issue but I did not actually resolve the issue.

One thing which I did find solves the issue is to change
``flight: FactoryGuy.belongsTo('flight'),``
to
`` flight: 1,``

But that doesn't match up with the documentation.

Any thought on whether or not that makes sense?

**Comment by danielspaniel** [comment]
what version are you using of factory guy/ ember data?? 
 what do you get when you do =>  FactoryGuy.build('map')  // can you post it

**Comment by Andrew-Max** [comment]
"ember-data": "1.13.6",
    "ember-data-factory-guy": "1.13.10",

with: ``flight: FactoryGuy.belongsTo('flight')``

I get: 
``Object {type: "ortho", fileUrl: "test-orthomaps/M", flight: Object, layers: Array[0]…}``

with: ``flight: 1``
I get:

``Object {type: "ortho", fileUrl: "test-orthomaps/M", flight: 1, layers: Array[0]…}``

Which seems to match up with what I would expect

**Comment by danielspaniel** [comment]
what do your models look like?

**Comment by Andrew-Max** [comment]
map-model: 

```
export default DS.Model.extend({
  fileUrl: DS.attr('string'),
  type: DS.attr('string'),
  urlPrefix: DS.attr('string'),
  flight: DS.belongsTo('flight', {async: true}),
  mapLayers: DS.hasMany('map-layer', {async: true}),
  kmlLayers: DS.hasMany('kml-layer', {async: true}),

  displayUrl: function () {
    return this.get('urlPrefix') + this.get('fileUrl');
  }.property('fileUrl')
});
```

```
export default DS.Model.extend({
  executeAt: DS.attr('string'),
  maps: DS.hasMany('map', {async: true}),
  site: DS.belongsTo('site', {async: true}),
  twoDimProductsUrl: DS.attr('string'),
  threeDimProductsUrl: DS.attr('string'),
  photosUrl: DS.attr('string')
});
```

**Comment by danielspaniel** [comment]
second one is flight .. I reckon.  Looks fine. 
Can you switch to latest factoryguy 2.0.3 . I think it works with ember-data 1.13 as well, and I think it might solve this problem

**Comment by Andrew-Max** [comment]
Yes, I  will give that a go and report back later today. I really appreciate all the help.

**Comment by Andrew-Max** [comment]
Upgrading to 2.03 fixed this issue! Many thanks @danielspaniel

**Comment by danielspaniel** [comment]
hooray .. I am glad you back in business! :)
