### ISSUE TITLE
setStore error

### ISSUE THREAD

**Issue by Asherlc** [danielspaniel/ember-data-factory-guy#135]
I'm getting the following error when trying to a model test according to the sample model test: `FactoryGuy does not have the application's store. Use FactoryGuy.setStore(store) before making any fixtures`

I don't see any mention of this in the docs, but it looks like there were some issues related to ember-data versions, so I've tried a bunch of different version combinations, and I'm now running ember-data-factory-guy:1.13.10, ember-data: 1.13.5, and ember-data: 1.13.5. All version combos I tried raised the same error.

Here's the test:
```
import Ember from 'ember';
import FactoryGuy, { make } from 'ember-data-factory-guy';
import { module, test } from 'qunit';

module('Unit | Model | batch draw', {
  afterEach: function() {
    Ember.run(FactoryGuy, 'clearStore');
  }
});

test('it exists', function(assert) {
  const model = make('batch-draw');

  assert.ok(!!model);
});
```

**Comment by danielspaniel** [comment]
@Asherlc sounds like this is setup issue. how did you install factory-guy?

**Comment by Asherlc** [comment]
I've just been using `ember install ember-data-factory-guy@1.13.10 ` (and rm -rf'ing my bower_components and node_modules folders when trying different versions)

**Comment by danielspaniel** [comment]
i was afraid of that .. because that is all pretty good.  what version of ember-cli are you on .. I will try and duplicate setting up new project with those settings.

**Comment by Asherlc** [comment]
Looks like I'm using 1.13.8. Thanks for the quick help, it's much appreciated!

**Comment by danielspaniel** [comment]
already I saw a strange issue where it did not install mockjax .. seems like the initializer did not run on the addon .. trying to figure out why at the moment

**Comment by danielspaniel** [comment]
this is really a puzzler .. because everything works for newer version .. curious if you can try on ember 2? with the latest factory guy .. while I try and figure out why it's not working for older versions on the newest cli version ( groan ) .. totally a bummer that things are so sensitive.
 I am guessing that the latest cli ( the way it handles addon callbacks ) has something to do with it .. but I don't know yet

**Comment by Asherlc** [comment]
huh.. . that's a bummer. unfortunately i'm using another wide-ranging ember addon that's yet to be 2.0 compliant (the constant Ember struggle), so I can't really try using 2.0 without a lot of other changes. Is the problem with the ember-cli version? because if so, it seems like i might just be able to upgrade that to whatever the latest version is, without messing with Ember itself, right?

**Comment by danielspaniel** [comment]
yeah .. bummer.. but that is the constant struggle for sure. feel like burying my head in the sand right now, but I will keep trying this and that to nail it down .. at this point I am not sure what it is.

**Comment by jcope2013** [comment]
I ran into same issue, you can use the other test pattern to get around it

https://github.com/danielspaniel/ember-data-factory-guy/blob/master/tests/unit/models/profile-test.js

**Comment by danielspaniel** [comment]
good point @jcope2013 , I would have mentioned that .. which you should definitely try @Asherlc , but I am trying to figure out why mockjax is not being installed when addon is installed ( that kills (ember t )  test run right away )

**Comment by danielspaniel** [comment]
ok .. @Asherlc , @jcope2013 was right on .. I am not sure why the initializer is not starting up factory guy sometimes for some versions . but that solves the problem ( thanks dude .. you saved my bacon  .. cause I forgot about that one ) 
 and just for funsies .... you can use the latest 2.0.3 factory guy .. seems to work fine with 1.13.8

**Comment by danielspaniel** [comment]
I updated the README to use the profile-test style that always works .. over the other style that sometimes does not work. So @Asherlc , let me know if you are all set and close the issue if you are??

**Comment by Asherlc** [comment]
@danielspaniel looks like that solves it. thanks!
