### ISSUE TITLE
Underlying network request not mocked

### ISSUE THREAD

**Issue by prismbent** [danielspaniel/ember-data-factory-guy#137]
https://gist.github.com/prismbent/a195bf89d289ee34632f - foreign model
https://gist.github.com/prismbent/61c5700ed6280c37782f - main model
https://gist.github.com/prismbent/c88d8c11b92031d5a80f - foreign model factory
https://gist.github.com/prismbent/a9a29c9c2790858c5386 - main model factory
https://gist.github.com/prismbent/509bd5c53699b599d789 - acceptance test
https://gist.github.com/prismbent/a1bd71f5d892b4248b0f - route

**Comment by danielspaniel** [comment]
@prismbent .. hmm .. two things .. in the test .. I think you are better off  using TestHelper.handleFind or TestHelper.handleFindQuery .. rather than making stuff first before visiting.  Other people have submitted issues that ember-data is no longer happy with this style ( the way you did it ) 
  The other thing is you are going to have to check to see what the network request is exactly ( chrome dev tools - network tab   while using your app in development mode ) .. to see what the url is for that pagination library's findPaginated is 
 because FactoryGuy can't guess what the query will be .. have to be certain so you know how to stub it.
 
 But what are the errors you have now?

**Comment by danielspaniel** [comment]
if you get me the url I can try and help to figure out how to mock it or override handleFind/handleFindQuery to mock it

**Comment by prismbent** [comment]
Hey Daniel,

     I had tried with not making the model prior to handling the query, the
query being this -

http://localhost:8000/api/1/usersubmittedquestions/?page=1&per_page=20&status=0

but that still didn't usurp the network request.

Back to handle/making the model in the acceptance test - in the docs it
seemed that "making" a model would return something directly from the store
as it's already in the store and skip the network request.



Melissa Zhang

*"Most important things are not zero sum."*

**Comment by danielspaniel** [comment]
very good point @prismbent  .. about the documentation .. which I have to change because that does not work anymore with latest ember-data 1.13+ ( my mistake because I did not have a test to catch that .. I just assumed it would always work ) so you have to mock the url with TestHelper.handleQuery I am guessing .. 
 and handleQuery allows you to make records and pass then in as the items you want returned   
 like so:
```
    var users = FactoryGuy.makeList('user', 2);
    TestHelper.handleQuery('user', {name: 'Bob'}, users);
    // network request will return those two users
```
  instead of {name: 'Bob} or params .. try {} 
or
```
  TestHelper.handleQuery('user-submitted-question', {name: 'Bob'}, users);
```

**Comment by prismbent** [comment]
I'm trying both 
` let user1 = make('user');
  TestHelper.handleFindAll('usersubmittedquestion', {page: 1, per_page: 20, status: 0}, user1);`

and

`  TestHelper.handleFindAll('usersubmittedquestion', {page: 1, per_page: 20, status: 0});`

and both are still making the network request.

**Comment by danielspaniel** [comment]
I figured they would @prismbent , but it is alot closer .. what I do in these situations is look at the mockjax library which is in your bower directory 
 go to line 114 
```
function getMockForRequest( handler, requestSettings ) {
```
 and console log or debugger that sucker right after that line and you can see the handler.url  .. which is the url that FactoryGuy makes .. and tell me what you find  

  isn't this fun? :)

 also let me know what the requestSettings in them

**Comment by prismbent** [comment]
this is the response
```{url: "http://localhost:8000/api/1/usersubmittedquestions/", type: "GET", isLocal: false, global: true, processData: true…}```

**Comment by danielspaniel** [comment]
that looks pretty good .. does it not?  
 can you console or debugger and see if things go as far as line 136 .. which means the url matches, and then we have to check the requestSettings  property to make sure they match .. 

 on line 137 
``` 
// Inspect the request headers submitted
```
 it starts checking headers

 what do you see for: handler.requestHeaders ( in console ) and the requestSettings.headers

**Comment by prismbent** [comment]
There is no requestHeaders object off of the handler.

**Comment by danielspaniel** [comment]
but the url matches .. right?

**Comment by prismbent** [comment]
Yes.

**Comment by danielspaniel** [comment]
and are there requestSettings.headers  ?

**Comment by danielspaniel** [comment]
if so what are they?

**Comment by prismbent** [comment]
Nope that's undefined.

**Comment by danielspaniel** [comment]
most likely this will not be too relevant and it will skip down to line158 .. where it checks the data
 but I wanted to be super sure before we move on .. ok .. great

**Comment by danielspaniel** [comment]
so what is in 
 requestSettings.data
 vs 
 handler.data

**Comment by prismbent** [comment]
requestSettings.data = Object {page: 1, per_page: 20, status: 0}
handler.data = undefined

**Comment by danielspaniel** [comment]
i guess you found the problem .. congratulations .. guess that solved that problem ..

**Comment by danielspaniel** [comment]
bigger problem .. how to fix it?.. thinking ...

**Comment by danielspaniel** [comment]
can you put that data into handleQuery call like:

```
 TestHelper.handleQuery('user...', {page: 1, per_page: 20, status: 0}, [user])
```
 run it and see if the correct data shows up in handler.data

**Comment by prismbent** [comment]
Yes, that's there now. 

This in appearing in the console now - `Error while processing route: qanda.index Assertion Failed: You must include an 'id' for usersubmittedquestion in an object passed to 'push' Error: Assertion Failed: You must include an 'id' for usersubmittedquestion in an object passed to 'push' `

**Comment by danielspaniel** [comment]
ok .. back to that mockjax file 
 what does the handler.responseText   property have in it?

**Comment by prismbent** [comment]
``usersubmittedquestions: Array[1]
0: Object
email: "user1@something.com"
first_name: "firstname1"
id: "1"
is_active: true
is_active_subscriber: true
is_staff: false
is_superuser: false
last_name: "lastname1"
username: "user1"```

**Comment by danielspaniel** [comment]
hmm .. i see an id there .. which I am sure you do too .. 
 which looks ok to me

**Comment by danielspaniel** [comment]
what top level attributes .. what do you expect the json to look like?

**Comment by danielspaniel** [comment]
it does .. but are not all those attributes setup in the factory .. and are they not in that object ?  what is missing? 
 also .. where exactly is that error being thrown ( from the route? or ember data ? )

**Comment by prismbent** [comment]
usersubmittedquestions: Array[1] 0: Object email: "user1@something.com" first_name: "firstname1" id: "1" is_active: true is_active_subscriber: true is_staff: false is_superuser: false last_name: "lastname1" username: "user1",
  [[[TOP LEVEL
    submitted_at: 10,
    status: 10,
    question: "Test Question",
    submitted_by: FactoryGuy.belongsTo('user'),
    summarized_question: ""]]]`

That error is thrown from Ember.debug

**Comment by danielspaniel** [comment]
ok .. yeah .. I see what you mean 
 what do you get when you FactoryGuy.build('usersubmittedquestion')  ??

**Comment by prismbent** [comment]
```  let user = make('user');
  build('usersubmittedquestion');
  // TestHelper.handleFindAll('usersubmittedquestion', {page: 1, per_page: 20, status: 0});
  TestHelper.handleQuery('usersubmittedquestion', {page: 1, per_page: 20, status: 0}, [user]);```

With that I'm still not seeing the top level attributes.

**Comment by danielspaniel** [comment]
what I mean is just do console.log(build('usersubmittedquestions'))  .. what do you see?

**Comment by danielspaniel** [comment]
in your factory 

```
 default: {
    user: {}, /// this line not needed
    submitted_at: new Date(),
    status: 10,
    question: "Test Question",
    submitted_by: FactoryGuy.belongsTo('user'),  // since this is the user
    summarized_question: ""
  },
```

**Comment by prismbent** [comment]
Sorry, where should I be placing this console.log?

**Comment by danielspaniel** [comment]
wherever .. but maybe at the start of the test ( before you visit )

**Comment by prismbent** [comment]
That does seem to have both the top level attributes and the user attributes - 
`usersubmittedquestion: {
       id: 1
      question: "Test Question"
      status: 10  
      submitted_at: 10
      submitted_by: 1}, 
users: Array[1 ...]}`

**Comment by danielspaniel** [comment]
instead of all this:

```
let user = make('user'); build('usersubmittedquestion'); // TestHelper.handleFindAll('usersubmittedquestion', {page: 1, per_page: 20, status: 0}); TestHelper.handleQuery('usersubmittedquestion', {page: 1, per_page: 20, status: 0}, [user]);
```

try this:
```
let submittedQuestion = make('usersubmittedquestion'); 
TestHelper.handleQuery('usersubmittedquestion', {page: 1, per_page: 20, status: 0}, [submittedQuestion]);
```

**Comment by prismbent** [comment]
With that I'm still getting no id for push for usersubmittedquestion. I tried console.logging a build(usersubmittedquestion) right after and the id for it prints as two so the first make seems like it is generating an id for it.

**Comment by danielspaniel** [comment]
this seems like adapter issue .. 
 for example, if you try and pass that json to store.push it will fail because the store now only accepts jsonapi json .. which factory guy gets around by converting all json to jsonap right in make right after it builds but before it pushes to store.
 so I am guessing something odd is happening like your adapter is activemodel but serializer is jsonapi ?? 
  what are your adapter and serializers ?

**Comment by danielspaniel** [comment]
you could also, try 
var json = FactoryGuy.build('blah') .. maybe build('user') .. something simple and then 

FactoryGuy.getStore().pushPayload(json)

does that work?  if it does try build('usersubmittedquestion')

**Comment by prismbent** [comment]
I'm using a drf adapater and serializer. I've created a gist for the two here -

https://gist.github.com/prismbent/637026edd9a9f56fa89f and
https://gist.github.com/prismbent/57ae0f1b39bdecf7d78c

using 
```let userJson = build("usersubmittedquestion");
  FactoryGuy.getStore().pushPayload(userJson);```

still gives me the same error of failing to have an id on push to store. Not familiar enough yet with the serializer to say why this is failing.

**Comment by danielspaniel** [comment]
what is in the file './drf' here that you are importing?
``` import DRFSerializer from './drf'; ```

**Comment by danielspaniel** [comment]
is that ember-drf  .. is that basically like rest adapter ?  FactoryGuy only supports REST, ActiveModel and JSONAPI adapters at the moment, so that might be issue, but I am not sure .. 
  This all works when your in development right, and your site works fine? 
  I wonder if you could go to chrome dev tools at the console and go to network tab and then go to route '/' and tell me what the response json is being passed ( to the adapter ) .. will tell me if I can support that or not

**Comment by prismbent** [comment]
```{
    "count": 63,
    "next": "http://localhost:8000/api/1/usersubmittedquestions/?status=0&per_page=20&page=2",
    "previous": null,
    "results": [{
        "id": 92,
        "submitted_by": {
            "id": 1,
            "username": "prismbent",
            "first_name": "Melissa",
            "last_name": "Zhang",
            "email": "mzhang@whalerockindustries.com",
            "is_active": true,
            "is_staff": true,
            "is_superuser": true,
            "is_active_subscriber": false,
            "belongs_to": []
        },
        "submitted_at": "2015-08-10T00:27:17.491403Z",
        "status": 0,
        "question": "asdf",
        "summarized_question": "asdf"
    }, {
        "id": 91,
        "submitted_by": {
            "id": 1,
            "username": "prismbent",
            "first_name": "Melissa",
            "last_name": "Zhang",
            "email": "mzhang@whalerockindustries.com",
            "is_active": true,
            "is_staff": true,
            "is_superuser": true,
            "is_active_subscriber": false,
            "belongs_to": []
        },
        "submitted_at": "2015-08-10T00:27:11.101533Z",
        "status": 0,
        "question": "asdfasdf",
        "summarized_question": "asdfdf"
    }, {
        "id": 90,
        "submitted_by": {
            "id": 1,
            "username": "prismbent",
            "first_name": "Melissa",
            "last_name": "Zhang",
            "email": "mzhang@whalerockindustries.com",
            "is_active": true,
            "is_staff": true,
            "is_superuser": true,
            "is_active_subscriber": false,
            "belongs_to": []
        },
        "submitted_at": "2015-08-10T00:27:04.491526Z",
        "status": 0,
        "question": "asdfasdf",
        "summarized_question": "asdfasdf"
    }]
}```

I am importing a Django Rest Serializer.

**Comment by danielspaniel** [comment]
hmm . .yeah .. this is a bummer .. it looks like the drf serializer is not normalizing the data back to what ember-data expects .. for the submitted_by ( belongs_to ) association .. an object is not allowed ( unless polymorphic ) .. need to be sideloaded like this:

```json
    profile: {
      id: 1,
      description: "Text goes here",
      camelCaseDescription: "textGoesHere",
      snake_case_description: "text_goes_here",
      superHero: 1,
    },
    'super-heros': [
      {
        id: 1,
        name: "BatMan",
        type: "SuperHero"
      }
    ]
  }
```

this is how factory guy  converts a payload with belongs_to association for REST adapter. 

 you could easily ( sort of ) .. write a converter for DRS and make it so factory guy can prepare this property for you.  

 I could be wrong .. ( if that DRF adapter is a subclass of DS.RESTAdapter .. is it? do you know? ) but I think that is the issue.

**Comment by danielspaniel** [comment]
wait .. can you clarify what you sent there .. where was the json produced  .. is that from your server?

**Comment by prismbent** [comment]
that JSON is directly from the server. I think DRF then converts it supposedly into an Ember Data happy format. When we pushPayload, all the work done by the adapter and serializer should have already been done right? I did a peekAll after pushPayload and can't seem to see any data.

**Comment by danielspaniel** [comment]
correct .. the drf is doing the conversion properly .. before pushPayload .. actually before push ...
 but this brings up a good question .. could FactoryGuy use the adaper/serializer you are using to convert the json being built?  then everyone would be happy with any adapter. 
  I think the answer is yes I could, but no it's not right now, because FactoryGuy builds a json packet from the factories that could include a model instance, so I had to do custom converter to handle that. 
  and then for the drf adapter I would be stuck .. because I don't know the format. 
 Anyway .. before I bore you, the answer to this problem is to make a converter for drf adapter .. 
 luckily factory guy is setup to be able to do this really easily .. 
 there is a factory that returns you a converter for an adapter 
  right now it only handles REST or JSONAPI, but if you wrote a converter for drf, you just plug add it to factory and your all set. 
  If you don't feel like doing this ( and submitting a PR ) .. I fully understand .. but I don't have time for at least a month to do it .. though I think if you looked at the code in factory guy you could figure it out pretty quickly .. at least it would be fun.

**Comment by danielspaniel** [comment]
In other words.  
 That json you have should from the server should pushPayload fine to the store ( does it not?).
 The json FactoryGuy produces would not be pushPayloadable to the store without custom converter

**Comment by danielspaniel** [comment]
So, just to be certain, what do you get when you do this:  FactoryGuy.build('usersubmittedquestion') ?

**Comment by danielspaniel** [comment]
are you using .. dustinfarris/ember-django-adapter  ??

**Comment by prismbent** [comment]
yes

**Comment by danielspaniel** [comment]
that is REST based adapter 
 so .. ( once again )  what do you get for FactoryGuy.build('usersubmittedquestion') ?

**Comment by prismbent** [comment]
Ah.. yes. FactoryGuy.build > missing converter > Ember Data Store Happy Format.

I will build a local converter to transform the json FG builds so the drf adapter can deserialize it. If it goes well I'll try to write a PR.

One last question (if I've fully understood the problem) - how does FG.build create formats that will work for both REST, json, and activemodel? I didn't see an example of specifying which adapter to use like - FG.build( "model", adapterType);

**Comment by danielspaniel** [comment]
wait .. I think I might have been wrong about converter .. can you ( once again again ) tell me what you get for FactoryGuy.build('usersubmittedquestion') ?

**Comment by danielspaniel** [comment]
you sent this before:
usersubmittedquestion: { id: 1 question: "Test Question" status: 10 submitted_at: 10 submitted_by: 1}, users: Array[1 ...]}

 that was it right? 
but can you send that again surrounded by 3 backticks so I can see what is in each field ( users just says array, but I want to see what is in there )

**Comment by danielspaniel** [comment]
and what versions of ember-data / factory guy  are you using ?

**Comment by prismbent** [comment]
```{
  "usersubmittedquestion": {
    "submitted_at": 10,
    "status": 10,
    "question": "Test Question",
    "submitted_by": 1,
    "id": 1,
    "links": {}
  },
  "users": [
    {
      "email": "user1@something.com",
      "first_name": "firstname1",
      "is_active": true,
      "is_active_subscriber": true,
      "last_name": "lastname1",
      "username": "user1",
      "id": 1,
      "links": {}
    }
  ]
}```

I am using "version": "1.1.0" of drf.

**Comment by danielspaniel** [comment]
that json looks good. except for one thing.

Can you do me a favour and instead of calling your user a submitted_by
  change to calling it a user .. like this 

 in factory:

 submitted_by: FactoryGuy.belongsTo('user'),
   to ->
 user: FactoryGuy.belongsTo('user'),
  
 model:

 submitted_by: DS.belongsTo('user'),
  to ->
user: DS.belongsTo('user'), 
submitted_by: Em.computed.alias('user')

**Comment by prismbent** [comment]
Hi, I've finally learnt that the drf adapter I'm using has a check that just proxies the data to process something like it's REST format so the converter for this didn't need to be built. However, I'm running into another question with trying to pass in stubbed data for handleQuery. I have a belongsTo relationship which means i have this kind of format:

``` {usersubmittedquestion: [ {...}. {...} ], user: [ {}, {} ]```

HandleQuery expects things to be in an array. From `Buildlist` to `handleQuery`, is there an easy way to format the data to something `handleQuery` can handle?

**Comment by danielspaniel** [comment]
@prismbent ..  I already told you it was a REST based adapter .. but congratulations on figuring that out yourself. It sure makes it easy for me. I don't have to do anything. 
  Take a look at issue #139 .. at the end and see if that is what you are looking for ( does that returnJSON .. look useful? )
