### ISSUE TITLE
Q: Association based data

### ISSUE THREAD

**Issue by taheilo** [danielspaniel/ember-data-factory-guy#138]
Im currently setting up my factories and I'm struggling with generating the data I need.

I have a setup with x models. 

Example:
Projects hasMany materials, hasMany inspections
Projects has a status property (planning, started, completed etc).

The problem I have is that the status property on projects has a direct influence on the inspections and materials models. Is there a way to hook into this property when generating the other models?

make('project', 'in_planning') would give me a inspections association with inspect: false
make('project', 'is_started') would give me a inspections association with inspect: true

Ember: 1.13.7
Factory Guy: 1.13.10

**Comment by danielspaniel** [comment]
@taheilo, yes you can do something in factories like:

```
FactoryGuy.define('project', {
  transient: {
    for_sale: true
  },
  traits: {
    is_started: {
      status: 'started',
      inspections: FactoryGuy.hasMany('inspections', 2, {inspect: true})
    }
  }
```

 would this do it for you?
 there are a few other techniques to look at like 'afterMake'
  or doing a scenario builder ( a concept which I use ) .. a special class to build scenarios with that is customized for building projects and it kinda fancy but very very great tool for spinning up complex scenarios.

**Comment by taheilo** [comment]
Sweet! I think that would definitely do the trick. Thank you @danielspaniel
