### ISSUE TITLE
Allow 'custom' response on `handle...` calls

### ISSUE THREAD

**Issue by trisrael** [danielspaniel/ember-data-factory-guy#139]
Sideloading is large component of ember-data via it's implementation of [JSON API](http://jsonapi.org/implementations/#client-libraries-javascript).

However, the `handle` calls seem to only be able to handle a single model at a time ( unless I'm mistaken).

I propose the ability to optionally pass in a hash instead to these functions that allows for definition by the user as a beginning road for support. 

It also seems possible to pass in several factory guy model arrays or single models and to use inflection on the type to build the associated JSON response.

_Custom reponse_
``` javascript
var customResponse = {
  "user": build('user'),
  "groups": buildList('group')
};
handleQuery('user', {id: 'me', "include[]": ".groups"}, customResponse)
```

_Pseudo code of naive future API definition_
``` javascript
var groups = makeList('group')
var user  = make('user')
handleQuery('user', {id: 'me'}, user, groups)
//returns based on array or if factory guy model
//"user": { }
//"groups":[...]

```
[`handleQuery`](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/vendor/assets/javascripts/ember_data_factory_guy.js#L1122) only handles `records` but ideally 

Currently. I have to perform `make` calls first  - but this kind of defeats the usage of `handle` as they are already placed in the store. Want to rely on the XHR mocking/stubbing completely to use as close a model to the user's experience as I can.

**Comment by danielspaniel** [comment]
what version of FactoryGuy are you on?  can you try upgrading to the very latest factoryguy 2.1.0 ?  It handles sideloading better than older versions, and probably does what you want already .. give it a try and let me know

**Comment by trisrael** [comment]
Okay I'm trying out - it's available via usage of traits because of `handle` falling back to use `build` / `buildList`. 

So far found it difficult to build specific scenarios using the `handle` without using `make` to explicitly build up the relationships I want

**Comment by danielspaniel** [comment]
yes traits help out for building relationships, but handleQuery does not return json ( as you correctly point out )  I am not sure exactly why I did that .. but I am sure I will remember once I try and change it. 
 But you make a good point, that it would be nice to do 

so something like:

 ```
var user = make('user')
handleQuery('user', {id: 'me'}).returnsModel([user]);
var user = make('user', 'with_groups')
handleQuery('user', {id: 'me', 'include[]': 'groups'}).returnsModels([user]);

handleQuery('user', {id: 'me'}).returnsJSON('user');
handleQuery('user', {id: 'me', 'include[]': 'groups'}).returnsJSON('user','with_groups');
```

would that work for your case?

**Comment by trisrael** [comment]
Something along these lines would be what I'm looking for I believe. Maybe I'll close this issue for now.

I'm working with traits and seeing if they can resolve most of my issues. I have a feeling I won't be able to model everything through traits however. I'll have a look at how the sideloads are built up but still feel that I'll need 

``` returnsJSON({user: user.toJSON(), groups: [group.toJSON()]...``` 

allowing for custom json responses still.


____

Also separately.

I feel like I'd still like a ember data model that has not been pushed into the store yet ( or uses a flag that makes in inactive ) if possible so mocked requests are truly 

```
var adminGroup = make('group', {type: 'admin'}, {live: false});
var admin1 = make('user', groups: [group], {live: false});
var admin2 = make('user', groups: [group], {live: false});
```

Where `live` in this case would mean fully pushed into store.  Don't care about the syntax but just ability to differentiate between items pushed and those not - to be able to use `handle`

**Comment by danielspaniel** [comment]
I think it's a legit case to want to to returnsJSON .. it's on my list of things to do .. 
 the {live: false} for a make seems alittle odd .. 'make' is for making stuff and pushing in the store.
 'build'  will build json  for you ( which is what I think you want ) .. so do you mean build('user')  

  var group = build('group' )
  var user = buildList('user',2, {group: group}); // can't do this now ( but I will try and do )  will have users and groups sideloaded

  which is what I would use to do the returnsJSON({user: user})

**Comment by danielspaniel** [comment]
can you do me a favour and make the specific use cases for me that you would like to see for (returnsModel and returnsJSON ) chained to handleQuery ( for now I will start with that on ) .. I put some examples a few comments ago, but I want you to verify and lay it out super clearly .. since I don't want to build something from my imagination of what you might need.

**Comment by trisrael** [comment]
Will do. I do a lot of context switching at work - so these examples are coming slower. But I will put forth a use case that doesn't feel like it can be supported through the traits.

I do like the direction that build('group'), buildList that you put above, which I think should do it. But I think I'd rather still have interim objects, that I can call to JSON on eventually.

Just showing the following as an example of what would be nice in order to build up a set of relationships outside of the trait system. Not suggesting the `toJSON` API
```
  let group = build('group');
  let admin = build('user', 'admin', {group: group});
  let moderator =  build('user', 'moderator', {group: group});
  let modCanEdit = build('permission', 'edit', {user: moderator});
  let adminCanEdit = build('permission', 'edit', {user: admin});

  ...returnsJSON({group: group, users: [moderator, admin], permissions: [modCanEdit, adminCanEdit]})
```

The example above is simple ( and the permissions could be done using traits ) but I'm sure there are scenarios that can't be done with traits similar to the above and some where you would want to have this control outside of traits.

**Comment by danielspaniel** [comment]
release 2.1.1  and 3 new methods to handleQuery which should allow you to do what you want

returnsJSON  .. json from buildList
returnsModels  .. array of models
returnsExistingIds .. array of ids of models that exist

 check them out and let me know what you think .. or if you need more of something
