### ISSUE TITLE
final production build include full ember-data-factory-guy library in vendor.js

### ISSUE THREAD

**Issue by junos** [danielspaniel/ember-data-factory-guy#140]
The issue is: we need to get rid of  "ember-data-factory-guy" library in vendor.js for production build.

Steps to re-production the issue:

1. add "ember-data-factory-guy" in package.json devDenendencies
2. npm install
3. import  '"ember-data-factory-guy" in our  test js file
3. excute ember cli build command in production mode
4. in vendor.js file, it include the full package of "ember-data-factory-guy"

**Comment by danielspaniel** [comment]
@junos .. why are you adding factory guy to devDependencies? 
 why don't you ->  ember install ember-data-factory-guy? 
  does that still include it in vendor.js ? it should not. no?

**Comment by junos** [comment]
It still don't work for me.

This is what I did:
1. clean bower cache, clean npm cache
2. rm -rf node_modules bower_components dist tmp
3. npm install
4. bower install
5. ember install ember-data-factory-guy
6. ember build --environment production
after these, vendor.js still include ember-data-factory-guy code

**Comment by danielspaniel** [comment]
why is this an issue .. ?? curious

**Comment by junos** [comment]
1. We don't want any test package in production release.
2. To exclude these test packages, it will minimize size of vendor.js and improve the page loading time.
3. curious why ember-data-factory-guy behave different with other js libraries.

**Comment by danielspaniel** [comment]
some addons like ember-cli-qunit install bower components ember-qunit, qunit .. etc 
 some addons don't .. since they are just addons ( and not specifically test addons ) 
 I agree that it would be great to exclude it .. 
 and I think what I would have to do is to make a bower build and include that when someone installs factory guy 
  is there another addon that is able to exclude itself from production vendor.js  that you know of ?

**Comment by junos** [comment]
For example, ember-sinon, could you define your package type as 'test'? so it only included in test dependances, https://github.com/csantero/ember-sinon/blob/master/index.js#L10

**Comment by danielspaniel** [comment]
right .. ember-sinon like ember-qunit both install the bower packages ( sinon and qunit and ember-qunit ( they made a bower package for ember-qunit ) 
 I think the answer is to do like ember or ember-data and install factory as bower component the way these do for now .. till ember-cli supports this sort of thing the way rails does .. asset groups 
 but I can't do it right now .. next week I can work on it when I do a few other upgrades

**Comment by danielspaniel** [comment]
can you open an issue on the ember-cli repo stating this very issue .. I think it's a good one

**Comment by junos** [comment]
OK, do you think this help? I file a ticket here: https://github.com/ember-cli/ember-cli/issues/4993

**Comment by danielspaniel** [comment]
yes, that helps .. thanks .. I will check out treeForTestSupport and see if that does it.

**Comment by danielspaniel** [comment]
Also, this might be a nice thing to try to get working  ( make a branch .. and try to get it working as you want and submit as pull request ).

**Comment by afn** [comment]
Any update on this issue?

**Comment by danielspaniel** [comment]
I was hoping you would help fix it? Any interest?
