### ISSUE TITLE
Buggette with cheese - extractAttributes 0 should not be false

### ISSUE THREAD

**Issue by davetheninja** [danielspaniel/ember-data-factory-guy#146]
Hey Daniel 

Found a bug today where my fixture value is 0 however in ExtractAttributes it doesn't guard for true value:

If (fixture[attribute]).... 

Should be

If (fixture[attribute]  ! == null || fixture[attribute] !== undefined).... 

Will fix locally for now. Patch later. 

Davie

**Comment by danielspaniel** [comment]
@davetheninja, that is such a typical bug ( happens all the time in my other code ) .. I usually use Ember.isPresent(value) .. just a suggestion .. I might be able to patch that up for you .. pretty simple dimple.

**Comment by danielspaniel** [comment]
actually .. I think that is already fixed by the PR from someone else I merged yesterday so that code is now
```
 var extractAttributes = function (modelName, fixture) {
    var attributes = {};
    var transformFunction = getTransformFunction(modelName, 'Attribute');
    store.modelFor(modelName).eachAttribute(function (attribute) {
      var attributeKey = transformFunction(attribute);
      if (fixture.hasOwnProperty(attribute)) {
        attributes[attributeKey] = fixture[attribute];
      } else if (fixture.hasOwnProperty(attributeKey)) {
        attributes[attributeKey] = fixture[attributeKey];
      }
    });
    return attributes;
  };
```

which should work for that case
 Give v 2.1.1 a try and let me know if that is working for you

**Comment by davetheninja** [comment]
Great thanks 



—

**Comment by danielspaniel** [comment]
and nice punning by the way ( in the title )  :) .. me appreciate

**Comment by davetheninja** [comment]
🎉 



—
