### ISSUE TITLE
Using handleQuery for the same endpoint with different query params

### ISSUE THREAD

**Issue by bryanaka** [danielspaniel/ember-data-factory-guy#151]
Right now, `handleQuery` is only registering one response per endpoint, even if registering with different query parameters.

```js
var post = make('post', { hasComments: true });
var popularPost = make('post', { isPopular: true });
TestHelper.handleQuery('post', { hasComments: true }).returnModels(post);
TestHelper.handleQuery('post', { isPopular: true }).returnModels(popularPost);

// somewhere in app/test code
store.query('post', { isPopular: true }); // fails to match first handler, goes to server
```

After doing some research, seems like this is expected of mockjax's implementation - https://github.com/jakerella/jquery-mockjax/issues/187

and to get further with this kind of implementation, we have to use passed in functions, as the issue suggests. I was wondering if there is any interest for this use case? Or am I doing it wrong?

I have put together something rough from our app here - https://gist.github.com/bryanaka/6ae13f3695b65f7765fe.

**Comment by danielspaniel** [comment]
Hmm .. this is a good reason to change the api to something like this:
```js
   TestHelper.handleQuery('post').withParams({ hasComments: true }).returnModels(post);

   TestHelper.handleQuery('post').withParams({ isPopular: true }).returnModels(popularPost);
```

which would also work like this ( in my imagination):
```javascript
   TestHelper.handleQuery('post', { hasComments: true }).returnModels(post);

   TestHelper.handleQuery('post').withParams({ isPopular: true }).returnModels(popularPost);
``` 
this would be pretty straightforward to whip up if you think this works for you.

**Comment by bryanaka** [comment]
So if I understand correctly, the latter `withParams` would only be needed when doing a duplicate endpoint call with different params? Or would `withParams` completely eliminate passing params into `handleQuery`?

**Comment by danielspaniel** [comment]
I reckon you could use both ways .. but it might be clearer to always use the withParams so it is really obvious that you can use it over and over again. So I would vote to get rid of the inline case and always require withParams .. what do you think?

**Comment by bryanaka** [comment]
IMO `handleQuery(...).withParams(...)` is more clear on initial read; however I am curious then what the default behavior would be if `withParams` is not called. Do you have an idea of what you would want it to be? I think that would need to be clear and useful, otherwise why not build into the initial `handleQuery` call.

I think what you were trying to go for was some unification on the store methods, right? If that is true, maybe the params is best served in the `handleQuery` call. I lean toward this option, but I would want to hear more why you would like to change the API for this use case.

**Comment by danielspaniel** [comment]
I think for the sake of fun, we could keep both ( for now ). 
 Most people will just do the handleQuery(' ', {}).returnsModels()  and call it a day
 but if you want to change the params you can use withParams() after that 
  
it's  simple change that we can then ponder over for a while and decide later what to do next. 
  Agree?

**Comment by bryanaka** [comment]
sounds good to me. Let the people decide :smiley: 

I'm in the middle of updating our app from 1.8.X -> 1.13.X, but after that I will have some time to work on this further. Or we can always tag-team on a PR if you find some time. Let me know what works best.

**Comment by danielspaniel** [comment]
I was just working on this and I saw that I already have a test like this:

```js
  test("using different query params returns different results", function (assert) {
    Ember.run(function () {
      var done = assert.async();

      var companies1 = FactoryGuy.makeList('company', 2);
      TestHelper.handleQuery('company', {name: 'Dude'}).returnsModels(companies1);

      var companies2 = FactoryGuy.makeList('company', 2);
      TestHelper.handleQuery('company', {type: 'Small'}).returnsModels(companies2);

      FactoryGuy.get('store').query('company', {name: 'Dude'}).then(function (companies) {
        equal(companies.mapBy('id')+'', companies1.mapBy('id')+'');

        FactoryGuy.get('store').query('company', {type: 'Small'}).then(function (companies) {
          equal(companies.mapBy('id')+'', companies2.mapBy('id')+'');
          done();
        });
      });
    });
  });
```

which seems to cover your case .. but if I am wrong .. can you change this test to show how your case looks, and how I might get a failing test? so I can fix it?

**Comment by bryanaka** [comment]
interesting. This looks like the case I need, but was definitely failing. Let me fork and try to write a failing test.

**Comment by danielspaniel** [comment]
One thing to note .. and I did not bring it up before because of what you said the error was is that you have to do:

```js
var post = make('post', { hasComments: true });
var popularPost = make('post', { isPopular: true });
TestHelper.handleQuery('post', { hasComments: true }).returnModels([post]);
TestHelper.handleQuery('post', { isPopular: true }).returnModels([popularPost]);
``` 
( basically return an array  and not a single model ) 
that may not be the issue at all .. but worth noting. 

 and thanks for offering a failing test .. very helpful

**Comment by bryanaka** [comment]
yeah my bad, I realized my original write up wasn't probably written in enough detail to really show off the issue.

Here is a closer representation of what the issue is

```js
var posts = makeList('post' 2);
TestHelper.handleQuery('post', { hasComments: true }).returnModels(posts);
TestHelper.handleQuery('post', { hasComments: true, isPopular: true }).returnModels(posts);
```

Whether you return the same array of models or a different array, both fail with a JSON Syntax error. Not sure why though.

Added a failing test here - https://github.com/bryanaka/ember-data-factory-guy/tree/h/query-failing-test

**Comment by danielspaniel** [comment]
Got it and can you give me a clue to how to find the test ... that link just takes me to repo

**Comment by bryanaka** [comment]
https://github.com/bryanaka/ember-data-factory-guy/blob/h/query-failing-test/tests/unit/shared-factory-guy-test-helper-tests.js#L461

**Comment by danielspaniel** [comment]
great just found it .. thanks

**Comment by danielspaniel** [comment]
Wow .. you found a really great bug .. don't know if I can fix it .. but it's pretty good one.  Working on it ..

**Comment by bryanaka** [comment]
Can you maybe provide some context to what the bug is? That way I can provide some context of what I have already worked through with our custom solution in our app

**Comment by danielspaniel** [comment]
Right .. it has something to do with params 
query1  {name: 'Dude'}
query2  {name: 'Dude', type: 'Small'} 

works ok if you do:

query1  {name: 'Dude'}
query2  {type: 'Small'}

not sure why the params have to be totally different yet .. trying to figure that out now

**Comment by danielspaniel** [comment]
Fixed .. will push out new version tomorrow when I am awake.

**Comment by danielspaniel** [comment]
Well .. I woke up all of the sudden, so v2.1.2 fixes that issue and thanks again for the nice test and the bringing of it up
