### ISSUE TITLE
Mocks: andSucceed/andFail everywhere

### ISSUE THREAD

**Issue by xcambar** [danielspaniel/ember-data-factory-guy#157]
Add `andSuccess` and `addFail` public methods to all mock classes so the user can test more use cases (500, 404...)

refs https://github.com/danielspaniel/ember-data-factory-guy/issues/156#issuecomment-162867001

**Comment by danielspaniel** [comment]
I am thinking of renaming to just succeeds()  and fails()  
 seems simpler and more along the lines of  with() and  returns()  methods proposed in the other items.

**Comment by xcambar** [comment]
Good idea.

BTW, I started working on this and it was kind of a rabbit hole, as, for example, `handleFind` returns an id and `handleQuery` returns an instance of `MockQueryRequest`.

Do you have an idea about how to make the transition smoother? I'd guess that returning a `MockRequest` (doesn't exist yet) systematically would help, but you may have another perspective.

And happy new year! :)

**Comment by danielspaniel** [comment]
Neato that you started on this. :) 

And good point there about handleFind.  One idea would be to move this id functionality from:

```js
var id = FactoryGuy.get('fixtureBuilder').extractId(modelName, json);

var url = this.buildURL(modelName, id);
new MockGetRequest(url, modelName, json);
return id;
```

to something like a property on MockGetRequest

```js
var mockRequest =  new MockGetRequest(url, modelName, json);
mockRequest.id = FactoryGuy.get('fixtureBuilder').extractId(modelName, json);
return mockRequest;
```

for handleReload would be similar, although redundant or not even necessary I suppose. 

.. I am open to anything else really.

And same here .. happy new year!

**Comment by danielspaniel** [comment]
are there things you're still stuck on. I am dedicating tomorrow to work on this and finish these issues, so let me know which you have not done, or which you want help on?

**Comment by danielspaniel** [comment]
@xcambar .. thanks for the amazing ideas that got me going on the huge refactor. I looked at your commits and used them as a base for my changes. 

you can now do this:
```js
  let mock = mockFind('user');
  let userId = mock.get('id');
```

I also added ability to inspect json with get method ( huge improvement ) 

thanks again!
