### ISSUE TITLE
customise response Headers as well as payloads

### ISSUE THREAD

**Issue by xcambar** [danielspaniel/ember-data-factory-guy#158]
refs https://github.com/danielspaniel/ember-data-factory-guy/issues/156#issuecomment-162867001

As discussed, rename `returns*` and `andReturn` method in mock classes to `returns`. The method takes an object literal and will allow to configure payloads (with keys `models`, `ids` and `json`) as well as headers (with key `headers`).

**Comment by danielspaniel** [comment]
Can now achieve this in version 2.3.0 with 
```javascript
   let mock = mockFindAll('user').returns({headers: {'X-Man': "Wolverine"}); 
   mock.returns({headers: {'X-Weapon': "Claws"}); 
```
