### ISSUE TITLE
Full control over handler

### ISSUE THREAD

**Issue by xcambar** [danielspaniel/ember-data-factory-guy#159]
refs https://github.com/danielspaniel/ember-data-factory-guy/issues/156#issuecomment-162867001

(Most) mock classes expose a `handler` method, but currently, this method is bound to `mockjax` during instanciation.

The call to this method should be wrapped in order to allow the developpers to have access to all the abilities of mockjax, in rare case when the exposed API of FactoryGuy is not enough.

**Comment by danielspaniel** [comment]
the handler is now available with version 2.3.0
when you get a mock with 
```js
   import { mockFind } from 'ember-data-factory-guy';
   let mock = mockFind('user');
   mock.handler //=> the handler function used by mockjax
```
