### ISSUE TITLE
handleCreate does not allow response to include nested associations

### ISSUE THREAD

**Issue by afn** [danielspaniel/ember-data-factory-guy#172]
In #141 you write:

> I actually remove any belongsTo associations in handleCreate Response .. because there were problems ( forgot what they were ) .. and it was redundant because if create a model with a belongsTo that exists in the store .. it will just 'be there' when the payload returns and makes the model for real 
so let me know if what I gave you does not work.

We have a use case where a model (call it `Post`) belongsTo another model (call it `User`), and the API that creates a `Post` also creates the corresponding `User`, so the response (with ActiveModelSerializer) looks like:

```json
{
  "post": {
    "user_id": 123
  },
  "users": [
    {"id": 123}
  ]
}
```

Because `handleCreate` removes all `belongsTo` associations (even if they're explicitly passed in), I can't write:

```javascript
handleCreate('post', {user: build('user')});
```

and instead have to use `mockjax` directly:

```javascript
  $.mockjax({
      url: url,
      dataType: 'json',
      type: 'post',
      responseText: build('post'), # the factory includes the belongsTo relationship, so this includes the user
      status: errorCode
  });
```

Could we revisit the decision to remove belongsTo associations in `handleCreate`?

**Comment by danielspaniel** [comment]
yes .. sure can .. if you can make a PR and rejigger things to work as you want .. I'd be happy to merge it.

**Comment by danielspaniel** [comment]
I think v2.6.2 fixed this issue .. let me know if there is any other problem! :)
