### ISSUE TITLE
makeList fails trying to read a number as a trait

### ISSUE THREAD

**Issue by visoft** [danielspaniel/ember-data-factory-guy#177]
I'm trying to test a component. I am using `manualSetup` inside my `beforeEach`

```
import { makeList , manualSetup }  from 'ember-data-factory-guy';
...
test('it renders the data for widgets', function(assert) {
  let widgets = makeList('widget', 2);
  assert.equal(widgets.length, 2);
  ...
})
```

When running the test, I get `Cannot read property '2' of undefined`.

I'm using the latest version 2.3.0 with Ember 2.4.1, Ember Data 2.4.0, and Ember CLI 2.4.1. It fails on line 75 of model-definition.js. `_jquery['default'].extend(traitsObj, traits[trait]);`, where `traits` is undefined and `trait` is the number 2. 

It works correctly if I use `makeList` like so: `makeList('widget', {name: 'Foo'}, {name: 'Bar'});` 

Is it something with the component test and `manualSetup`? It was working with the previous version of ember-data-factory-guy.

**Comment by danielspaniel** [comment]
Yes, I see that bug, will fix by tonight and release new patch.

**Comment by visoft** [comment]
Thanks :+1:

**Comment by danielspaniel** [comment]
Actually was easy, just fixed it. New version 2.3.1 is out, and has the fix. :)

**Comment by visoft** [comment]
You're awesome! Works great now.
