### ISSUE TITLE
Custom API format section of README is out of date

### ISSUE THREAD

**Issue by mdentremont** [danielspaniel/ember-data-factory-guy#195]
https://github.com/danielspaniel/ember-data-factory-guy#custom-api-formats

FactoryGuy isn't an `Ember.Object` anymore, so we can't do a `FactoryGuy.set`. I think the new style is just to `FactoryGuy.fixtureBuilder = `, but haven't finished fixing up a bunch of other issues to confirm yet.

**Comment by danielspaniel** [comment]
Right .. that section is out of date .. did you want to do something in particular .. or fix that up .. not sure?

**Comment by mdentremont** [comment]
@danielspaniel I'm not sure I'm the best candidate at this point lol, my environment is in a really bad state and I'm having a hard time figuring out what the correct way of doing it it 😛

**Comment by mdentremont** [comment]
Looks like this is the main reason why it isn't working anymore: https://github.com/danielspaniel/ember-data-factory-guy/commit/f4408a483c9a1b88af705389c034f09de3af9b97

**Comment by mdentremont** [comment]
The `fixtureBuilder` attribute has been commented out

**Comment by mdentremont** [comment]
@danielspaniel I can't for the live of me get 2.5.3 to work for our app.

We're using the ember-django-adapter, which uses a `{id: ..., field_x: ..., etc}` format for single items, and `{results: ]{id: ..., field_x: ..., etc}], next: <url>, previous: <url>}` for lists.

On 2.2.0 I was able to make most if not all of ember-data-factory-guy work by using the following (hack) code:

```javascript
import Ember from 'ember';

import FactoryGuy from 'ember-data-factory-guy';
import FactoryGuyTestHelper from 'ember-data-factory-guy/factory-guy-test-helper';
import FixtureBuilder from 'ember-data-factory-guy/fixture-builder';
import FixtureBuilderFactory from 'ember-data-factory-guy/fixture-builder-factory';
import MockGetRequest from 'ember-data-factory-guy/mock-get-request';

function convertCamelToSnake(model) {
  let clone = JSON.parse(JSON.stringify(model));
  Object.keys(clone).forEach(key => {
    let propertyValue = clone[key];
    delete clone[key];
    clone[Ember.String.decamelize(key)] = propertyValue;
  });
  return clone;
}

/**
 * Ugly, but allows us to "inherit" from FixtureBuilder so we don't need to duplicate a bunch of code
 */
function DjangoFixtureBuilder(store) {
  FixtureBuilder.call(this, store);

  /**
   * Convert the Ember format of models into the format that would be returned
   * from the API.
   */
  this.convertForBuild = (modelName, fixture) => {
    if (fixture instanceof Array) {
      let snakedFixture = fixture.map(convertCamelToSnake);

      return {
        results: snakedFixture,
        next: null,
        previous: null
      };
    }

    return convertCamelToSnake(fixture);
  };
}

FixtureBuilderFactory.reopen({
  fixtureBuilder: Ember.computed('store', {
    get() {
      return new DjangoFixtureBuilder(this.get('store'));
    }
  })
});
```

And I could achieve the new `.results({json|model}` functionality using custom TestHelper methods:
```javascript
FactoryGuyTestHelper.reopen({
  handleFindAllWithRecords(modelName, records) {
    let url = this.buildURL(modelName);

    let serializedRecords = records.map(record => record.serialize({includeId: true}));
    let json = FactoryGuy.getFixtureBuilder().convertForBuild(modelName, serializedRecords);

    this.stubEndpointForHttpRequest(url, json);
  },

  handleFindAllWithModels(modelName, models) {
    let url = this.buildURL(modelName);

    let serializedModels = JSON.stringify(models);
    let json = FactoryGuy.getFixtureBuilder().convertForBuild(modelName, serializedModels);

    this.stubEndpointForHttpRequest(url, json);
  },

  handleFindWithRecord(modelName, record) {
    let json = record.serialize({includeId: true});
    let id = json.data ? json.data.id : json.id;

    let url = this.buildURL(modelName, id);
    new MockGetRequest(url, modelName, json);
    return id;
  },

  handleFindWithRecords(modelName, records) {
    return records.map(record => this.handleFindWithRecord(modelName, record));
  },

  handleFindWithModel(modelName, model) {
    let json = JSON.stringify(model);

    let url = this.buildURL(modelName, model.id);
    new MockGetRequest(url, modelName, json);
    return model.id;
  }
}

export default FactoryGuyTestHelper;
```


Which isn't too much code in order to get things to work.

With the new version, I'm really having a hard time. Here are some issues I'm seeing:

- Stubbing in custom builder/converter/payload is as much of a hack as it was before
- Calling `makeList` on a model which has embedded properties doesn't actually populated the embedded pieces
- Calling `mockFind(<model_name>).returns({json: ...})` mocks the list endpoint as `this.responseJson.get` doesn't exist
- I'm really confused by the `{id: <id>, typeName: <type name>}` code being performed by `MockGetRequest`, which is essentially throwing away all of the model data that I passed in via `.returns({models: ....})`


I'm really sorry to bring this up as mostly a code dump, but I'm at the point of giving up on the new version, and any help would be incredibly helpful.

**Comment by danielspaniel** [comment]
hmm .. you know what might be really helpful @mdentremont .. if you could put together a sample project on github using jango adapter .. that I could then play around with and get something working .. might have to give me a server version too .. so one repo for some django server sending data and one for ember using django adapter 

  or just one with ember /django adapter ( but it's less great .. cause i want to see that django serialized data ) , .. since I am alittle unclear as to the format for the json still .. maybe give a real example for the find and findAll too. 
  
  For your issues , I sort of don't see the big picture yet, so I am having trouble understanding what is it that needs to be hacked ..

**Comment by mdentremont** [comment]
@danielspaniel that is a great idea. I'll try and whip it together soon

**Comment by danielspaniel** [comment]
great .. that will be super duper helpful. 
  
 One thing I notice so far is that the django rest adapter ( python ) .. has serializers, and with those you can customize the json payload to make it work with ember-data .. which would mean no hacking like you are doing ( 90% less ) .. 

 I also saw this: http://ngenworks.com/technology/making-ember-data-and-django-rest-framework-play-nice/  
  might have some good ideas. 

but overall ..as I said .. still not sure what is going on, so these are just shot in the dark suggestions

**Comment by danielspaniel** [comment]
how is this going @mdentremont ??  I'd be happy to help out if I can.

**Comment by mdentremont** [comment]
@danielspaniel Started on it tonight, should have something soon

**Comment by danielspaniel** [comment]
I am almost sure there is an easy answer to this one .. I hope you get some good inspiration then.

**Comment by mdentremont** [comment]
:)

**Comment by mdentremont** [comment]
3/4 done but I need to call it quits for the night.

https://github.com/mdentremont/django-api-rest-and-ember

I kind of merged two sample apps. To get it running:

- `pip install -r requirements.txt`
- `python manage.py migrate`
- `make create_database; make make_fixtures`
- `npm install && bower install`
- `python manage.py runserver &`
- `ember server`


This should give you a decent idea of what we're trying to do. You can checkout the Django responses at `http://localhost:8000/api/users`

**Comment by danielspaniel** [comment]
what version python? 3.x or 2.x ?

**Comment by danielspaniel** [comment]
ok .. got it all installed and working .. and I see the users json

**Comment by mdentremont** [comment]
Awesome!

**Comment by danielspaniel** [comment]
I noticed that the tests in ember-django-adapter 
https://github.com/dustinfarris/ember-django-adapter/blob/master/tests/acceptance/crud-success-test.js
covers the basic crud operations and looks all compatible with factory guy ( since the json is pure rest style ) 
 but maybe the problem is when data is returned as "results" as you are showing.  ( obviously .. that is a problem ) 
 Will be good to have a nice failing test in there ( so look forward to your adding more to this code base so we can get this straightened out )

**Comment by mdentremont** [comment]
@danielspaniel Yeah, one thing I noticed while setting up the sample app was it wasn't working due to the `{next: ...,previous: ...,results: ...,count: ...}` bit.

I added the https://github.com/hhff/ember-infinity addon last night which I thought dealt with the pagination format, but that was actually not need.

I have pushed a new commit to the sample app repo which removes the ember-infinity portion. I did a little digging into the ember-django-adapter docs and found this section on pagination which might be helpful: http://dustinfarris.com/ember-django-adapter/pagination/.

**Comment by danielspaniel** [comment]
I hear you .. and what you could do to make me feel better about things is to write some test that shows something breaking ... because then I can be more focused .. since I am not sure what you are needing to handle .. ( though I have a pretty darn good idea ) 
 though I think it is just that the FactoryGuy is not putting out json like the jango adapter .. right?
 but still .. if you can just write a few tests that fail .. then it's just more fun for me

**Comment by mdentremont** [comment]
For sure, on it now!

**Comment by mdentremont** [comment]
@danielspaniel Pushed up some changes, added one failing test so far.

**Comment by danielspaniel** [comment]
whoooray for failing tests!

**Comment by mdentremont** [comment]
More tests.. Looks like `FactoryGuy.hasMany` is leading to some issues

**Comment by mdentremont** [comment]
Looks like around these commits there was some functionality removed which allowed generating objects with embedded records:

- https://github.com/danielspaniel/ember-data-factory-guy/commit/28c9633ef801457133093e2a3ef7427e399ca860
- https://github.com/danielspaniel/ember-data-factory-guy/commit/aab907b3372a43bcc28d4d1f9d067876f505375c

**Comment by danielspaniel** [comment]
hmm .. could be .. those were some big changes .. but I don't remember removing tests .. ( except for those 2 ( commented out in 28c9633 ) ... errr .. umm .. well .. I guess if you have a failure .. I can just put it back?

**Comment by mdentremont** [comment]
@danielspaniel haha not sure. I could whip up a second page in my sample app which doesn't have embedded records, which would allow us to dig further into the issues I was seeing, without immediately needing any changes to support embedded records.

**Comment by danielspaniel** [comment]
yeah .. whew .. that is helpful .. for now .. to do one at a time

**Comment by mdentremont** [comment]
I've pushed up a few more tests

**Comment by danielspaniel** [comment]
great .. will look around later today

**Comment by danielspaniel** [comment]
I have looked at this ember django adapter and your setup and I am not sure how to actually go about doing this.  It looks like the django server sends data with no payload key .. then the ember-django-serializer ( which is REST type ) .. actually adds that payload key to the payload .. before passing it to be normalized .. into JSONAPI style
so .. 
  what I think might work is to use the new JSON Fixture converter that does not use a payload key and handles embedded records ( am working on this converter now ) .. 
  this will work for most things ( I think ) .. 
 but what it will NOT do is spit out those payloads with "results", "next" and "previous" in them. 
 
 You might have to tweek the JSONFixtureConverter a bit ( not sure ) .. but overall .. all you then will have to do is say override the current automatic assignment of the fixtureBuilder ( because since you are REST adapter/serializer based .. the default you get is a RESTFixtureBuilder ) 
  FactoryGuy.fixtureBuilder = JSONFixtureBuilder    and you should be 90% there .. if not I will pass the ball to you to see what you can do with it

**Comment by danielspaniel** [comment]
Shockingly .. everything seems to work with the new things I did .. so your in luck .. and so am I because I can say this is done.
 
You made some shockingly ridiculous errors in your repo ( see the post and posts ) route .. they are both wrong ( one should be the other both the route and the template were mixed up that way )  

and in the last test the expectedJson should be
```
  expectedJson = {
    title: 'title: 1',
    body: 'body: 1',
    id: 1,
  }

```

 But your repo basically did a great job of helping be get this working .. so thanks for all the effort

One thing that was really odd is that I could not navigate to the post/:post_id route at all ( ember shows the route exists ) .. but it will not go there ( so that test can not pass )  your using pods ( sort of ) .. maybe switch to not using them ? 

Other than that ( since I don't have rights to push the code back on that repo ) .. all you have to do is 

```
import FactoryGuy, { JSONFixtureBuilder } from 'ember-data-factory-guy';

module('try to show ember-data-factory-guy django incompatibilities', {
  beforeEach() {
    TestHelper.setup();
    this.application = startApp();
    FactoryGuy.fixtureBuilder = new JSONFixtureBuilder(FactoryGuy.store);
  },
  ....
});

that .. and your good to go .. with version 2.6.0 of factory-guy

**Comment by danielspaniel** [comment]
@mdentremont    did you get to check this new version out .. and fix your other fixes to get the tests passing?  
  Do you think I should make this easier for DRF users ( automatically use the JSONFixtureBuilder ?? 
 instead of having to manually set it up?

**Comment by mdentremont** [comment]
@danielspaniel I've been overhauling our real app over to the new version, seems to be going great so far.

I did find it a bit painful to switch over to JSONFixtureBuilder, as there isn't a nice way of doing it globally due to how FactoryGuy is instantiated on import. Automatic switch would be pretty amazing.

Overall things are going well, although there are two things I found a little painful:
- `mockCreate('model').returns(FactoryGuy.[make,build]('model'))` doesn't want to work
- `mockFind('model').returns(FactoryGuy.build('model'))` doesn't work as the URL which is generated for the mock does not include the item's ID (works with FactoryGuy.create though)

**Comment by danielspaniel** [comment]
Ok .. good point. I guess there is no reason not to make that automatically set for you ( I will do that today ) 

with the mockFind .. can you be more clear ( like show the exact exact real code you are using for that mockFind and for mockCreate )  and maybe the error your getting

**Comment by mdentremont** [comment]
```javascript
madeModel = FactoryGuy.made('modelX');
builtModel = FactoryGuy.build('modelX');
TestHelper.handleFind('modelX').returns({json: builtModel}).getUrl();  // 'modelX/'
TestHelper.handleFind('modelX').returns({model: madeModel}).getUrl();  // 'modelX/1'
```

**Comment by mdentremont** [comment]
@danielspaniel Just ran into another complication. `ember-infinity` relies on the `next` and `previous` pagination pieces from our server responses.

It seems that those are converted to `meta` which is part of the ember-data's JSONAPI spec (I'm not the most familiar with ember-data's internals).

I'm guessing this isn't a current use case supported by ember-data-factory-guy?

**Comment by danielspaniel** [comment]
those mockFind's should work .. they are fully tested .. so something your doing is different than I am testing ( can't see it from your snippets unfortuneately ) 

maybe you can push more code ( like these failture ) to that repo and then I can see the errors? 

and yes, that is one thing I am NOT doing ( the next, previous , results ) things .. and for that I would have to do meta data ( which I don't do right now in factory guy ) .. so you'd have to help out on that one or just wait till I get to it?  I would need a clear set of tests to see what I even need to do also ( cause I am not sure ) 

ember data supports meta stuff ( for REST serializers too I think ) and the ember-django-serializer takes the data from django and put's it in the meta hash .. ) this is the reason I think the guy uses REST serializer for the django-serializer ( I wrote to him ( dustin ferris ) for help on this issue .. ( no response ) )

 anyway .. I am not sure what it would take to make this happen

**Comment by mdentremont** [comment]
I made some changes to my sample repo undoing the pod structure and updating the tests.

I also added a test demonstrating where "meta" is needed.

**Comment by mdentremont** [comment]
I can get 90% of my tests passing if I just change `convert` in JSONFixtureConverter to return the `{results: ..., next, previous}` format, however this doesn't play well with `returns{models: ...}` for reasons I think you've already mentioned above.

**Comment by danielspaniel** [comment]
I pulled new code .. got all tests passing except for those 2 at the end.
 I will get to this on the weekend ( maybe sooner ) .. seems like special case that might be kinda weird, but if it fits with this serializer nicely then I will be surprised/ happy.

**Comment by danielspaniel** [comment]
interesting .. the django server sends a payload with "results"  and a "count" for any list .. did not reallize that till now .. that changes the game here .. I think I can hook that up

**Comment by danielspaniel** [comment]
I don't see that the pagination works at all in your test repo .. 
forgetting the tests .. 
 just hitting the users paginated route gets me ( all the results ) 

do you see it working  where you click to get more?

**Comment by mdentremont** [comment]
Check your network tab when visiting the "users-paginated" route, you
should see it make a bunch of requests.

**Comment by danielspaniel** [comment]
I do see that 
 but your page users-paginated then shows all results .. with no pagination

**Comment by danielspaniel** [comment]
also the data is not even correct: ( first result is root with no info ) 
 ```json
{"count":5,"next":null,"previous":null,"results":[{"id":1,"username":"root","first_name":"","last_name":"","posts":[{"id":1,"title":"Title #1","body":"This is a great post","multiword_field":"","author":1}]},{"id":2,"username":"bob","first_name":"Bob","last_name":"","posts":[{"id":2,"title":"Title #2","body":"Another thing I wanted to share","multiword_field":"","author":2}]},{"id":3,"username":"sally","first_name":"Sally","last_name":"","posts":[]},{"id":4,"username":"joe","first_name":"Joe","last_name":"","posts":[]},{"id":5,"username":"rachel","first_name":"Rachel","last_name":"","posts":[]}]}
```

**Comment by danielspaniel** [comment]
but if pagination is working fine for you .. I am all ears as to how you are doing it with this repo

**Comment by mdentremont** [comment]
Hmm. The pagination should be triggered automatically as you scroll near
the bottom of the page. I'm using ember-infinity for this. I will have to
take another peek, but in order to get the unit tests to make the second
fetch I had to set 'triggerOffset' in the template. Maybe remove that piece
and see if it acts a little better?

>

**Comment by mdentremont** [comment]
The pagination is similar to what Twitter does vs actually having
Next/Previous page buttons

**Comment by danielspaniel** [comment]
is this what you see?  I don't see that ..

**Comment by danielspaniel** [comment]
and once again .. I am not even looking at the tests .. let's just forget that right now.. and look at the regular http://localhost:4600/users-paginated  route .. there is no pagination going on there that I can see .. twitter style or otherwise

**Comment by mdentremont** [comment]
Omg lol. Forgot to mention that I changed the fixtures so make them create 200 users instead of like 2. Just run another `make all`

**Comment by danielspaniel** [comment]
Right .. NOW I got it .. I get the scrolling. 

how does the server do this:

"next":"http://localhost:8000/api/users/?page=4&page_size=2","previous":"http://localhost:8000/api/users/?page=2&page_size=2","results":[{"id":11,"username":"sally 9","first_name":"Sally","last_name":"","posts":[]},{"id":12,"username":"joe 10","first_name":"Joe","last_name":"","posts":[]},{"id":13,"username":"rachel 11","first_name":"Rachel","last_name":"","posts":[]},{"id":14,"username":"bob 12","first_name":"Bob","last_name":"","posts":[]},{"id":15,"username":"sally 13","first_name":"Sally","last_name":"","posts":[]}]}

with the "next" and "previous" links .. 
 
 is that built into django serializer??

**Comment by mdentremont** [comment]
Yeah, it's the `PageNumberPagination` class from http://www.django-rest-framework.org/api-guide/pagination/.

Essentially what happens is DjangoRestFramework magically performs the pagination for you by using LIMIT and OFFSET SQL behind the scenes based on the `page` and `page_size` params (it has its own configurable defaults as well for when they aren't passed).

**Comment by mdentremont** [comment]
It is configured in `example/settings.py` via:

```python
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,
}
```

**Comment by danielspaniel** [comment]
I think this is also leading to an issue that has been brewing in my mind for a while. 
 what if there is a way to:
```javascript 
let users1 =  build('user', 2).add({meta: {next: "/users/?page=2&page_size=2", previous: null}});
let users2 =  build('user', 2).add({meta: {next: "/users/?page=4&page_size=2"", previous: "/users?page_size=2"}} ;
mockFindAll( 'user' ).with({params: {page:1,page_size:2}).returns({json:users1});
mockFindAll( 'user' ).with({params: {page:2,page_size:2}).returns({json:users2});
```
that would then solve the infinity problem for all the adapters

**Comment by mdentremont** [comment]
Yup that's what I was thinking. It would also be nice if there was a way to add `next: null` and `previous: null` by default, as all of the server endpoints we use are paginated (and many of the Ember routes we use are making use of ember-infinity)

**Comment by danielspaniel** [comment]
I see ( about the django ) 
but what I don't get is how infinity uses your next and previous .. because that url style is not used by infinity

**Comment by danielspaniel** [comment]
by default I would not do because then everyone who not using infinity sees that .. so that would have eo be customized for your needs ..

**Comment by danielspaniel** [comment]
testing this of course by pretend scrolling is alittle bit over the top .. I think because ( I don't know ) .. just seems like it?

**Comment by mdentremont** [comment]
So it turns out `ember-infinity` needs some way of knowing if there will be more data (by default, it just knows to increment the page query param, so the URL in "next" is actually not used by ember-infinity).

If you check out my route code, that's actually where I am making use of the "next" metadata. We have that stuff extracted into a metaclass in our app which is why I got a little confused into thinking ember-infinity provided that functionality.

I do agree that the scrolling test bit is a bit over the top, however it is a crucial piece of our functionality so we kind of have to suck it up and write the painful test just to have that extra warm fuzzy feeling knowing the test is passing.

I've been overhauling hundreds of tests and I have most passing, so I'll try to make sure I get much better tests in my sample app to demonstrate any remaining issues I'm seeing.

The `add('meta', ...` functionality you mentioned definitely would be super helpful for some of our tests!

**Comment by danielspaniel** [comment]
ok .. I see .. so it just might work with the meta  next, previous  and the other thing I mentioned .. hmm .. seems promising .. I will see what I can do .. will take time because I have to test that myself in factory guy

**Comment by mdentremont** [comment]
@danielspaniel The issue I mentioned earlier about using `build()` results with `mockFind` turned out to be `buildList`, not `build`.

I pushed a test demonstrating the potentially issue.

**Comment by danielspaniel** [comment]
that I don't consider a bug .. because you should not be using that function ( it is for internal factory guy purposes only ) .. 

 if you visit a page you check the url with currentURL() 

 otherwise .. you don't need to check the url

**Comment by danielspaniel** [comment]
I used to have all the private methods hidden, 
 but I redid everything as classes and did not hide the private methods because it was pain in the ass and  it is not so easy.

**Comment by mdentremont** [comment]
@danielspaniel I'm using `getUrl()` to show that the URL is missing the ID. What ends up happening when trying to `mockFind` with a result from `buildList` is that the find doesn't end up being mocked, instead what gets mocked is the list endpoint (`/users` vs `/users/1`).

**Comment by danielspaniel** [comment]
yes, your right .. that was a genuine bug .. wow .. how did I miss that .. ?? guess I never thought someone would use mockFind and pass in one of buildLists items .. but that is pretty common thing .. so I am a bit shocked I missed that ..  thanks for finding :)

**Comment by danielspaniel** [comment]
Almost done with the new DRFFixtureBuilder for factory guy .. last few bug fixes and I can release it ( probably tonight or tomorrow )

**Comment by mdentremont** [comment]
Amazing! I finished fully migrating over from 2.2 to 2.6 yesterday, I think it was a productive experience (although long and painful due to all the crazyness we had going on)

**Comment by danielspaniel** [comment]
Awesome .. someone else did the same thing ( migrating all their hacks ) ( wrote me this morning ) and using newer JSONSerializer .. so your not alone. And in the end .. it's so worth it..

**Comment by danielspaniel** [comment]
v2.6.1 is now published ..  so grab that sucker and behold a whole new world of fun. 
you don't have to do anything . the FixtureBuilder is set for you 
only one test still not passing but it does not matter since the mockFind tests still work 

 the DRFAdapter adds a trailiing slash to url's .. pretty whacky ( see for yourself ) 
```javascript 
// file ember-django-adapter/addon/adapters/drf.js
export default DS.RESTAdapter.extend({
  defaultSerializer: "DS/djangoREST",
  addTrailingSlashes: true,
  nonFieldErrorsKey: 'non_field_errors',
```
which gets you: 
"http://localhost:99999/api/users/1/"  instead of  "http://localhost:99999/api/users/1" 

so ?? not big deal ... since you at least helped me fix the bug this pointed out 

 thanks for the help on this .. I would never have ever ever done this without your help. 
 the creator of ember-django-adapter has not even responded to my inquiries .. 
 so maybe he not interested  ..   ¯\_(ツ)_/¯
