### ISSUE TITLE
Model named "computed" is not found.

### ISSUE THREAD

**Issue by mattmcginnis** [danielspaniel/ember-data-factory-guy#197]
I have a model (fragment) named "computed" (unfortunately) and I'm getting the error:
```
No model was found for 'computed'
```
Could this be a naming issue similar an earlier problem when an attirbute was named "type" or is it more likely a model fragments issue?

**Comment by danielspaniel** [comment]
Can you try renaming that attr to something else to test that theory?

**Comment by mattmcginnis** [comment]
Renaming does work.  All of my other model fragment associations work as advertised.

**Comment by danielspaniel** [comment]
Can you send me the test and the model .. ie .. more detail pls.

**Comment by mattmcginnis** [comment]
Closing this because this error is something specific to my repo, yet to be determined.  This can be seen working correctly in my scratch repo here: https://github.com/mattmcginnis/ember-data-model-fragments-factory-guy.git
