### ISSUE TITLE
ActiveModel sideload or a mockQuery update/create variant

### ISSUE THREAD

**Issue by mreq** [danielspaniel/ember-data-factory-guy#205]
Is that possible? I need to mock a `PUT` with a response of the main model + sideloaded related models. Am using the ActiveModel adapter.

Example response

```
{
    "photo_collection": {
        "id": 19336,
        "photo_collection_item_ids": [
            378424,
            378428,
            378427,
            378426,
            378425
        ]
    },
    "photos": [
        {
            "id": 1770413
        },
        {
            "id": 1770412
        },
        {
            "id": 1770409
        },
        {
            "id": 1770411
        },
        {
            "id": 1770410
        }
    ],
    "photo_collection_items": [
        {
            "id": 378424,
            "photo_id": 1770413
        },
        {
            "id": 378428,
            "photo_id": 1770412
        },
        {
            "id": 378427,
            "photo_id": 1770409
        },
        {
            "id": 378426,
            "photo_id": 1770411
        },
        {
            "id": 378425,
            "photo_id": 1770410
        }
    ]
}
```

**Comment by danielspaniel** [comment]
You know .. that is a great question .. it is not possible now ( I am almost sure ) .. but it is something I think I can pull together .. if you feel like making a test case (  fun exercise  :) ) ..that would help me finish this one faster

**Comment by danielspaniel** [comment]
I think v2.6.2 fixed this issue .. that was a huge beast to tackle .. but it all worked out in the end.

**Comment by mreq** [comment]
That's great, thanks!

**Comment by danielspaniel** [comment]
You realize that photos in your example is not related to the other models?  right?
 I am 100% sure that the hasMany will work, but not sure about the photos ( an added sideload ).
 to mock this you would do 
```js
 let photoCollectionItems = build('photo-collection-item',3);
 mockCreate('photo-item').returns({ photoCollectionItems });
```
but I don't think doing the add for the photos will work .. 
 let me know if you need that and I will test it

**Comment by danielspaniel** [comment]
Actually .. I realized you mentioned PUT and not POST .. so you need this for mockUpdate also? 
 I can do that .. just let me know.

**Comment by mreq** [comment]
Yes, I was actually looking for PUT mocks. The UPDATE returns the sideloaded records as well using the default ActiveModel serializers.

**Comment by danielspaniel** [comment]
Oh .. ok .. good .. I will fix up that mockUpdate then ( it is the last remaining mock handler that has not been overhauled ) .. but should not take long since the mockCreate was much harder.

**Comment by danielspaniel** [comment]
v2.6.5 now allows mockUpdate.returns()  to pass in relationships as arguments which will cover your cases ( except the photos that is unrelated model .. ie not a relationship )
