### ISSUE TITLE
AMD/Require and use strict

### ISSUE THREAD

**Issue by davetheninja** [danielspaniel/ember-data-factory-guy#21]
Hey, 
I really am quite interested in using this library for dev/testing however in its current state I am unable to use it.

Issues:
1. I use 'use strict' within my build process which rejects undeclared (var) variables. var is not used  when defining classes within this library.
2. Unless I am missing something obvious, there is no support for AMD/Require JS

Question:
1. I am more than willing to fork, change and submit a patch to resolve the above - is this something you would be willing to accept into your library?  

If you are totally against strict and AMD then there is no point me spending time forking and patching.

Thanks

Davie

**Comment by davetheninja** [comment]
Apologies for being AWOL, family and work commitments.  I am actually getting time to do some of my own project coding again.

The new factory-guy is excellent btw.  Well done

**Comment by danielspaniel** [comment]
Thanks @davetheninja .. mucho appreciado and glad to see you back :)

**Comment by davetheninja** [comment]
:relieved:
