### ISSUE TITLE
Make vs build, debugging mockjax requests

### ISSUE THREAD

**Issue by brancusi** [danielspaniel/ember-data-factory-guy#210]
Hi,

When trying to `mockFindAll` records with associated models, I can't seem to use `make` or `makeList`. The resulting response from these don't seem to load the relationships even though I can inspect and see that there are relationships.

Example:

```js
const post = make('post', 'with_comments');
debugger;
```

If I inspect this, I can do:

```js
post.get('comments.firstObject.id');
```

and it shows `1`

But in the acceptance test, when using `mockFindAll('post')`, that post doesn't have any comments in the app.

If on the other hand I use:

```js
const post = build('post', 'with_comments')
mockFindAll('post').returns({json:post});
```

The comments are there.

The issue is I then can't get `mockUpdate` to work.

```js
mockUpdate('post', 1);
```

Results in a 404

Obviously I am doing something goofy since this is really basic stuff and no one else seems to be having these issues.

Wondering if there is a to debug mockjax to see what the response will be. Also, would it be possible to add an example acceptance test that includes these steps:

1. `buildList` of records
1. `mockQuery` those records
1. `mockUpdate` the first record

I think I would answer my own question once seeing a working version of those steps in a single test.

Thank you again for the great project

Just in case the actual code reveals something useful:

```js
test('can delete individual route visit', async function(assert) {
  const routePlan = make('route-plan');
  const routeVisits = buildList('route-visit', 2, {routePlan});

  mockFindAll('route-visit').returns({json:routeVisits});
  mockQuery('route-visit').returns({json:routeVisits});

  await page.visit();
  assert.equal(page.routePlans(0).routeVisits().count, 2);

  mockUpdate('route-visit', 1);

  await page.routePlans(0).routeVisits(0).delete();
  assert.equal(page.routePlans(0).routeVisits().count, 1);
});
```

Results with: `Error: Ember Data Request PUT /route-visits/1 returned a 404`

*Using mockUpdate even though it looks like I need a delete, removing is just updating the parent association, hence using mockUpdate*

**Comment by danielspaniel** [comment]
for the first issue ( mockFindAll not returning comments in the post )  => try this: 

mockFindAll('post', 2, 'with_comments');

**Comment by danielspaniel** [comment]
```js
test('can delete individual route visit', async function(assert) {
  const routePlan = make('route-plan');
  const routeVisits = buildList('route-visit', 2, {routePlan});

  // you don't mean to do these two right ?  is it a store.findAll or store.query ?
  mockFindAll('route-visit').returns({json:routeVisits});
  mockQuery('route-visit').returns({json:routeVisits});

  await page.visit();
  assert.equal(page.routePlans(0).routeVisits().count, 2);
  // can you add this and see if you have the route visits?
  console.log(FactoryGuy.store.peekAll('route-visit').mapBy('id') 
  mockUpdate('route-visit', 1);

 // You are doing a delete .. but when is the update happening ? 
  await page.routePlans(0).routeVisits(0).delete();
  assert.equal(page.routePlans(0).routeVisits().count, 1);
});
```

Bonus for using page objects 
and async await's .. have to tried that yet 

$.mockjaxSettings.logging = true;

**Comment by brancusi** [comment]
Screenshare would be excellent, my timezone at the moment is: 6pm - 8am PST.

Please let me know if anything in there works, otherwise I will be back on 8am-10pm pst in about 1 week.

Here is the updated test:

```js
test('can delete individual route visit', async function(assert) {
  const routePlan = make('route-plan');
  const routeVisits = buildList('route-visit', 2, {routePlan});

  mockQuery('route-visit').returns({json:routeVisits});

  await page.visit();
  assert.equal(page.routePlans(0).routeVisits().count, 2);
  
  console.log(FactoryGuy.store.peekAll('route-visit').mapBy('id'));

  mockUpdate('route-visit', 1);

  await page.routePlans(0).routeVisits(0).delete();
  assert.equal(page.routePlans(0).routeVisits().count, 1);
});
```

Result: `jquery.js:9175 PUT http://localhost:7357/route-visits/1 404 (Not Found)`

```js
console.log(FactoryGuy.store.peekAll('route-visit').mapBy('id'));
```

Results: `["1", "2"]`

As for the delete, under the hood when deleting a route visit from a route plan, we are really just removing the routePlan association from the routeVisit, so it's an update:

```js
routeVisit.set('routePlan', null)
routeVisit.save();
```

Since we never delete them, only move them to open status.

On a side note, does the host matter? For testing I am setting the host to: `''` in the application adapter.

**Comment by danielspaniel** [comment]
are you using 2.6.7 of factory guy?

**Comment by brancusi** [comment]
Yes

**Comment by brancusi** [comment]
Trying to inspect the handler like so:

```js
test('can delete individual route visit', async function(assert) {
  const routePlan = make('route-plan');
  const routeVisits = buildList('route-visit', 2, {routePlan});

  mockQuery('route-visit').returns({json:routeVisits});

  console.log($.mockjax.unfiredHandlers());

  await page.visit();
  assert.equal(page.routePlans(0).routeVisits().count, 2);

  mockUpdate('route-visit', 1);

  console.log($.mockjax.unfiredHandlers());

  await page.routePlans(0).routeVisits(0).delete();
  assert.equal(page.routePlans(0).routeVisits().count, 1);
});
```

Upon inspecting the mockUpdate handler, I noticed the `[[BoundThis]]` is: `_default`

Where the other handler shows: `MockQueryRequest ` for `[[BoundThis]]`

Is there a way to see matching rules in mockjax? I enabled logging along with setting it to level 4 but I'm not seeing any logging.

**Comment by danielspaniel** [comment]
you can also try 
 
let mock = mockUpdate('route-visit', 1);
console.log(mock.getUrl());

and it is odd that mockjax is not logging .. if it is working it will out put every request it sees ( even if it does not mock it.

**Comment by danielspaniel** [comment]
it's too late for me to do a screenshare .. i am pooped ( EST time 10PM )

**Comment by brancusi** [comment]
Ok I think I know what is going on. 

First off, got logging to work by adding:

```js
$.mockjaxSettings.logging = true;
$.mockjaxSettings.logging = 4;
```

after the call to `mockSetup();` in the `module-for-acceptance` helper.

Without the logging level nothing outputs and if placed before the `mockSetup` I'm assuming it get set to false in `mockSetup`

Issue I see now after inspecting the handler:

`mock.getType()`, is of type `PATCH`

but the request being made is a `PUT`

Any ideas for the mismatch?

**Comment by brancusi** [comment]
Upgrading to `ember-data 2.7.0` fixes the issue.

**Comment by danielspaniel** [comment]
Is there any way you can make that repo  public so I can look at it ?  I would like to see what is going on ( back when it was ember data ( before 2.7 ) and then see what changed

**Comment by brancusi** [comment]
Sure here is the repo: https://github.com/brancusi/last-strawberry

Checkout: https://github.com/brancusi/last-strawberry/blob/master/tests/acceptance/distribution-test.js
And the route: https://github.com/brancusi/last-strawberry/blob/master/app/routes/distribution.js

**Comment by danielspaniel** [comment]
I just checked and you don't have the serializers/application.js file
if you put that in there and set it to JSONAPISerializer  then I think things will work fine ( even on ember-data 2.6 )  .. seems like if you declare an adapter ( like you did in adapters/application.js  .. you have to declare a serializer for the application too  or else it defaults to something not JSONAPI ( which is odd ) 

 I actually had the same problem in my own demo repo the other day .. but I will clone this repo ( thanks for sharing ) and check out my theory

**Comment by danielspaniel** [comment]
Strange, I got the repo. Changed ember-data and ember to 2.6.0, ran the tests, and that test passed. Mmmm .. not sure what to say? except your code is pretty good. I am kinda impressed. 

anyway .. just a few suggestions:

```js
FactoryGuy.define('route-plan-blueprint', {
  default: {
    name: FactoryGuy.generate(num => `Route Plan Blueprint - ${num}`),
    routePlanBlueprintSlots: FactoryGuy.hasMany('route-plan-blueprint-slot')
  }
});
```
You don't have to use FactoryGuy.generate in this case to get the next number,
 since the fixture id has always the id ( which is the next number )  so, a shortcut 
is to do and inline function that is always passed the fixture ( where you grab id ) 
And with FactoryGuy.hasMany('blah') you have to pass a number if you want to say 
 how many of them. If you wanted 0 then that is fine too ( so keep as you have it ) 

```js
FactoryGuy.define('route-plan-blueprint', {
  default: {
    name: (f)=> `Route Plan Blueprint - ${f.id}`,
    routePlanBlueprintSlots: FactoryGuy.hasMany('route-plan-blueprint-slot', 2)
  }
});
```

I am going to close this issue,because I can't recreate the problem and because you sort fixed it? Let me know if you have anything else going on .. and keep up the good work. This all looks well done.

**Comment by brancusi** [comment]
Thank you @danielspaniel that's really great to hear.

I will keep playing with it and report if I find anything more concrete.

Thanks again!
