### ISSUE TITLE
match() fails with JSONAPI for relationship when serializer's payloadKeyFromModelName() doesn't pluralize

### ISSUE THREAD

**Issue by cristinawithout** [danielspaniel/ember-data-factory-guy#213]
Our application serializer has the following method that purposely does not pluralize.

`payloadKeyFromModelName(modelName) { return Ember.String.underscore(modelName); }`

mock-create-request.js is [setting serializeMode to true ](https://github.com/danielspaniel/ember-data-factory-guy/blob/v2.7.0-beta.7/addon/mocks/mock-create-request.js#L67) and jsonapi-fixture-converter.js [uses that to pluralize the type](https://github.com/danielspaniel/ember-data-factory-guy/blob/v2.7.0-beta.7/addon/converter/jsonapi-fixture-converter.js#L15).

So when I try to use mockCreate().match() with a relationship, the type key is getting pluralized in the expected data and the match fails because our serializer does not pluralize the type key.

Example:
`mockCreate('entry-type').match({name: 'My Name', handle: 'my_name', section: {id: '1', type: 'section'}})`

And when it reaches [this comparison](https://github.com/danielspaniel/ember-data-factory-guy/blob/v2.7.0-beta.7/addon/mocks/mock-create-request.js#L74), the data is:

expectedData.data:
```
{
attributes: {
	handle: "my_name",
	name: "My Name"
},
relationships: {
	section: {
		data: {
			id: "1",
			type: "sections" // pluralized
		}
	}
},
type: "entry-types" // pluralized
}
```

requestData.data:

```
{
attributes: {
	handle: "my_name",
	name: "My Name"
},
relationships: {
	section: {
		data: {
			id: "1",
			type: "section" // not pluralized
		}
	}
},
type: "entry-type" // not pluralized
}
```

So the match fails, but the requestData is exactly as it should be using our serializer.

Is it possible to instead lookup serializers by modelName and use payloadKeyFromModelName() as the JSONAPI serializer does when serializing the type?

**Comment by danielspaniel** [comment]
@cristinawithout .. good point here. 
 Do you think you could put together a PR that would handle this ?? 
 and put a nice test together ( which would be pretty similar to what you have above ) ??

**Comment by danielspaniel** [comment]
v2.7.0-beta.8 has your changes
