### ISSUE TITLE
.match() for mockUpdate()

### ISSUE THREAD

**Issue by cristinawithout** [danielspaniel/ember-data-factory-guy#216]
I don't see a way to verify the data sent to my endpoint on update is correct as I can with mockCreate().match()

**Comment by danielspaniel** [comment]
err .. um .. well .. let's see, I am digging through my thoughts for this one, and the answer is?
 no found 
oh well .. 
 not sure why I never did that .. is that something nice to have .. 
 I just never thought of it 
 since I usually set stuff and update it and only care about returning extra attrs but never checking that the attrs I am sending are this way or that 
 
 but you know, it's not a bad idea 

 might be easy to do 
  
 you want to take a shot at it?
 maybe give me example of what you want to do so I can be 100% certain I don't mess it up.

**Comment by cristinawithout** [comment]
I'll see if I can make a PR with at least some tests.

**Comment by danielspaniel** [comment]
v2.7.0-beta.10 has this ability

**Comment by danielspaniel** [comment]
@cristinawithout =>  side note. I thought this was a pretty silly feature at first, and lo and behold as soon as I finished it, I used it right away 👍 

seems to happen every time I get a feature request. I kind of think ( who would ever need that ). Then it ends up being me using it pretty much the next day.

**Comment by cristinawithout** [comment]
👍  Nice. I'm using it along with mockJack's throwUnmocked:true in acceptance tests to make sure A. all the form inputs are hooked up to the buffered model (our own implementation similar to buffered proxy - but handles relationships) B. the values in the buffered model transfer to the model on save  C. The values are serializing as expected.

Using match(), I can make sure all of those things are working. Without it, the update would return success, and the test would pass even if the the model wasn't connected to the inputs and/or the serializer was returning nothing.

An update acceptance test where I'm using it is basically like this:

```
test('can update entry type', function(assert) {
    mockFindAll('section', 5);
    mockFindAll('entry-type', [{
        id: '100',
        name: 'My Entry Type',
        handle: 'my_entry_type',
        section: {
            id: '5',
            type: 'section',
        }
    }]);
    let mock = mockUpdate('entry-type', 100)
        .match({
            name: 'New Name',
            handle: 'new_name',
            section: {id: '1', type: 'section'}
        });

    visit('/entry-types/100/update');

    // Edit the name, handle and section relationship.
    fillIn('[data-test=et-name] input', 'New Name');
    fillIn('[data-test=et-handle] input', 'new_name');
    click('[data-test=et-section] .chosen-container'); // (uses Chosen plugin)
    click('[data-test=et-section] .chosen-container .chosen-results li:eq(0)');

    // Submit form
    click('button[type=submit]');

    andThen(function() {
        // Check for errors rendered when the response fails. 
       // If values don't match, it'll come back with an error because throwUnmocked is true.
        assert.equal(find('.alert-danger').length, 0, 'Should not have error alert');
         // Make sure the mock was called.
        assert.equal(mock.timesCalled, 1);
    });
});
```

**Comment by mdentremont** [comment]
@danielspaniel Does this work for `mockCreate` as well, or just `mockUpdate` (+ `mockFind`, etc)?

**Comment by danielspaniel** [comment]
@mdentremont:  only mockUpdate and mockCreate   has the concept of match attributes. 
  Don't think it would be possible with mockFind or the GET calls because there are no attributes being passed. Only parameters ( if any ) ..

**Comment by mdentremont** [comment]
@danielspaniel Sorry, I was referring to the `timesCalled` - I thought when it is was first introduced it wasn't available via `mockCreate`

**Comment by danielspaniel** [comment]
Oops .. yes, timesCalled is available to all the mocks .. and your right .. it was not available to mockCreate until I refactored it to use the same base class at all requests

**Comment by mdentremont** [comment]
@danielspaniel Awesome, that is great news!
