### ISSUE TITLE
[FEATURE REQUEST] Add support for serializer renamed fields (ie: `attrs: { localKey: 'serverKey'}`)

### ISSUE THREAD

**Issue by mdentremont** [danielspaniel/ember-data-factory-guy#219]
Ember-data supports custom field mappings through a serializer's "attrs".

ex:
```javascript
# models/label.js
export default DS.Model.extend({
  title: DS.attr('string')
});

# serializers/label.js
export default DRFSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    title: 'name',      // OR: title: {key: 'name'}
  }
});
```

This allows us to use a different name in our ember app than the API.

Ember-data-factory-guy does not check for these attrs when generating JSON, so ember-data ends up getting confused about the data format.

**Comment by danielspaniel** [comment]
errr ... well .. yes, that is good point.  do you feel like setting up some failing tests for me and I can fix ..  and just to understand .. you are using 'title' as the ember model attribute, but the data for that title is in the attribute 'name' in the payload ( is what your serializer is saying )   

    On Monday, July 11, 2016 9:26 PM, mdentremont <notifications@github.com> wrote:
 

 Ember-data supports custom field mappings through a serializer's "attrs".ex:# models/label.js
export default DS.Model.extend({
  title: DS.attr('string')
});

# serializers/label.js
export default DRFSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    title: 'name',      // OR: title: {key: 'name'}
  }
});This allows us to use a different name in our ember app than the API.Ember-data-factory-guy does not check for these attrs when generating JSON, so ember-data ends up getting confused about the data format.—

**Comment by mdentremont** [comment]
That is correct -- I'll look into creating some tests at some point -- I actually had it mostly implemented but somehow lost it (was directly modifying my node_modules folder :P)

**Comment by danielspaniel** [comment]
That is funny .. I do that too .. modify code from addon right in node_modules. ok .. if you don't get to it .. I can get that next week 

    On Monday, July 11, 2016 9:42 PM, mdentremont <notifications@github.com> wrote:
 

 That is correct -- I'll look into creating some tests at some point -- I actually had it mostly implemented but somehow lost it (was directly modifying my node_modules folder :P)—

**Comment by mdentremont** [comment]
@danielspaniel I edited my previous comment and added a code snipper with the changes I was using

**Comment by danielspaniel** [comment]
this worked ?? wow .. cause that is transformRelationshipKey 
and you were mentioning attribute keys .. is it same idea though?

**Comment by danielspaniel** [comment]
but I think I can set up some tests pretty swiftly to check this out .. and see where should go where and if I can reuse what you have

**Comment by danielspaniel** [comment]
what does:

```js
 let relationshipKey = serializer._getMappedKey(relationship.key, modelClass);
```
 
 I don't see that _getMappedKey function anywhere

**Comment by danielspaniel** [comment]
I think I fixed this. Will release new version tomorrow and you can try it out

**Comment by danielspaniel** [comment]
v2.7.0 implements the fix for this issue

**Comment by mdentremont** [comment]
@danielspaniel You are super quick man :)

**Comment by danielspaniel** [comment]
Thanks @mdentremont  .. I just got a good idea and all of the sudden I was done. :)

**Comment by mdentremont** [comment]
I'll reward your efforts with yet another obscure edge case 😛  https://github.com/danielspaniel/ember-data-factory-guy/issues/220
