### ISSUE TITLE
A typo in scenario.js

### ISSUE THREAD

**Issue by youroff** [danielspaniel/ember-data-factory-guy#222]
There must be a typo in `mockReload` string:
https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/scenario.js#L5

**Comment by danielspaniel** [comment]
wow .. that is pretty funny and strange because I can still use mockReload ( I thought? ) in scenario .. but obviously wrong ..  fixing asap, and adding test for that

**Comment by youroff** [comment]
Can't say if it's working or not, just ran into it while looking over the code :)

**Comment by danielspaniel** [comment]
v2.7.3 fixes this typo
