### ISSUE TITLE
How to mock requests to custom endpoints in integration test

### ISSUE THREAD

**Issue by brancusi** [danielspaniel/ember-data-factory-guy#230]
Hi,

Here is the use case:

Trying to test a component that uses the google place autocomplete.

I need to mock the auth and query requests.

For some reason, in the integration test, `mockJax` does not seem to match any requests when a handler is created directly through the mockJax global.

We've tried using $.mockJax and Ember.$.mockJax.

Neither intercept any of the requests.

Any ideas?

Thanks

**Comment by danielspaniel** [comment]
maybe simple as this:

```js
    let widget = this.build('widget', 'withExtras').get();
    Ember.$.mockjax({ url: `/my/custom/widget`, responseText: widget, type: 'GET' });
```
 as in ( lowercase the mockjax )

**Comment by danielspaniel** [comment]
did this work for you?

**Comment by brancusi** [comment]
Thank you. I haven't had a chance to try it yet since we skipped that test for now. Will close and keep you posted once I try it out.

Thanks again
