### ISSUE TITLE
Bizarre issue with make and makeList

### ISSUE THREAD

**Issue by ayuk23** [danielspaniel/ember-data-factory-guy#232]
I'm getting some very bizarre data in my factories. My code is the following:
```js
	var tmp1 = make('example');
	console.log(tmp1.get('category_id'));


	var tmp2 = make('example');
	console.log(tmp1.get('category_id'));
	console.log(tmp2.get('category_id'));


	var tmp3 = make('example');

	console.log(tmp1.get('category_id'));
	console.log(tmp2.get('category_id'));
	console.log(tmp3.get('category_id'));
```

and outputs "1 2 2 3 3 3"

My factory is the following:
```js
import FactoryGuy from 'ember-data-factory-guy';

FactoryGuy.define('example', {
	sequences: {
		genericSequence: function(num) {
			return num.toString();
		}
	},

	default: {
		category_id: FactoryGuy.generate('genericSequence'),
  		category_name: "test"
	}
});
```

The behavior is the same if I use `makeList('example', 5)` with the category_id of each being 5. I have no idea what could be causing this. Any help would be appreciated.

**Comment by danielspaniel** [comment]
I tried to recreate this problem with what you told me here, but could not do it. Everything works perfectly for me. 
 If you can make a test that fails then maybe I can see what you are doing wrong. 
 I need to see more of what you are doing in the model ( example ) 
 Or if you can share this repo with me I could look it over.

**Comment by ayuk23** [comment]
@danielspaniel
Just figured it out.

In the serializer for my class, I had
`primaryKey: 'differentField'`

Any way of using sequences but still keeping my primary Key?

**Comment by danielspaniel** [comment]
Glad you figured it out, but I still don't understand what was causing problem. 
 I would have to see the model and serializer to understand what you just said above. 
 
  I am sure there is a way to use sequences, but I have to understand the problem first.

**Comment by ayuk23** [comment]
@danielspaniel 
So I did not provide you with all of my factory, but essentially the issue was that I was setting a default value for my primary key. My serializer was like this:
```
export default DS.JSONSerializer.extend({
  primaryKey: 'sample_id'
});
```
but my factory's default included this line: `sample_id: "default_id"` which mean that every object I created shared the same id... which led to some unusual, but not unexpected behavior.

Thanks for your help!

**Comment by danielspaniel** [comment]
right .. ok .. NOW I get it .. thanks for clearing that up .. I will close this issue, but feel free to ask me any questions and/ or have me look over your code to help setup the tests with factory guy .. there are alot of little things that make it really rocking when you know what to do.
