### ISSUE TITLE
Build strategies for related data

### ISSUE THREAD

**Issue by brancusi** [danielspaniel/ember-data-factory-guy#234]
Hi,

Wondering if anyone has a suggestion on how to make this more reusable, and if possible how to setup the factories to do this type of data building.

### Example:
1. `Company -> hasMany('location')`
1. `Location -> hasMany('employee') and belongsTo('company')`
1. `Employee -> hasMany('work-shift') and belongsTo('location')`
1. `WorkShift -> belongsTo('employee')`

### Route:
When hitting: `/workshifts` the model hook makes a request for: `workshifts` and sideload all the related data.

### Goal:
Would like to be able to call: `mockFindAll('work-shift', 5)` and it would not only create the workshifts but the related data all the way up the chain to `company`.

### Current solution 
To get the above to work, we use the following:

```js
const company = make('company'),
      location = make('location', {company})
      employee1 = make('employee', {location}),
      employee2 = make('employee', {location}),
      workShifts = buildList('work-shift', 
        {employee:employee1, location}, 
        {employee:employee2, location});

mockFindAll("work-shift").returns({json: workShifts});
```

Just want to make sure we are not missing out on a better approach.

**Comment by danielspaniel** [comment]
Depends on if you care about what company or location is being used ( and if they are the same ones ). 

Let's say you do this in location factory:

```js
FactoryGuy.define('location', {
  default: {
    company: FactoryGuy.belongsTo('company')
  }
});
```

You then don't have to make a company model for location, but if you do this the companies for each location will be different. 

Usually I do just what you are doing, when I need to have fine grained control off all the associations.

**Comment by brancusi** [comment]
Thank you! Glad to see we are on the right track.
