### ISSUE TITLE
FactoryGuy.define devours the supplied config object

### ISSUE THREAD

**Issue by ryedeer** [danielspaniel/ember-data-factory-guy#235]
Here's the problem I ran into when I was defining factories for a set of similar models. To avoid repeating the whole config, I assigned it to a variable. However, I found that the data disappear from the config object after the first call to `FactoryGuy.define`:

```javascript
var config = {
  default: {
    color: 'yellow',
    shape: 'spherical'
  }
};

FactoryGuy.define('apple', config); // works just fine
FactoryGuy.define('lemon', config); // the config is empty!
```

As I can see from your code, it happens due to the specifics of the implementation. To overcome this, I currently use `Ember.copy(config)`, but this behaviour was somewhat unexpected. Wouldn't in be better to spare the supplied object?

**Comment by danielspaniel** [comment]
Yes, it would be better. I will update the code to make a copy ( of config ) before I destroy it.

**Comment by danielspaniel** [comment]
fixed in v2.7.5

**Comment by ryedeer** [comment]
Thank you very much for fixing it! Now I can safely remove `Ember.copy` from my factory definitions :)

**Comment by danielspaniel** [comment]
You're welcome.  That was a good idea .. 👍  to copy the config anyway .. so glad that is in there now.
