### ISSUE TITLE
Field called type raises error

### ISSUE THREAD

**Issue by trevorrjohn** [danielspaniel/ember-data-factory-guy#237]
Hi I have a model that has a type column like:

```javascript
//user.js
DS.Model.extend({
  type: DS.attr('string') // ie. free, paid, admin
});
```

When I create a factory like so:

```javascript
const user = make('user', { type: 'free' });
```

I get an error that says: 

```javascript
"Assertion Failed: You tried to push data with a type 'free' but no model could be found with that name."
```

It looks like `FixtureBuilder` changes the `modelName` from `user` to `free` then when it gets pushed into the store it is breaking. Are there any workarounds for this?

**Comment by trevorrjohn** [comment]
I see this comment:

https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/converter/fixture-converter.js#L19-L21

Not sure what the workaround is yet though?

**Comment by danielspaniel** [comment]
does this help give you a clue?:

https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.7.5

**Comment by trevorrjohn** [comment]
yes it does...
