### ISSUE TITLE
Mocking a singularized endpoint

### ISSUE THREAD

**Issue by edprats** [danielspaniel/ember-data-factory-guy#241]
in my application i have a 'user' model, and sometimes i want to `findRecord('user', 'me')`, which in my user adapter translates to the endpoint `GET /user` (singular, for retrieving the authenticated user from my API)

how could i use an http GET mock (mockFind?) to use that in development (hit up singular 'user' as opposed to 'users')?

**Comment by danielspaniel** [comment]
To deal with this ( till I change to pull in urlForFindRecord ) and you ( actually use urlForFindRecord ) on the adapter you can:

1.  build a user payload and use mockjax directly
```js
let user = build('user');
$.mockjax({url: `/user/me`, responseText: user); 
```
or
2.  use factory guy cache only mode and make a user 
```js
FactoryGuy.cacheOnlyMode();
make('user');
```

cacheOnlyMode works by saying .. hey .. don't bother to look for a findRecord model or findAll if you have something in the store already.

**Comment by edprats** [comment]
thank you, that worked perfectly

**Comment by danielspaniel** [comment]
fixed: => https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.7.6
