### ISSUE TITLE
Having a property called "type" on your model causes `make` to fail

### ISSUE THREAD

**Issue by patocallaghan** [danielspaniel/ember-data-factory-guy#242]
If your model has a property on it called `type` it will cause `make` to fail (and presumably `build` too). Doing a `git bisect` it looks like this was introduced with this commit https://github.com/danielspaniel/ember-data-factory-guy/commit/b015ef25dca5f03a77b147780fce1c651cd14872 specifically with this line here https://github.com/danielspaniel/ember-data-factory-guy/commit/b015ef25dca5f03a77b147780fce1c651cd14872#diff-5f1855cb8ac1827c7ef28bcaacf20a4bR85

```
type: this.typeTransformFn(fixture.type || modelName),
```

I've added a [failing test here](https://github.com/danielspaniel/ember-data-factory-guy/pull/243) to replicate it, adding a `type` property to the `employee` model.

![image](https://cloud.githubusercontent.com/assets/685034/18307665/3e7079be-74e9-11e6-9c99-75c290e3143a.png)

**Comment by danielspaniel** [comment]
I just put the solution for this in the docs last night. 
 Check it out:
https://github.com/danielspaniel/ember-data-factory-guy#defining-factories

**Comment by patocallaghan** [comment]
Oh, sorry I missed that. I'll close this then.

**Comment by danielspaniel** [comment]
Oh well, yeah .. was kinda tricky to find that one.
