### ISSUE TITLE
Manually adding model fragment causing error

### ISSUE THREAD

**Issue by patocallaghan** [danielspaniel/ember-data-factory-guy#244]
Say we have the `employee` model set up like so:

```
export default Model.extend({
  designation: fragment('name'),
  ....
});

```

where the `designation` property is named differently than the fragment it's associated with, `name`.

When manually trying to insert the `name` fragment into the `employee` like so:

```
let employee = make('employee', {
  designation: build('name').get()
});
```

it fails with the below error:

![image](https://cloud.githubusercontent.com/assets/685034/18330940/79ae6df0-7553-11e6-9c0e-5fc55cc15828.png)

It's expecting the property to be named the same as the fragment. I've tracked this down to the following line https://github.com/danielspaniel/ember-data-factory-guy/blob/3a5e3e84b451ebd9bf4adef75e5bf72175a1b26c/addon/factory-guy.js#L271 in `buildRaw` where when appending the fragment to the `employee` it has the `args.name` "designation".

```
let definition = lookupDefinitionForFixtureName(args.name)
```

~~I have a failing test too which I'll link soon~~ Failing Test: https://github.com/danielspaniel/ember-data-factory-guy/pull/245

**Comment by danielspaniel** [comment]
Does this look like easy fix? I'm scared 😱

**Comment by danielspaniel** [comment]
fixed with: https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.7.7

**Comment by patocallaghan** [comment]
Ha, no probs....thanks for the fix! 🙌
