### ISSUE TITLE
mockFind with RESTAdaptor clobbers type attribute on model

### ISSUE THREAD

**Issue by patocallaghan** [danielspaniel/ember-data-factory-guy#248]
Found a crazy "Perfect Storm"-esque issue 🙈 

Basically you need the following criteria to reproduce:

* Have a `type` attribute on a non-polymorphic model/factory
* Be using the `DS.RESTAdapter`
* Use `mockFind` in either of the following 3 ways:

```
let employee = make('employee');
#1 - mockFind(employee);
#2 - mockFind('employee').returns({model: employee});
#3 - mockFind('employee').returns({id: employee.id});
```

The model returned by the `findRecord` has its `type` attribute clobbered by the `type` describing the model. So for example if my factory has a `type: 'contractor'`, it actually gets clobbered to be `type: 'employee'`. 

I think the reason why this is happening is because the `payload` in the `var record = store.push(payload);` in Ember Data's `_find` method contains `type: 'employee'` in the `attributes`. But it probably shouldn't when using the RESTAdaptor?. They payload looks like `{"data":{"id":"1","type":"employee","attributes":{"type":"employee"},"relationships":{}}}`.

On the other hand, If you do

```
let employee = build('employee');
mockFind('employee').returns({json: employee});
```

it works as expected.

I have a failing test which I'll link up in a separate PR.

I've currently only tested this for `mockFind` and not the other mock helpers.

**Comment by danielspaniel** [comment]
Does this help?
https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.7.5

There is also a blurb here:
https://github.com/danielspaniel/ember-data-factory-guy#defining-factories

about the ```polymorphic: false```  flag

granted it is new thing, and there was little of the usual fanfare surrounding it's release

**Comment by danielspaniel** [comment]
eww .. looks you are using that  polymorphic: false  flag

**Comment by danielspaniel** [comment]
do all those 4 tests you added to employee-view-test.js fail?

**Comment by patocallaghan** [comment]
yeah, I'd tried that already unfortunately 😞 

It works fine when using `mockFind` with `returns({json: ...})` but not when using model or id

**Comment by patocallaghan** [comment]
3 fail and 1 passes.

**Comment by danielspaniel** [comment]
ok .. good to know .. will dig up some dirt .. find some suspects .. see what I can do

**Comment by patocallaghan** [comment]
Thanks man! appreciate it!

**Comment by danielspaniel** [comment]
wow .. that was nuts ( hard to find the issue )  .. another great find, as usual. My testing was sloppy on this one. But not anymore. 
Fixed in https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.7.8

**Comment by patocallaghan** [comment]
Awesome, thanks very much! Will give that a go. I really appreciate the effort 🙇

**Comment by danielspaniel** [comment]
Your super welcome Pat, and thanks for being so appreciative. Helps keeps the elves singing and happy at night.
