### ISSUE TITLE
Deprecation warnings on Ember 2.8

### ISSUE THREAD

**Issue by mdentremont** [danielspaniel/ember-data-factory-guy#250]
It looks like Django 1.10 has introduced an `includes` method to the array class, and deprecated the `contains` method.

There are a couple usages of `contains` in the test helpers which are leading to some deprecation warnings on the new version.

**Comment by danielspaniel** [comment]
I will fix that today .. thanks for letting me know ( it is also deprecated in ember 2.8 )

**Comment by mdentremont** [comment]
@danielspaniel Haha my bad - too much context switching :P

**Comment by mdentremont** [comment]
@danielspaniel Feel free to use https://github.com/danielspaniel/ember-data-factory-guy/pull/251
 if you're happy with it

**Comment by danielspaniel** [comment]
Appreciate the pull request .. I put comment there about just replacing contains to includes with no conditional logic

**Comment by mdentremont** [comment]
Thanks @danielspaniel !

**Comment by danielspaniel** [comment]
https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.7.10
