### ISSUE TITLE
Using different adapter/serializer for different models may cause an issue if different from application adapter/serilizer

### ISSUE THREAD

**Issue by iraspopo** [danielspaniel/ember-data-factory-guy#256]
This issue was also described in following PR that was recently closed/deleted: https://github.com/danielspaniel/ember-data-factory-guy/pull/149

More info: 
Our application adapter is REST and we don not have application serializer defined but all models have one and it is JSONAPI. However factory-guy assumes if there is no application serializer it will assign serializer that matches adapter in this case REST.
Then we will get this error when trying to get data with factory and model that have JSONAPI:

*ember.debug.js:29433 Error while processing route: network-elements Assertion Failed: normalizeResponse must return a valid JSON API document:
	* One or more of the following keys must be present: "data", "errors", "meta". Error: Assertion Failed: normalizeResponse must return a valid JSON API document:*

**Comment by danielspaniel** [comment]
What would you like the behavior to be in this situation ( and can it be generalized ) 
Should I always check the serializer for each model and ignore the adapter.  
 What if the adapter is one thing and the serializer another ( there is nothing I can do about that one I think except just pick one .. maybe the serializer always gets picked ?? )  
 What you think?

**Comment by iraspopo** [comment]
I think serializer should always be picked if available, otherwise use application serializer if available or default ember serializer JSONAPI if nothing is defined.

**Comment by danielspaniel** [comment]
Ok good, I agree. 
 I might also do the thing where I check each model serializer first then application serializer then application adapter then JSONAPI as you say

**Comment by iraspopo** [comment]
Sounds good. Thanks!

**Comment by danielspaniel** [comment]
Just out of curiousity.. why don't you define the application adapter as JSONAPI ?   Any reason for that to stay REST ?

**Comment by iraspopo** [comment]
I see no major reason not to be able to change application adapter to JSONAPI, other than we would have to use pathForType in each model adapter to get the right url (default REST adapter does it by default ). BTW, I got involved in current project when majority of the functionality was already implemented(so we are at this point only retrofitting the legacy app with some tests).In any case we have mix of two serializer for our models (JSONAPI and JSON) so we would still need more comprehensive solution.

**Comment by danielspaniel** [comment]
Ok .. I am double and triple checking to make sure the fix I do applies to a nice general solution, and your response confirms my idea that doing the model check on serializer will work for you and hopefully others. 
 I am still not sure I can cover every case where adapter is one thing serializer is another .. in application or in model, but I will try something and hopefully don't fall on my face.

**Comment by iraspopo** [comment]
Very much appreciated. If you have prototype we can test it, if that helps.

**Comment by danielspaniel** [comment]
Thanks  .. I will try and make all the different permutations ( I can think of )  because some might even be different than your case.  But I appreciate offer :)

**Comment by danielspaniel** [comment]
That was a monster to fix but new release does fix it ( unless you tell me otherwise ) 
https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.9.0

**Comment by iraspopo** [comment]
Checked with new version and worked fine when having some models with JSONAPISerializer and some with JSONSerializer. Thanks! Great job!

**Comment by danielspaniel** [comment]
Your welcome. Thanks for bringing it up ( again ) because overall .. was a good refactor. :)
