### ISSUE TITLE
add ability to make models in the new state

### ISSUE THREAD

**Issue by jakeonfire** [danielspaniel/ember-data-factory-guy#269]
factory-guy cannot make models in the new state for use in component integration tests. i had to use the following code to set a model in a component which - when saved - would issue a create (POST) in ember-data:

```javascript
  let store = this.container.lookup('service:store');
  let adapterAttrs = make('adapter').toJSON({ includeId: false });
  let adapter = run(() => store.createRecord('adapter', adapterAttrs));
  this.set('model', { adapter });
```

**Comment by danielspaniel** [comment]
ummmmmmm .. mmmmm .. hmmmm .. interesting. 
Would you like FactoryGuy be able to do that for you in one swift operation? 
 Can you propose a way that would work? 

 I have not needed this ( does not mean its not a good idea ) .. so I am not sure right now what is best way. 

 you could change this:
```javascript
  let adapterAttrs = build('adapter', id: null).get();
  let adapter = run(() => FactoryGuy.store.createRecord('adapter', adapterAttrs)); 
  this.set('model', adapter); // did you really mean to do { adapter } ?  seems odd 
```

I usually do this way because I am usually testing one or two attributes only and I don't mind if the rest are blank. 
```javascript
  let adapter = run(() => FactoryGuy.store.createRecord('adapter', {name: 'dude'})); 
  this.set('model', adapter); 
```

**Comment by jakeonfire** [comment]
your suggestion is more succinct, thanks. but yes, was wondering if it's possible to do a make to create a model in the 'new' state. we have some components which behave differently for new (creating) and existing (updating) records. as far as syntax - i'm not sure; just getting to know factory-guy. maybe:
```javascript
let adapter = build('adapter', isNew: true);
```
...since that is the recommended attribute for differentiating in user code, and it's read-only in ember-data. i am totally unfamiliar with the level of difficulty for implementation, however. do you think its possible?

**Comment by danielspaniel** [comment]
This ( using make ) would be confusing though because "make" is supposed to make a 'loaded' model. So your idea I do like so much. 
 FactoryGuy has the "build" method to make a json payload. 

  So, maybe there needs to be another name for "make me a new record"  like make createNew ? or makeNew ? .. then you could use the same traits and options as you would with make , build. 
  
```javascript
let newCan = makeNew('cat', 'calico', {name: 'Meow'})
```

**Comment by jakeonfire** [comment]
oh, and this code:
```javascript
let adapterAttrs = build('adapter', id: null).get();
```
produces hyphenated attributes (using JSONAPIAdapter with defaults) so won't work for handing to `store.createRecord` :o(

**Comment by danielspaniel** [comment]
Howdy partner, this is fixed in:
https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.10.1

**Comment by jakeonfire** [comment]
amazing - thanks!

**Comment by jakeonfire** [comment]
@danielspaniel I'm having an issue with `makeNew` related to my last comment before you closed the issue. `convertForBuild` with JSONAPIAdapter creates hyphenated attributes which don't match up to the camelCased ones in the model, so any attributes that have more than one word in them in the fixture aren't applied. e.g. in the new method, applying some logging:
```javascript
  makeNew() {
    let args = extractArguments.apply(this, arguments);
    ...
    let modelName = lookupModelForFixtureName(args.name);
    let fixture = this.buildRaw.apply(this, arguments);
    console.log("==> fixture:", fixture);
    let data = this.fixtureBuilder(modelName).convertForBuild(modelName, fixture);
    data = data.get();
    delete data.id;
    console.log("==> data:", data);

    const model = Ember.run(()=> this.store.createRecord(modelName, data));
    console.log("==> model:", model.toJSON());
    return model;
  }
```
yields:
`==> fixture:`
```javascript
{
  id: 1,
  name: "Adapter 1",
  coverageMergerClassName: "CoverageMergers::Synchronize"
}
```
`==> data:`
```javascript
{
  name: "Adapter 1",
  coverage-merger-class-name: "CoverageMergers::Synchronize"
}
```
`==> model:`
```javascript
{
  name: "Adapter 1",
  coverageMergerClassName: null,
  ...
}
```
Is this particular to my ember-data adapter setup or an issue with factory-guy? (sorry for the confusing use of `adapter` as the model in my examples!)

**Comment by jakeonfire** [comment]
per your original comment, the shortest i can write the code using `make` would be:
```javascript
let adapterAttrs = make('adapter').toJSON({ includeId: false });
let adapter = run(() => FactoryGuy.store.createRecord('adapter', adapterAttrs));
```

**Comment by danielspaniel** [comment]
hmm .. let me write a test for this @jakeonfire .. might be that I have to use 

```javascript
  let data = this.fixtureBuilder(modelName).convertForMake(modelName, fixture);
```

can you do me favour and swap that out and see what happens? 

good catch in any case

**Comment by danielspaniel** [comment]
@jakeonfire .. this is now fixe on v2.11.4  .. happy testing!

**Comment by jakeonfire** [comment]
perfect, thanks!
