### ISSUE TITLE
Move jquery-mockjax from bower dependency to npm dependency?

### ISSUE THREAD

**Issue by mblayman** [danielspaniel/ember-data-factory-guy#280]
Hi, @danielspaniel!

Have you already considered moving `jquery-mockjax` from being a bower dependency to an npm dependency? `jquery-mockjax` is the last vestige of bower that I have left in my project. Considering the Ember community seems to be moving away from bower, I was curious if you've thought about it already.

Is it a matter of getting the time to work on it? Or are there some blockers I'm unaware of? I might be able to take a crack at it if the answer is the former instead of the latter. Thanks!

**Comment by danielspaniel** [comment]
Sure thing @mblayman .. if you can make it work, I am up for it.
