### ISSUE TITLE
Setting non-persisted properties

### ISSUE THREAD

**Issue by GufNZ** [danielspaniel/ember-data-factory-guy#290]
In reading your docs and using the code in our tests, it seems the only way to set a non-persisted property on a model is after it's created by the factory.  I can use `afterMake` to do that, or do it manually via an `Ember.run(() => model.set('prop', value))` but `afterMake` is deprecated...

Any suggestions?  It'd be nice if I could do this inside the factory but I don't want to start relying on `afterMake` if it's about to go away...

**Comment by danielspaniel** [comment]
Good question @GufNZ ,  if you tell me exactly what you want to do I can give you better answer.  Give me a teeny bit more context, or nice example of what you are trying to do.

**Comment by GufNZ** [comment]
Specifically, we have models representing assets that get loaded asynchronously.  They have persisted properties to do with their content.  They also have an assetReady flag that is not persisted, set once the asset is loaded.

Some code is skipped if the relevant asset isn't ready yet, so to test fully I need to set that too.  The afterMake hook works fine for this but is deprecated.

**Comment by danielspaniel** [comment]
I might un deprecate the afterMake .. because if it works for you then that is good enough reason to keep it. There were issues with it working properly in certain situations( I forgot already ). 
But my guess is that there are ways of doing what you need to do with plain old attributes. 
 I just need to see the code for your models and the exact way you are using the afterMake.  
 I would be happy to screen share so I can see the context. Or if you can give me more code I can figure it out better. From what you said, I can almost get it. But I need the code to 100% get the full context.

**Comment by GufNZ** [comment]
models/image:
```
import DS from 'ember-data'

export default DS.Model.extend({
  views: DS.attr()
})
```

factories/image:
```
import FactoryGuy from 'ember-data-factory-guy'

FactoryGuy.define('image', {
  default: {
    //...
  },
  afterMake (model, attrs) {
    if (attrs.setAssetReady) {
      model.set('assetReady', true)
    }
  }
})
```

**Comment by GufNZ** [comment]
I can't put `assetReady` inside default as it's not a recognised model attribute so gets dropped.

I also don't want to persist the `assetReady` flag as that doesn't make sense.

The above is working, but I wasn't sure if there was a better way.

**Comment by danielspaniel** [comment]
one idea: 
 you could set a property assetReady on the model  and then in the serializer strip it out .. which would allow you to use traits for this 

 but I wonder how you setting assetReady in your application .. is that manually set or something?

**Comment by GufNZ** [comment]
It gets set by the ajax handler once that image gets loaded.  I guess that counts as manually.

**Comment by danielspaniel** [comment]
that is pretty manual .. so that is why I think in a test it is reasonable to set manually too. 
 but you know, if afterMake works for you and you like it, that is fine. 
  I will un-deprecate it and can assure you it will not go away in the future.

**Comment by danielspaniel** [comment]
I will close this when I fix the docs to stop saying it is deprecated

**Comment by GufNZ** [comment]
Cool, thanx.  (c:
