### ISSUE TITLE
how to build a named indirect relationship

### ISSUE THREAD

**Issue by GufNZ** [danielspaniel/ember-data-factory-guy#291]
If I have a model `A`, which has a `hasMany` of `B`, and `B` has a `belongsTo` of `C`, is there a way to define a factory that would return me an `A` with a certain trait `C` inside its list of `B`s that doesn't involve specifying in the `A` factory something like the following?
```
FactoryGuy.define('material', { list: [
    {
        id: 1,
        c: { id: 1, otherAttrs: 'here' }
    }, // a B
    {
        id: 2,
        c: { id: 2, otherAttrs: 'here' }
    }, // another B
]
```

I'd kinda like to specify in the `A` factory something like `{ list: [ ['B', 'someTrait'], ['B', 'otherTrait'] ] }` but have those traits describe specific `C`s under `B`s somehow.

It feels like I'm missing something obvious that would help...

**Comment by GufNZ** [comment]
I think I have it now..  The trick was to not pass a number as a 2nd arg to `hasMany` when passing a list of traits.

```
FactoryGuy.define('A', {
   default: {
      list: FactoryGuy.hasMany('B', 'trait1', 'trait2')
   }
})
```
```
FactoryGuy.define('B', {
   default: { /*...*/ },
   traits: {
      trait1: {
         c: FactoryGuy.belongsTo('C', 'trait1')
      },
      trait2: {
         c: FactoryGuy.belongsTo('C', 'trait2')
      },
   }
})
```
```
FactoryGuy.define('C', {
   default: { /*...*/ },
   traits: {
      trait1: { /* trait1 values here */ },
      trait2: { /* trait2 values here */ }
   }
})
```

Is this the best way to do what I'm doing?

**Comment by danielspaniel** [comment]
Yes. that is the way to do it.
 I think I wrote about it in the tips and tricks section:
https://github.com/danielspaniel/ember-data-factory-guy#tips-and-tricks 
 and FactoryGuy.hasMany works just like makeList or buildList
