### ISSUE TITLE
Enabled on development?

### ISSUE THREAD

**Issue by GufNZ** [danielspaniel/ember-data-factory-guy#292]
https://github.com/danielspaniel/ember-data-factory-guy/blob/982c7dbee8fe0cc662b69cfbd400583b8028bbbd/index.js#L58

Why is it enabled in `development` as well as `test` by default?

This is breaking our frontend as it has trouble loading a helper used in some of the factories.  I've disabled it in `environment/config` for now but is there a particular reason it tries to run in `development`?

**Comment by danielspaniel** [comment]
This is the age old question talked about here in #247 .
 See there for the explanations and solutions ( which you found yourself ) 
 Though I reckon I should put that solution in the doc? Do you feel like putting that there for me?
