### ISSUE TITLE
deep merge traits or alternative

### ISSUE THREAD

**Issue by GufNZ** [danielspaniel/ember-data-factory-guy#294]
I have a model with an array attribute.  I was trying to make a set of traits that would allow me to mix and match the entries of the array, but because [this line](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/model-definition.js#L148) does a shallow merge, they instead overwrite each other.

What is the recommended way to handle this?  Or should this be a feature-request for deep-merging traits?

**Comment by GufNZ** [comment]
(For now I'll try an `afterMake` approach instead...)

**Comment by danielspaniel** [comment]
mmm .. normally the traits override each other ( last one wins ) .. there may  be a way to do what you are trying to do .. in simpler way .. but not sure. need to see models and your factories .. ( an example ) .. also using ember-data-model-fragments might help too make this simpler to do. 
  not sure what your arrays look like though

**Comment by GufNZ** [comment]
```js
  traits: {
    /* These overwrite each other rather than mix: */
    dxt1: {
      views: [
        {
          format: 'dxt1',
          width: 8,
          height: 8
        }
      ]
    },

    dxt5: {
      views: [
        {
          format: 'dxt5',
          width: 8,
          height: 8
        }
      ]
    },

    rgb: {
      views: [
        {
          format: 'rgb',
          width: 8,
          height: 8
        }
      ]
    },

    rgba: {
      views: [
        {
          format: 'rgba',
          width: 8,
          height: 8
        }
      ]
    },

    png: {
      views: [
        {
          format: 'png',
          width: 8,
          height: 8
        }
      ]
    }
  },

  /* ...so I did it this way: make('image', { makeViews: ['dxt1', 'png'] }) etc. */
  afterMake (image, attrs) {
    if (attrs.makeViews) {
      image.set('views', attrs.makeViews.map(format => ({ format, width: 8, height: 8 })))
    }
  }
```

**Comment by danielspaniel** [comment]
if you used model fragments you could do this much much more elegant-o-lisiously.
 you could set up views as a fragmentArray
 set up the view types in the factory for view ( fragment ) 
 and then you could add the view fragments much much simpler 

```javascript
  let views = buildList('view', 'png', 'dxt1').get();
  let image = make('image', {views});
 // done!
```

**Comment by GufNZ** [comment]
True, but in this case, image has `views: DS.attr()` - it's not a relationship.  Tho I guess that would still work in a similar fashion.

The `afterMake` way means I just need the one line of setup.

**Comment by danielspaniel** [comment]
correct .. it is not a relationship .. but using fragments allows you to pretend at no cost to you. 
 It is way cleaner than what you are doing.  and though your setup might be less NOW .. if you write the setup as fragments the test setup will be LESS and  in the long run the tests will be more understandable .. up to you .. but you know my vote

**Comment by danielspaniel** [comment]
let me know if you still have more questions @GufNZ .. or else can you close this one?
