### ISSUE TITLE
Docs should explain the purpose of scenarios

### ISSUE THREAD

**Issue by phcoliveira** [danielspaniel/ember-data-factory-guy#296]
Sorry, I really don't want to look like a fool, but I just can't understand the purpose of scenarios. I am using Mirage's scenarios as a guidance, but not to much avail. Nothing on StackOverflow either.

It is easy to use Mockjax inside tests in order to mock a server. But how could I do that in development? Is that the purpose of using scenarios? If it is, then it is not as crystal clear as Mirage's config file.

**Comment by danielspaniel** [comment]
oooo .. I hear you .. I have maybe not enough documentation for that, because if you are confused than that is a sign. 
 Well, let me try and explain. 
  
 You have tests, and you happily use factory guy for creating data in unit/integration/acceptance tests. 
 The data is either pushed to the store ( make, makeList ) or put into mock payload ( build, buildList ) and used with ( mockFind, etc ) 
 But what about development mode. 
 You want to run your ember code and see it working in development, and you don't want to have a server sending data.  This is what scenarios do. They setup data for use in development environment.

  So, if your page shows list of users. 
 You can ( in your scenario file ) ->  

 ```js
 // app/scenarios/users.js
  let users =  makeList('user', 10)  and see the users in the list  
  mockFindAll('user').returns({models: users});
```
  and now when you go to a route that fetches the users 

```js 
  // app/routes/users.js    
  model() { return this.store.findAll('user'); }
```

 I just made pretend like you have this route. But it gives you the idea. 

 Any questions so far?

**Comment by phcoliveira** [comment]
Thanks, @danielspaniel, and I apologize for not being able to respond sooner.

Well, I am used to Ember and Rails, but the magic, this time, is somewhat too magical. I am guessing that having multiple scenarios is completely optional, and all these settings can be set in one "main" scenario, much like Mirage's config file.

I am also guessing that the order in which statements like "mockFind('user')" should matter, for it would be useful to have more specific matchings prioritized.

Thanks again.

**Comment by danielspaniel** [comment]
Yes, it is optional to have multiple scenarios. It helps to separate out the mock things for different routes. 
The difference here from mirage is that you can mock the calls for certain models and the rest will go to back end. You also can do shortcuts like put things in the store directly and the return those models as if it were an ajax call. 
The order can be important, but sometimes it is not. It sort of depends on what your doing. mockQuery is most likely to be the only one that matters but it depends on how specific you are in matching the query. 
I would be happy to screen share and talk about stuff so I can feed you ideas in a more rapid fire way. I am on East Coast time.

**Comment by phcoliveira** [comment]
Thank you very much, @danielspaniel, for disposing of you time to help me, but that won't be necessary. I getting to know how scenarios, and other things, can be worked with.

**Comment by fwoelm** [comment]
As a newcomer to Ember who just started using scenarios today and being somewhat confused about how they work, I found this very helpful! Love how it's all working now! :heart:

**Comment by Asherlc** [comment]
Sorry to dredge this up, but I'm a bit confused about the use of scenarios in tests. Are they meant to be just for development, or is it possible to use them in tests as well? For example, all my acceptance tests require mocking out certain models, and it'd be great to have that centralized, and scenarios seem like a possibility for that?

**Comment by danielspaniel** [comment]
not a problem @Asherlc  ... i never quite got into explaining 

what you can do and what I have done is have the scenario files in app/scenarios directory, 
then in tests, you can import those very same scenarios and use the methods on them. 

Usually you will have a different run method in tests, so what I actually do is setup a tests/scenarios directory 
and import the scenario I want from app/scenarios and override/extend it with new run method and so on. 

 If you don't know what i mean or it's unclear, I can post examples of code.

**Comment by Asherlc** [comment]
totally makes sense! Would you run that like so?

```
import MyScenario from 'appname/tests/my-scenario';

export default function(name, options = {}) {
  module(name, {
    beforeEach() {
      MyScenario.create().run();
      this.application = startApp();

      mockSetup();

      if (options.beforeEach) {
        return options.beforeEach.apply(this, arguments);
      }
    },
    afterEach() {
      mockTeardown();

      let afterEach = options.afterEach && options.afterEach.apply(this, arguments);
      return Promise.resolve(afterEach).then(() => destroyApp(this.application));
    }
  });
}
```

**Comment by danielspaniel** [comment]
sort of .. but I don't usually run scenarios for every test ( though you might want to for stubbing finding a user and that sort of thing ) 


```javascript
// file tests/acceptance/dudes.js

import moduleForAcceptance from '../../../helpers/module-for-acceptance';
import page from '../pages/dudes';
import Scenario from '../scenarios/dudes';  // test scenario in file: tests/scenarios/dudes.js

let scenario;
moduleForAcceptance('Acceptance | Service | Dudes Find', {
  beforeEach() {
    scenario = new Scenario();
    scenario.run();
  }
});

test('visting for first time shows dudes', async function() {
  let mock = scenario.findDudes();
  await page.visit();

  page.assertDefaultDudesSet();
});
```


```javascript
// file tests/scenarios/dudes.js

import Dudes from 'application-name/scenarios/dudes';
import User from '../user';

export default class extends Dudes {
  run() {
    this.include([User]);
    this.findSufers();
    return this;
  }

  findDudes({params=this.defaultParams(), num=7}={}) {
    this.dudes = this.buildList('dudes', num);
    return this.mockQuery('dudes')
      .withParams(params)
      .returns({ json: this.dudes });
  }
}
```

```javascript 
// file app/scenarios/dudes.js

import Ember from 'ember';
import FactoryGuy, {Scenario}  from 'ember-data-factory-guy';
import {dealerStatus, allStatus} from 'portal-ui/service/raps/find/controller';
import {compact} from '../../utils/object-functions';

export default class extends Scenario {

  run() {
    return this;
  }

  findDudes(trait) {
    this.reimbursements = this.buildList('dude')
    return this.mockQuery('service/reimbursement', {}).returns({ json: this.dudes });
  }
}

**Comment by Asherlc** [comment]
gotcha, thanks!
