### ISSUE TITLE
nested models

### ISSUE THREAD

**Issue by mnifakram** [danielspaniel/ember-data-factory-guy#300]
I have nested models like the following:  a `Vehicle` (Super Class) and Two submodels `Car` and `Moto`.

I defined a factory called `car.js` 

```
import './vehicle'
FactoryGuy.define('car', {
  extends: 'vehicle',
  default: {
    wheels: 4
  }
});
```
and then in my test I did the following setup:

```
const record = make('car');
mockFindRecord('vehicle').returns({ model: record });
```
Here I want to get all the vehicles regardless of the type (`Car` or `Moto`). The mock works well except that it return the object with `modelName=vehicle` which is the argument passed to `mockFindRecord('this is what always get returned')`?  I need the real `modelName` as I have  a component that render based on the `model.constructor.modelName`.

I found a dirty fix by overriding the `modelName` after [this line](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/mocks/mock-get-request.js#L88)

```
case 'model':
        model = options.model;

        Ember.assert(`argument ( model ) must be a Model instance - found type:'
          ${Ember.typeOf(model)}`, (model instanceof Model));

        json = { id: model.id };
        modelName = model.constructor.modelName; // this work like a charm
        this.setResponseJson(this.fixtureBuilder.convertForBuild(modelName, json));
        break;
```

is there a better way to do it? Or at least how to reopen this class and redefine it. thanks

**Comment by danielspaniel** [comment]
well @mnifakram, I am alittle confused  

 Are you trying to get list of all vehicles with mockFindRecord? because that only returns one model.
 I am alittle bit confused and don't know how to help you without more context.

Can you tell me what exact call you are trying to  mock?   Is there a line in the route like ... 

 ```js
 let vehicles = this.store.findAll('vehicle');  // ?? 
```

 Or can you describe more of what is where and how needs what where.

**Comment by mnifakram** [comment]
@daibhin I know it's a little bit confusing and not obvious. I'm trying to mock the loading of relationships the way ember does. 
If a `Person` hasMany `Vehicle` when loading the Person including the `vehicles`, when trying this

`visit(`person/${person.id}/vehicles/${vehicle.id}`); `
Ember will make a get request  **https://domain.com/api/vehicles/1**

which could be a `Car` or a `Moto`.

**Comment by danielspaniel** [comment]
ok.. that is helpful.  getting warmer.
 so is this a call because the person hasMany vehicles and the relationship is async? 
 of if not tell me more about when/where/how the call is being made ( like from find/findAll )

**Comment by mnifakram** [comment]
@danielspaniel yes you're exactly right. Any ideas?

**Comment by danielspaniel** [comment]
```js

const car = make('car'),
           moto = make('moto'),
           person = make('person', {vehicles: [car, moto]});

mockFindRecord('person').returns({ model: person });
mockFindRecord('vehicle', car.id).returns({ model: car }); 

```

this setup does not work correct?

**Comment by mnifakram** [comment]
nope doing like that results to this error 
`Assertion Failed: You're trying to use a trait [1] for model vehicle but that trait can't be found.`

**Comment by danielspaniel** [comment]
I corrected the above thing but it still will not help because

 => I don't think I have come across this problem because you are doing something I think which is non standard ( correct me if I am wrong )  because even for polymorphic models there is usually a route for each model type ( /car  , /moto  ) ( at least that is how I do it )  
and usually not one for all of them ( /vehicle ) in a rest style api.

**Comment by mnifakram** [comment]
Just to explain more the 'error' or non expected behavior

```
const car = make('car'),
           moto = make('moto'),
           person = make('person', {vehicles: [car, moto]});
// car.constructor.modelName ==> car
// moto.constructor.modelName ==> moto
// the above output is right and expected
mockFindRecord('person').returns({ model: person });
mockFindRecord('vehicle').returns({ model: car });

// from my component if I console.log(car.constructor.modelName)==> it prints out vehicle
// which is not what I want 

```
@danielspaniel what I'm doing looks normal to me a Person has many Vehicles. What to do if you want to list all the vehicles (Car and Moto) in one template? you do separate request?

**Comment by mnifakram** [comment]
@danielspaniel is there a way on how to change _setReturns prototype from my Ember app?

**Comment by danielspaniel** [comment]
sorry to say @mnifakram , I am on vacation starting 10 minutes ago for about  5 days so if you don't hear from me it is because i unplugged the internet and ran away into the woods.

**Comment by mnifakram** [comment]
@danielspaniel I'm so sorry and I don't want to bother you again but is there a quick way on how to redefine that method. Please

**Comment by mnifakram** [comment]
The only way to get it done per the current implementation is like the following 

```
const car = build('car', { id: 1 }),
      moto = make('moto'),
      person = make('person', {vehicles: [car, moto]});

mockFindRecord('person').returns({ model: person });
mockFindRecord('vehicle').returns({ json: car }); // this will return the right modelName`
```

closing this.
