### ISSUE TITLE
Set circular relationship though build

### ISSUE THREAD

**Issue by mnifakram** [danielspaniel/ember-data-factory-guy#303]
Is there a way to set circular relationships using build?

eg:
```
const bill = build('person', { name: 'bill' });
const car1 = build('car', { owner: bill });
const car2 = build('car', { owner: bill });
// set is not a function as bill is not a DS Model
bill.set('cars', [car1, car2]);
```

**Comment by danielspaniel** [comment]
build is meant to create a simulated server payload, so circular relationships are not needed. 
If you tell me what your context is ( what your trying to do / test ) I can tell you how to achieve what you need though.

**Comment by danielspaniel** [comment]
@mnifakram , want to talk more about this?  need more ideas ?  let me know.

**Comment by danielspaniel** [comment]
closing due to lack of responsyness, but feel free to reopen for more discussion
