### ISSUE TITLE
relationship IDs in nested model

### ISSUE THREAD

**Issue by tachun** [danielspaniel/ember-data-factory-guy#304]
Hello,
I'm trying to do use `belongsTo().id()` to get model's id without send a request to fetch whole model object, my models are like these:
`assignment` belongsTo `task`, `task` hasMany `assignments`
`task` belongsTo `classroom`, `classroom` hasMany `tasks`

I need classroom's id via an assignment and it's task, it works fine with Ember data by using: `this.get('assignment.task').belongsTo('classroom').id()` but with `make()` in test `this.get('assignment.task')` looks like wrapped into a proxied `content` object

```
this.set('taskStub', FactoryGuy.make('task'));
this.set('assignment', FactoryGuy.make('assignment', { task: taskStub }));

this.get('taskStub').belongsTo('classroom').id()  // get "1"
this.get('assignment.task').belongsTo('classroom').id()  // this.get(...).belongTo() is not a function
this.get('assignment.task.classroom.id')  // get "1", but will send a request to fetch whole classroom

this.get('assignment.task.content').belongsTo('classroom').id()  // get "1"
```

Maybe I missed something, does anyone have any idea of this? thx !

**Comment by danielspaniel** [comment]
looks like you are trying to twist yourself into a knot. 
why don't you just make stuff the easy way? 
```
let classroom = FactoryGuy.make('classroom');
let task = FactoryGuy.make('task', {classroom});
let assignment = FactoryGuy.make('assignment', { task });
```
then: => assignment.get('task.classroom.id')  

as usual though, you might have some reason for doing the things your doing. but I can't see it because you did not really post your test or you model classes. I am guessing your models are not set to async: false though, but since I can't see them it's only a guess.

**Comment by tachun** [comment]
Thanks for quick reply,
the reason for doing things this way is because I only have an `assignments.json`(json api) like this:
```
    "data": {
        "id": "25",
        "type": "assignments",
        "attributes": {...},
        "relationships": {
            "task": {
                "data": { "id": "553", "type": "task" }
            }
        },
        "included": {
            "task": {
                "data": { 
                    "id": "553", 
                    "type": "task",
                    "attributes": {...},
                    "relationships": {
                        "classroom": {"data": { "id": "1", "type": "classroom" }}
                    },
                }
            }
        } 
```
`task` is included but not `classroom`, and there is a reason we can't included `classroom` easily on backend side... so `classroom` is not in the store at this moment.

I've tried to set `{ async: false }` in task model like: `classroom: belongsTo('classroom', { async: false })`, but it still send the request to `classroom/:id` :(

**Comment by danielspaniel** [comment]
In that case then 
```classroom: belongsTo('classroom', { async: true })``` or just 
```classroom: belongsTo('classroom')``` is correct

But as I said before, I don't know what you are actually trying to do. I need the big picture ( more context ) or else I can't help you.
