### ISSUE TITLE
MockFindRecord.fails() does not capture preflighted requests

### ISSUE THREAD

**Issue by roschaefer** [danielspaniel/ember-data-factory-guy#309]
I'm trying to test the behaviour for a HTTP 404 response of the backend:
```javascript
    describe('HTTP 404 from backend', function() {
      beforeEach(function() {
        broadcastMock.fails({status: 404, response: {errors: {status: '404', name: ["broadcast not found"]}}});
      });

      it('shows a 404 error page', function() {
        visit('/broadcast/' + broadcast.get('id'));

        return andThen(() => {
          expect(find('p').text()).to.have.string('We could not find that page');
        });
      });
```
Apparently that is not possible, because the `.fails()` does not capture the preflighted request and therefore I get an `Error: The adapter operation was aborted` and the route cannot reach the error event.

I believe this is a bug.

See the entire acceptance test here: https://github.com/roschaefer/rundfunk-mitbestimmen/commit/42feff029c96785328e8f839867da797773a909a

![selection_086](https://user-images.githubusercontent.com/2110676/32134984-b8a140fa-bbf7-11e7-9968-e0b8722c667f.png)

**Comment by danielspaniel** [comment]
This is tested pretty well already in the factory guy test suit, so I know it works. The question is .. what is different about your setup ( which looks great to me ) than mine. 
 What version of everything are you using? 
  Ember, ember-data, and factory guy ?

**Comment by roschaefer** [comment]
```
$ ember --version
ember-cli: 2.16.2
node: 8.3.0
os: linux x64
```

```
$ yarn list | grep ember-data
├─ ember-data-factory-guy@2.13.8
├─ ember-data@2.16.3
```

I reach the error page in `development` environment. When I debug the route in `test` environment, the `error(error, transition)` event is not called at all.

I set up a test case to see what happens when factory guy just `.return({model: broadcast})` instead of a failure, everything works as expected.

**Comment by roschaefer** [comment]
I created at least one model with `make('broadcast')` as described in the README. Besides that, I suspected a chained call to the `broadcastMock` to be the reason for the error (`broadcastMock.returns({ ... }).fails({...})`) but that does not seem to be the case.

**Comment by danielspaniel** [comment]
you are making one very small error 
I will post this again with your setup too, ( that is clue ) and give you 5 minutes to figure it out:

```javascript 
 beforeEach(function() {
     broadcastMock = mockFindRecord('broadcast');
     broadcast = make('broadcast', {  title: 'This is the title'  })
  });
 describe('HTTP 404 from backend', function() {
      it('shows a 404 error page', function() {
        broadcastMock.fails({status: 404, response: {errors: {status: '404', name: ["broadcast not found"]}}});

        visit('/broadcast/' + broadcast.get('id'));

        return andThen(() => {
          expect(find('p').text()).to.have.string('We could not find that page');
        });
      });
```
If after 5 mins you don't get it I will give more clues :)

**Comment by roschaefer** [comment]
order of `broadcastMock` and `broadcast = make(...)` ? - No.

**Comment by danielspaniel** [comment]
ooo .. so close .. 😅

**Comment by danielspaniel** [comment]
broadcastMock way to inspect the payload ( first clue )

**Comment by danielspaniel** [comment]
when you mock a payload with 
```javascript
  let mock = mockFindRecord('broadcast');
```
 the magic here is that the payload is built for you automatically, and the route that is mocked is setup based on that payload 

do you give up yet?

**Comment by roschaefer** [comment]
I see a broadcast which I did not build explicitly.

**Comment by roschaefer** [comment]
... errr, I don't get it yet. I wonder right now, that:
```
        return andThen(() => {
          console.log(broadcastMock.get());
          expect(find('p').text()).to.have.string('We could not find that page');
        });
```
has a broadcast.
```
{title: "Lovely broadcast", description: "It is really great", id: 1}
description
:
"It is really great"
id
:
1
title
:
"Lovely broadcast"
```

**Comment by danielspaniel** [comment]
yes, that was built for you as a friendly customer service sort of gesture. saving valuable calories that you would waste having to do this
```javascript
 let broadcastPayloadNumberONE = build('broadcast');
 let mock = mockFindRecord('broadcast').returns({json: broadcastPayloadNumberONE});
```

**Comment by danielspaniel** [comment]
look at the     =>  id value on that payload 
look at the    => id value on the broadcast model you made with make   

 clue # 3

**Comment by roschaefer** [comment]
For that reason I created the accompanying test case which succeeded :thinking: 

I had `visit('/broadcasts/4711')` before I used the `broadcast.get('id')` of the mock (that should fail in the 2nd case)...

**Comment by danielspaniel** [comment]
visit('/broadcast/' + broadcast.get('id'));

visit('/broadcast/' + **broadcastMock**.get('id'));

**Comment by roschaefer** [comment]
Ok, now I reach the `error` event in the route

**Comment by danielspaniel** [comment]
do you understand why?

**Comment by roschaefer** [comment]
https://github.com/danielspaniel/ember-data-factory-guy/blob/master/tests/acceptance/user-view-test.js#L16

**Comment by roschaefer** [comment]
not at all

**Comment by danielspaniel** [comment]
please say yes .. don't make me cry in my soup

**Comment by danielspaniel** [comment]
oh .. well .. too late then.. i cried already .. but I am better now

**Comment by roschaefer** [comment]
Well, sorry for that. I just used the example acceptance test of the plugin and I don't understand why it should matter if I use the auto-generated id of the model of ember-data's store or the id of the mock.

**Comment by danielspaniel** [comment]
Ok .. let's review 

```javascript  // from that example in factory guy
let user = build('user', { projects: projects });
  mockFindRecord('user').returns({ json: user });

  await visit('/user/' + user.get('id'));
```

and what you were doing 

```javascript 
  describe('HTTP 404 from backend', function() {
      it('shows a 404 error page', function() {
        broadcastMock = mockFindRecord('broadcast');  
        broadcast = make('broadcast', {  title: 'This is the title'  })
        broadcastMock.fails({status: 404, response: {errors: {status: '404', name: ["broadcast not found"]}}});
          //  broadcastMock.get('id')  !== broadcast.get('id') 
        visit('/broadcast/' + broadcast.get('id')); // this will not work  ( id is wrong ) 
        visit('/broadcast/' + broadcastMock.get('id'));  // this will work because you have to ask the mock for it's id that it is mocking 
        return andThen(() => {
          expect(find('p').text()).to.have.string('We could not find that page');
        });
      });

```

**Comment by roschaefer** [comment]
I was expecting `mockFindRecord` simply to mock *any* route, regardless what `id` I supply. (Unless I explicitly do so)

**Comment by danielspaniel** [comment]
Ah ha .. now that is interesting point

**Comment by danielspaniel** [comment]
I never  had that mock style setup that way  .. but I don't think it is possible
 because it would not know what to return for a payload when you do 

 mockFindRecord('broadcast') 
 and then 

 store.find('broadcast', id1)
 store.find('broadcast', id2)

 would return the same model .. which would be bad 

  and in your case  you said visit with the real model id .. so that would expect to return the model 

 anyway .. you just got confused .. so no worries .. 

   if you have more questions let me know

**Comment by danielspaniel** [comment]
i sick of typing so i would rather get on slack and talk there if you want to argue about this more ( which I don't mind )

**Comment by roschaefer** [comment]
In the example acceptance test, `user` refers to the model created on line 12. I did the same thing and it works great in the other test case of my acceptance test. That's why I stopped to think my test setup was wrong.

Ok, I learned sth. today:
* mockFindRecord has an id
* that Id can be different from the returned model

I have to admit that I don't understand the necessity for the two points. But I think I will get into it when the confusion clears up a little. Thanks anyways.

Feel free to close this.

**Comment by roschaefer** [comment]
Or I'll just close this. I'll bother you on slack another time ..

**Comment by danielspaniel** [comment]
One mistake you are making in thinking 

 - mockFindRecord has an id
-  that Id can be different from the returned model ( not true ) 

  your test could have been simpler and looked like this  =>

 ```javascript
let broadcastMock = mockFindRecord('broadcast');  
broadcastMock.fails({status: 404, response: {errors: {status: '404', name: ["broadcast not found"]}}});
visit('/broadcast/' + broadcastMock.get('id'));  // returns payload from broadcastMock and that will be the model used in route 
```

so you did not have to make a broadcast model to return ( because the mock is already returning a broadcast payload ) is what is important here

**Comment by roschaefer** [comment]
https://github.com/roschaefer/rundfunk-mitbestimmen/pull/378/commits/227fca741b2d0972ecab6221ecaa94235dedb1d2

I specify the broadcast model now in the group that checks the title of the broadcast to appear on the page.

**Comment by roschaefer** [comment]
By the way, I think I get my head around this: When I do `fails()` the returned model (and therefore the id of the mock) is the "default" model. I had chained the calls in my test setup like this:

```javascript
broadcastMock = mockFindRecord('broadcast'); // would return a random model
broadcast = make('broadcast', {  title: 'This is the title'  })
broadcastMock.returns({model: broadcast}); // returns "my" model
broadcastMock.fails({status: 404}); //  but now it's the previous default model again, with a different id
visit('/broadcast/' + broadcast.get('id')); // fails, wrong id
```

And that's the reason why the example acceptance test of this plugin succeeds and the second test case of my acceptance test as well.

If my assumption is correct, it would be great if `ember-data-factory-guy` could return the specified returned model, if any, and after that take a default model.

**Comment by danielspaniel** [comment]
I actually have been testing more to figure out what is going on here 
 ( thanks for really hanging in there on this one .. it's admirable ) 
AND  grand and final conclusion that I can find is> 
   if you're going to mock a fail for a findRecord  don't make a model and pass back that model if you expect a 404 .. NOT FOUND.  

```javascript 
broadcastMock = mockFindRecord('broadcast'); // would return a random model
broadcast = make('broadcast', {  title: 'This is the title'  })  // not needed 
broadcastMock.returns({model: broadcast}); // don't return a valid model and then mock a 404 
broadcastMock.fails({status: 404}); 
visit('/broadcast/' + broadcast.get('id')); 
```

you are doing too much setup for nothing 
 
for a fails for mockFindRecord 

```javascript 
broadcastMock = mockFindRecord('broadcast'); // would return a random model
broadcastMock.fails({status: 404}); 
visit('/broadcast/' + broadcastMock.get('id')); 
```
 that is all you should do .. and no more 

I am actually trying to fix that right now .. so that you will not have that error and it will return null on 404 fails, but still .. simpler is better and especially in this case it is not just simpler .. it is silly to return a model ( that is in the store ) and then say it's a 404 not found

**Comment by roschaefer** [comment]
I agree.

My pattern to expose a certain bug or an unimplemented feature is to set up two test cases: Test A checks existing behaviour and is expected to pass while Test B shares much of the test set up of Test A but exposes the targeted functionality. This pattern served me well, usually it ensured that I did the test set up right. Well, not this time. Instead it made me think that the call of `.fails()` was the only problem.

In the last commit, I moved the not-to-be-shared part of the setup (returning a model and use its `id` to generate the url) of Test B into Test A exclusively.

If you want I can send a pull request that uses the less ambiguous `mockFindRecord.get('id')` instead of `model.get('id')` for the url in the example acceptance tests.

**Comment by danielspaniel** [comment]
Oddly the example I showed was fine because the mock model that was returning was the same one returned by the mockFindRecord. 
 In your case that was also the case ( I think ) BUT the big difference is:
 This test that passes is expecting the model to be found. 

 You were expecting a find to fail when that model was in the ember data store. That just did not sit well with ember data. That is why for a fail you should not use returns({model: myModel}).fails()  just do .fails on the mock and stop there. 

 I am going to fix the docs to show that and even put a fails test in the acceptance tests as well 
 If you can think of anything else to document, let me know
