### ISSUE TITLE
Using and mocking store.findRecord() in didReceiveAttrs()

### ISSUE THREAD

**Issue by gabz75** [danielspaniel/ember-data-factory-guy#311]
Hi,

I'm having a testing issue with a component using `store.findRecord`.

I've created a repo to reproduce and isolate the issue. You can find two components:

- [comp-find-record](https://github.com/gabz75/fg-find-record-in-did-receive-attrs/blob/master/app/components/comp-find-record.js)
- [comp-find-all](https://github.com/gabz75/fg-find-record-in-did-receive-attrs/blob/master/app/components/comp-find-all.js)

They respectively use `store.findRecord` and `store.findAll` inside the `didReceiveAttrs()` hook.

I've created two integration tests that uses `mockFindRecord` and `mockFindAll`.
- [comp-find-record-test](https://github.com/gabz75/fg-find-record-in-did-receive-attrs/blob/master/tests/integration/components/comp-find-record-test.js) < this one fails with the error below:
- [comp-find-all-test](https://github.com/gabz75/fg-find-record-in-did-receive-attrs/blob/master/tests/integration/components/comp-find-all-test.js) < this one passes

```
 Pretender intercepted GET /users/1 but encountered an error: Nothing returned by handler for /users/1. Remember to `return [status, headers, body];` in your route handler.
```

Here is the repo: https://github.com/gabz75/fg-find-record-in-did-receive-attrs

Thanks!

```
$ ember --version
ember-cli: 2.13.1
node: 6.11.3
os: darwin x64
```

**Comment by danielspaniel** [comment]
I see your issue, and the test is to me a foul play.  For the test to really be fair, you would set up the component 
 like this 
```javascript 
test('it renders', function(assert) {
  let user = make('user');
  this.set('userId', user.id);
  
  mockFindRecord('user').returns({ model: user });

  this.render(hbs`{{comp-find-record userId=userId}}`);

  assert.ok(true);
});
```

and then the component 

```javascript 
  didReceiveAttrs(...args) {
    this._super(args);
    get(this, 'store').findRecord('user', this.get('userId');
  },
```

what you are doing is 
```javascript 
  get(this, 'store').findRecord('user', 1);
```
and that '1' should be '2'  ( I can explain why later ) but if your going to hard code you just got it wrong, but what I am saying is that is kind of not fair to hard code user id in the component because your assuming factory guy will have the id of 1 for you .. but you can't assume that.

**Comment by danielspaniel** [comment]
can I close this .. do you see what I meant?  need any other help with this? be happy to explain more.

**Comment by danielspaniel** [comment]
closing due to lack of responsyness, but please reopen if you have a further question or you not happy with something.
