### ISSUE TITLE
Can't use with ember-data-model-fragments the way specified in documentation

### ISSUE THREAD

**Issue by jniechcial** [danielspaniel/ember-data-factory-guy#313]
I found inconsistency in what is recommended way for usage with `ember-data-model-fragments`. According to documentation we should be able to run:
```
let phoneNumbers = buildList('phone-numbers', 2).get();
let employee = make('employee', { phoneNumbers });
```
However, `make` is not using serializers which means that JSON returned from `build` or `buildList` will not be deserialized. In such scenario, if we have a serializer that is serializing keys to underscore in `keyForAttribute`, they will be returned from `build` as underscore and passed into `make` and directly to `store` which won't create fragment models properly. 

The workaround for me is to pass the objects with camel cased attributes instead of `build` model fragments. To make it more standarized there probably should be serializers involved in the pipeline both in `build` to serialize and in `make` to create JSON and deserialize.

cc @patocallaghan for reference.

**Comment by danielspaniel** [comment]
@jniechcial , I sort of see what you mean, but for even more thrill and excitement can you me/you/us both a huge favour and make a failing test for that in the factory guy repo?  That way I can see what happened and then when I fix it .. see that it works??

**Comment by jniechcial** [comment]
Absolutely! Sorry for this!

**Comment by danielspaniel** [comment]
Ok, after a long few days of puzzlement, I finally thought of a way to resolve this.  It required a large internal factory guy refactor ( which was fun times and made things better ), but now you fragments are handled much more cleanly.  

 Now, you can use make to make fragments for a model like this: 

```javascript 
test('make with manual setting up employee name', function(assert) {
  let firstName = 'Joe',
      lastName  = 'Black',
      name      = {firstName: 'Joe', lastName: 'Black'},
      employee  = make('employee', {name});

  run(() => {
    let names = run(() => employee.get('name').getProperties(['firstName', 'lastName']));
    assert.deepEqual(names, {firstName, lastName});
  });
});

test('make with manual setting up employee name ( another way )', function(assert) {
  let firstName = 'Joe',
      lastName  = 'Black',
      name      = make('name', {firstName: 'Joe', lastName: 'Black'}),
      employee  = make('employee', {name});

  run(() => {
    let names = run(() => employee.get('name').getProperties(['firstName', 'lastName']));
    assert.deepEqual(names, {firstName, lastName});
  });
});
```

or for build you would do what I mentioned before:
```javascript 
test("build json payload by manually setting up employee name and retrieve model from store.findRecord", async function(assert) {
  let firstName = 'Joe',
      lastName  = 'Black',
      name      = build('name', {firstName, lastName}).get(),
      employee  = build('employee', {name});

  mockFindRecord('employee').returns({json: employee});

  let model = await run(async () => FactoryGuy.store.findRecord('employee', employee.get('id')));
  let names = run(() => model.get('name').getProperties(['firstName', 'lastName']));
  assert.deepEqual(names, {firstName, lastName});
});
```

Now, when you make a fragment or build a model or fragment and there is a hadMany or a belongsTo in the factory definition  it will all be handled correctly. 

Thanks again for bringing up the issue because it really improved things overall. 

use  v2.13.17  for the new code

also, feel free to add documentation and PR that if you like .. i appreciate the help on that

**Comment by jniechcial** [comment]
@danielspaniel impressive job! Thanks! I will add a PR with docs after the weekend (or during). Thanks again!
