### ISSUE TITLE
mockQuery doesn't return models

### ISSUE THREAD

**Issue by Exelord** [danielspaniel/ember-data-factory-guy#324]
Hey @danielspaniel,
I found your addon- is genius!
But I encounter some weird behavior of `mockQuery`. It doesn't return models at all :/ I have a component which calls a `query` but it doesn't receive any data. If I would change it to findAll - it works as expected.

Here below is a simple test which expects from the mock to return the mocked json. It constantly fails :/ Could, you please verify it?

```js
test('it return correct amount of models on query', function(assert) {
  let json1 = buildList('guest', 2);
  mockQuery('guest', { a: 1 }).returns({ json: json1 });

 // component call here

  FactoryGuy.store.query('guest', { a: 1 }).then((records)=> {
    assert.equal(records.length, 2);
  });
});
```

EDIT:
In development scenarios it works, so the problem is only in tests.

In development when I have:
```js
this.mockFindAll('guest', 3);
this.mockQuery('guest', { filter: { q: 'test' } }).returns({ models: this.makeList('guest', 2) });
```

it correctly responds to:
```js
return this.get('store').query('guest', {
      filter: {
        q: this.get('searchQuery')
      }
    });
```

but in tests, it doesn't

**Comment by Exelord** [comment]
Sorry, solved!
Taking a query require using await as it loads somehow differently than findAll

**Comment by danielspaniel** [comment]
Good question and good answer 😄   I am surprised that findAll does not require an await also. Me curious. But glad you figured it out
