### ISSUE TITLE
Application's store unavailable message wrong for latest ember-cli-qunit

### ISSUE THREAD

**Issue by Charizard** [danielspaniel/ember-data-factory-guy#326]
With the new emberjs/rfcs#232 RFC, the error message when Factory Guy can't access the application instance is wrong.

This
```
Assertion Failed: [ember-data-factory-guy] FactoryGuy does not have the application's store.
       Use manualSetup(this.container) in model/component test
       before using make/makeList
```
should change to
```
Assertion Failed: [ember-data-factory-guy] FactoryGuy does not have the application's store.
       Use manualSetup(this.owner) in model/component test
       before using make/makeList
```

**Comment by Charizard** [comment]
*You are 😆 

Thanks for the awesome addon though.

**Comment by danielspaniel** [comment]
This is now fixed in v2.13.24 

 I made it so you can not screw it up anymore since now .. you only have to do

```js 
manualSetup(this);
```
and it will so the right thing

 Thanks for pointing out he message being wrong :)

**Comment by Turbo87** [comment]
FWIW I would recommend exporting a `setupFactoryGuy()` function for the new testing APIs like this:

```js
export function setupFactoryGuy(hooks) {
  hooks.beforeEach(function() {
    manualSetup(this.owner);
  });
}
```

**Comment by danielspaniel** [comment]
good suggestion .. stay tuned for that one

**Comment by danielspaniel** [comment]
v2.13.26 now has setupFactoryGuy(hooks) method @Turbo87

**Comment by Turbo87** [comment]
awesome, thanks! seem like I can remove our custom one then 😉
