### ISSUE TITLE
ember-cli 2.17 breaks initializer

### ISSUE THREAD

**Issue by thec0keman** [danielspaniel/ember-data-factory-guy#327]
ember-cli 2.17 changed the way the application is set up: [source](https://github.com/ember-cli/ember-cli/commit/4d21f92ddf2b25cbae2d9326d7b83125bb8e3173#diff-5f835b0755003822773a475fbb5eadb9)

This means that for acceptance tests, the initializer for this addon uses will fire before the app has a container (i.e. like a fastboot app.)

I'm guessing that migrating this to an instance initializer would solve it.  Alternatively documentation could be updated to indicate that for acceptance tests you need to use `manualSetup` as well.

What is the ideal solution for this?

**Comment by danielspaniel** [comment]
I think all you have to do is add a beforeEach hook just like you do for the other tests, and I will update the docs with a new acceptance test in this style to show how it's done. thanks for heads up on this. 

```js
  hooks.beforeEach(function() {
    manualSetup(this);
 });
```

**Comment by danielspaniel** [comment]
The docs are now updated and I converted a test to use the new style 

example here:  
https://github.com/danielspaniel/ember-data-factory-guy/blob/master/tests/acceptance/user-view-test.js

**Comment by thec0keman** [comment]
:+1:  I like that approach.  I agree it is less magical, as well as more inline with the overall testing philosophy they've been moving towards (more API parallels between acceptance and integration/unit testing).
