### ISSUE TITLE
mergeDeep() seems to cause "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by Turbo87** [danielspaniel/ember-data-factory-guy#328]
Using Ember v3.1.0-beta.1 I'm seeing "RangeError: Maximum call stack size exceeded" which, according to the call stack, seems to be caused by the `mergeDeep()` function in `ember-data-factory-guy`. Unfortunately I'm not sure what exactly is causing this... 😞

**Comment by Turbo87** [comment]
Looks like in some situations this is also triggered even in Ember 3.0 stable 🤔

**Comment by Turbo87** [comment]
https://github.com/emberjs/ember.js/issues/16049 is possibly related to this

**Comment by danielspaniel** [comment]
v2.13.26 has your fix, thanks again  😄
