### ISSUE TITLE
Mocking findRecord with buildList

### ISSUE THREAD

**Issue by Exelord** [danielspaniel/ember-data-factory-guy#332]
Hey Daniel :)
Is it possible to mock findRecords for items from buildList?

I'm working with scenarios in mock environment and Im trying to mock findAll and findRecord for each built object. It is possible?

So right now I have sth like this, but it doesn't work correctly :/

```js
    let users = this.buildList('user', 3);

    let list = [users.get(0), users.get(1), users.get(2)];
    list.forEach((attrs) => this.mockFindRecord('user').returns({ json: this.build('user', attrs) }));
```

another small issue I found is; `this.attributesFor` is not accessible in scenarios ;)

**Comment by danielspaniel** [comment]
Right, gotta fix that about attributesFor Maciej. 

  Ok .. well .. I would suggest 1 possibility.  Use => FactoryGuy.cacheOnlyMode()
  That way you can build models ( like users ) and for store.find or store.findAll they will be used automatically. There is nothing to mock anymore. But that just makes is too easy .. I know, so sorry about that.  We need something with more suffering. 

 You could otherwise probably better off without the list style. 
```js
    let user1 = this.build('user');

    let list = [users.get(0), users.get(1), users.get(2)];
    list.forEach((attrs) => this.mockFindRecord('user').returns({ json: this.build('user', attrs) }));
```

**Comment by Exelord** [comment]
:D Yeah, we need more suffering xD

is this `FactoryGuy.cacheOnlyMode();` set globally? I mean it will be working in all scenarios?
There is one problem with it :/ I don't have the delay on requests anymore which is very crucial for me as my app relies on loading states I need to see what is happening.

How can mock also in the second example `findAll` which those created users?

**Comment by danielspaniel** [comment]
cacheOnlyMode is kinda global so that is good point. 
also, about the waiting. I usually don't care, but if you do, then you do which is important. 

 So, here is what you would do.  Once again, it is far too easy.  😄 

```js
   let users = this.makeList('user');
   let [user1, user2] = users;

   this.mockFindRecord(user1);
   this.mockFindRecord(user2);
   this.mockFindAll('user').returns({models: users});
```

 You know how to set up ajax waiting time in Scenarios ? I guess you do, since you need that feature.

**Comment by danielspaniel** [comment]
hi @Exelord , did this work for you? need anything else? can i close this?

**Comment by Exelord** [comment]
I would be grateful for leaving it for now. I'm on the holidays, I will get back to it in the next week.

**Comment by Exelord** [comment]
So... There is one more problem with the proposed solution :/ It pushes the records to the store before they have been requested. That's why I wanted to achieve this with buildList

**Comment by danielspaniel** [comment]
Ok Maciej, fair enough.  If you want to use buildList then his will work:

```js
let json = buildList('user', 2);
mockFindAll('user').returns({json});
json.get().forEach(item=> {
  mockFindRecord('user').returns({id: item.id})
})
```

**Comment by Exelord** [comment]
Look cool, but after a test, it doesn't work :/ I says that `/users/1` endpoint is not defined but it is.

**Comment by danielspaniel** [comment]
can you post your entire test here?   and also show me the route (model hooks )  want to make sure that I know the order in which the users are fetched .. gotta be something I am not seeing

**Comment by Exelord** [comment]
Im doing this in scenarios :/ Ive pasted your example, and in the ember app cant fetch it.

**Comment by danielspaniel** [comment]
might have to sceen share then? if you don't mind that i stare at the code for a few minutes

**Comment by danielspaniel** [comment]
can you make an ember-twiddle to show your scenario? 

https://ember-twiddle.com/421f16ecc55b5d35783c243b8d99f2be?openFiles=tests.unit.model.user-test.js%2C

i have ideas of how to fix . but i want to see your usage exactly

**Comment by danielspaniel** [comment]
Hi @Exelord .. I am going to close this cause I have not heard back in many months, and you may have already solved it?  If not, please reopen, cause I am willing to help solve it, I just need more information and guidance from you if it still an issue
