### ISSUE TITLE
mockCreate returns payload as string to serializer 

### ISSUE THREAD

**Issue by sethboyles** [danielspaniel/ember-data-factory-guy#335]
This causes an error: 

```
Error: Assertion Failed: Your {modelName} record was saved to the server, but the response does not have an id and no id has been set client side. Records must have ids. Please update the server response to provide an id in the response or generate the id on the client side either before saving the record or while normalizing the response.
```

I have a simple factory like this: 

```
FactoryGuy.define('filter-set', {
  reusable: false
});
```

and am using `mockCreate('filter-set')` (no other arguments)

I tracked the error down to this line:

https://github.com/emberjs/data/blob/v2.0.0/packages/ember-data/lib/serializers/rest-serializer.js#L198

where `Object.keys` obviously is expecting a hash, but instead `payload` is a string like this:  `"{"filter_set":{"id":5}}"`

Using ember-data-factory-guy 2.13.27
          ember-data  2.13 (and upgraded to 2.18, didn't fix the issue)
          active-model-adapter 2.1 / 2.2

**Comment by danielspaniel** [comment]
do you think you could make a new ember project and set it up with your setup that shows the error ( then share that repo with me so I could clone it ) 
 that way .. that would make it much easier to track down the problem and fix it.

**Comment by sethboyles** [comment]
Turns out it was an issue with our extension of the ActiveModelAdapter.  Somebody overwrote `ajaxOptions` with this:

```
 ajaxOptions: function(url, type, hash) {
    hash = this._super(url, type, hash);
    hash.dataType = null;
    delete hash.dataType;
    hash.contentType = 'application/json; charset=UTF-8';
    return hash;
  }
```

I'm not sure why they did, but with getting rid of the `dataType` seems to (understandably) confuse Pretender.  So this doesn't seem like an issue with ember-data-factory-guy.  Sorry for the false alarm.
