### ISSUE TITLE
`mockFindAll` with params failing to match

### ISSUE THREAD

**Issue by patocallaghan** [danielspaniel/ember-data-factory-guy#337]
In our application adapter we’d like to start overriding the `ajax` hook to automatically append a `data` param to every single request that goes to our backend. So something like `store.findAll('some-model')` will actually make a request like `GET /some_models?our_property=true`.

But it appears mocking `findAll` calls which contain params fails as it thinks it’s a `query` command. This is where it fails here https://github.com/danielspaniel/ember-data-factory-guy/blob/23f6180a19dd443055e19192a6da76330a07e7d4/addon/mocks/mock-find-all-request.js#L11-L25

**Comment by danielspaniel** [comment]
fixed with v3.0.3
