### ISSUE TITLE
New ID to record that already has an ID?

### ISSUE THREAD

**Issue by henrymazza** [danielspaniel/ember-data-factory-guy#340]
This is an error returned by Ember Data when the server assigns a new ID to an already existing model:
```
"Assertion Failed: 'sale-item:1' was saved to the server, but the response returned the new id '4'. The store cannot assign a new id to a record that already has an id."
```
How can it happen under FactoryGuy? Is `mockCreate` intercepting `mockUpdate`?

**Comment by danielspaniel** [comment]
Can you show me your test + setup?

**Comment by henrymazza** [comment]
I couldn't isolate a code to reproduce the issue so far, but it probably is some out-of-loop code on my side, right? Gonna close so it doesn't stay hagging here, if I manage to isolate that I'll open it again. Thank you.

**Comment by danielspaniel** [comment]
Probably something like that. I have seen this error before but it is always an error I am making in my test setup. But feel free to open again if you see a bug in factory guy.

**Comment by henrymazza** [comment]
To leave it registered, I found the culprit. I had some code like this:
```js
await $(‘.save-sale-item-button’).click() // fires saleItem.save() directly
await $(‘.save-all-button’).click() // fires saleItem.save() indirectly
```
Silly me, click() won’t be _awaited_! So both will run concurrently and make a mess. Changed it to:

```js
$(‘.save-sale-item-button’).click() 
await settled()
$(‘.save-all-button’).click() 
await settled()
```

Hope it helps someone.

**Comment by danielspaniel** [comment]
just FYI if you use the click helper like this:

```js
import { click } from '@ember/test-helpers';
 // and the in the async test use like this:
await click(‘.save-sale-item-button’); 
```

you don't have to use settled
