### ISSUE TITLE
How to use a models function in a factory?

### ISSUE THREAD

**Issue by krachtstefan** [danielspaniel/ember-data-factory-guy#341]
Hi there! I'm new to ember-data-factory-guy and it seems to be very powerful and time saving. During the implementation on my current project tests I stumbled upon some basic questions that I could not find the answer to in the readme file or existing issues. 

When creating a factory with `let factory = make('mymodel')`. How do you call functions of that model? Computed properties are woking out of the box, but I couldn't find out how to call a function that I defined in my model. Also, is it right that hooks like f.e. the init hook and observers of a model are ignored when using a factory?

**Comment by danielspaniel** [comment]
@krachtstefan , you can call functions on the model.  You will have to show me EXACTLY what you are doing and what you model looks like for me to see what is happening to you. 
 
```js
let user = make('user');
user.someFunction(); // works as expected 
```
The init function is called, as are other hooks (didLoad/ready) even when the model is pushed into the store and not loaded ( thought ajax call ) when using make. 

 I might be able to look at your code in about 6 hours ( I am on EST ) if you want to clear up issues without having to guess what is going on more.

**Comment by krachtstefan** [comment]
Oh man, I tried this so many times before, but it turns out I had a typo in one of my factory definitions. I feel bad now :(  

You definitely earned the Fastest-Github-Response-Award 2018®. Sorry for taking your time and keep up the good work.

**Comment by danielspaniel** [comment]
Thanks @krachtstefan, I appreciate your noticing. I enjoy using factory guy alot so I am happy to share any other tips or tricks if you need them.
