### ISSUE TITLE
mockQueryRecord does not appear to return model attributes when used with `make`

### ISSUE THREAD

**Issue by joebartels** [danielspaniel/ember-data-factory-guy#342]
`ember` version: 3.1.0
`ember-data` version: 3.1.0
`ember-data-factory-guy` version: 3.1.0

#### This setup did not work for me:
```js
const madeUser = make('user', { name: 'Larry' });

mockQueryRecord('user').return({ model: madeUser });
```

with this app code:
```js
const userFromAppCode = await store.queryRecord('user', {});
```
The ids will match, `get(userFromAppCode, 'id') === get(madeUser, 'id')`
but the attributes don't appear to come in the payload response - in this case `name`.

---

#### This setup did work for me:
```js
const builtUser = build('user', { name: 'Larry' });

mockQueryRecord('user').return({ json: builtUser });
```

But it took me some time before figuring that out...

---

I couldn't find a test that asserted using `mockQueryRecord` with `make` so I'm not sure if it's supported but the [readme.md suggest it is supported][link-to-readme]

[link-to-readme]: https://github.com/danielspaniel/ember-data-factory-guy#mockqueryrecord

**Comment by danielspaniel** [comment]
mockQueryRecord for sure works with make @joebartels .. but let me write up a test in the factoryGuy tests and link to it in the docs for you .. and I will get back to you about that ( thought i am 100% sure that this will work and the name will appear ) 

also
 ```js
 mockQueryRecord('user').returns({model: user});
```
needs to be **returns** not return ( but that was probably a typo )

**Comment by joebartels** [comment]
ah yeah typo on the `returns`. Thanks for response. I'll be interested to know what the test shows 👍

**Comment by danielspaniel** [comment]
What happens if you do this: 

```js
const madeUser = make('user', { name: 'Larry' });
console.log('>> name should appear: ', madeUser.name);  // line 2
mockQueryRecord('user').return({ model: madeUser });
```

if there is not name on line 2 then youz got problems .. if you do, they Iz got the problems 
if it is the case 1 (youz got problems) above => what does user model look like?

**Comment by joebartels** [comment]
The model has the attribute being set. _(It was an `attr('string')` in my case)_

`make` returns the attributes as expected - so in that example, line 2 prints the name.

The deepest I inspected was `normalize(type, hash)` in the serializer and the `hash` only contained an `id`.

**Comment by danielspaniel** [comment]
holy primaryKey madness batman.. this really is interesting issue. 
 I think factory guy can try and detect that setting?  maybe? and use it .. ? 
 maybe you can outline a way that factory guy can accommodate this .. 
 
 i could check primaryKey setting in serializer for sure, but the extractId is funkyness I can not probably handle. 
  what I am thinking is that I could see .. oh .. you using _id as primary key .. so put key of _id there as well as id

**Comment by joebartels** [comment]
our `extractId` is a cautious in that if `_id` already exists it does not generate it client-side - so at least in this case there's sensible way to avoid `extractId` further interfering with things. 

adding `id` and `_id` doesn't strike me as a particularly nice way to handle this. What you said about inspecting the `primaryKey` seems like a good starting place at least and maybe enough.

**Comment by danielspaniel** [comment]
Do you think you can make a PR with a nice failing test that shows this setup ?? I would promise to make you a spinach salad with my favorite things like goat cheese and olives if you can do this ( might be tricky is why I am offering )

**Comment by danielspaniel** [comment]
Is this still an issue Joe ?  Did you figure things out?  If so, can you close this one? or keep trying to work with me to resolve it
