### ISSUE TITLE
mockQueryRecord calls adapter.urlForQueryRecord with undefined queryParams.

### ISSUE THREAD

**Issue by sly7-7** [danielspaniel/ember-data-factory-guy#343]
When doing 
```
let user = make('user');
mockQueryRecord('user', { me: true}).returns({model: user});
```
It throws an exception in my adapter's `urlForQueryRecord(query)`, with `query` being `undefined`. 

I think it's because `urlForQueryrecord` is called during: https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/mocks/mock-get-request.js#L14 but the queryParams attr is not yet initialized.

**Comment by danielspaniel** [comment]
let me write a test for that and see if i can fix it.

**Comment by danielspaniel** [comment]
this is fixed in https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v3.1.2 
 thanks for the issue .. was good one
