### ISSUE TITLE
Supplied param to matchin function is always `undefined`

### ISSUE THREAD

**Issue by roschaefer** [danielspaniel/ember-data-factory-guy#344]
[I think there is a :bug:  on this line.](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/mocks/attribute-matcher.js#L51) I'm debugging our application, we're using `JSONAPIAdapter` and instead of a key `user` (for a model user) there is a key `data`. Calling `requestBody[this.modelName]` is always undefined. Searching this repository for `match` did yield a test case for matching parameters but no test case for matching function.

Example code in our test suite:

```JavaScript
        let user = make('user');
        let userMock = mockQueryRecord('user');
        userMock.returns({model: user});
        // ...
        let updateUserMock = mockUpdate(user).match((updatedUser) => {
          console.log(updatedUser);
          return false;
        });
        // .. trigger the update here
        // .. visit a page, query the user above, click to update the user

```

Could sb. confirm this?

**Comment by danielspaniel** [comment]
There are 2 tests for match with function here:

https://github.com/danielspaniel/ember-data-factory-guy/blob/master/tests/unit/shared-adapter-behaviour.js#L1616 

 If you can make a failing test in a PR for your case, I'd be happy to try and fix things up ( unless you beat me to it )

**Comment by roschaefer** [comment]
@danielspaniel Sorry, I noticed your comment after creating my PR

Probably the test case is a little to big to expose that error, right?

**Comment by roschaefer** [comment]
@danielspaniel I'm going to update my branch to cover #344 in a smaller unit test.

**Comment by danielspaniel** [comment]
good idea .. thanks Robert
    On Wednesday, May 30, 2018, 11:17:19 PM GMT+1, Robert Schäfer <notifications@github.com> wrote:  
 
 
@danielspaniel I'm going to update my branch to cover #344 in a smaller unit test.

**Comment by danielspaniel** [comment]
the new patch version v3.1.2 has this fix

**Comment by mattwr18** [comment]
Thank you @danielspaniel!
