### ISSUE TITLE
'WhatWGFetch' is not defined in pretender.js

### ISSUE THREAD

**Issue by Gaurav0** [danielspaniel/ember-data-factory-guy#352]
The latest versions of pretender brought in by this addon, v2.1.1, has a dependency of @xg-wang/whatwg-fetch, which is not imported to the browser by this addon. As a result, during tests, one gets an error that WhatWGfetch is not defined.

The solution is to import all dependencies required by pretender by reading its package.json.

As a workaround, you can use the resolutions field in package.json to specify pretender v2.0.0.

**Comment by danielspaniel** [comment]
You want to make a PR  for that @Gaurav0 ?

**Comment by danielspaniel** [comment]
v3.3.1 has fix from this PR https://github.com/danielspaniel/ember-data-factory-guy/pull/354
