### ISSUE TITLE
Cannot read property 'fetch' of undefined

### ISSUE THREAD

**Issue by herzzanu** [danielspaniel/ember-data-factory-guy#353]
Upgrading to the latest version gets me this error. 

![image](https://user-images.githubusercontent.com/2959519/43370366-0deef59e-937e-11e8-8e14-5425fa26a8f3.png)

Both in an existing app with Ember 3.0 and in a brand new app with Ember 3.3.

**Comment by herzzanu** [comment]
Probably duplicate of #352

**Comment by danielspaniel** [comment]
v3.3.1 fixes this ( I think ) https://github.com/danielspaniel/ember-data-factory-guy/pull/354

**Comment by danielspaniel** [comment]
hmmm .. not sure what to say.  Can you try and noodle around with package.json and see if you can fix it?

**Comment by herzzanu** [comment]
Seems this one https://github.com/danielspaniel/ember-data-factory-guy/pull/388 fixes it.

**Comment by danielspaniel** [comment]
super .. will merge it and make new version in a moment  .. thanks for PR

**Comment by herzzanu** [comment]
Awesome, you rock 🎉
