### ISSUE TITLE
Unnecessary bower files

### ISSUE THREAD

**Issue by runspired** [danielspaniel/ember-data-factory-guy#357]
This project ships unnecessary `.bowerrc` and `bower.json` files.

**Comment by danielspaniel** [comment]
ok .. i remove that in a few moments, thanks for reminder

**Comment by runspired** [comment]
@danielspaniel thanks :) I only noticed because I don't have `bower` installed yet on the CI runs for `ember-data` and this was one of the external partner tests that failed because of that. (ember-data-change-tracker did as well)

**Comment by danielspaniel** [comment]
i made new version for that PR v3.3.4
