### ISSUE TITLE
Improvement: expecting specific parameters

### ISSUE THREAD

**Issue by yratanov** [danielspaniel/ember-data-factory-guy#36]
While writing acceptance tests for my application, I have noticed that `handleCreate`, `handleUpdate` methods are pretty indifferent to what they receive.
For example we have code:

``` coffee
test 'create post', ->
  postData = FactoryGuy.build('post')
  factoryGuyHelper().handleCreate('post', postData)
  # fill form with data from "postData" and click on submit
  # assert page contains data from "postData" 
```

The problem is that we do not care what exactly has been sent to the server, we just accept anything and return post with `postData`.

What do you think about adding (or changing existing) methods to handle only MATCHED requests?

`$.mockjax` supports it by passing `data` parameter.

``` js
$.mockjax({
    url:  "/posts",
    data: { title: "foo" }
});
```

Possible API:

``` coffee
# will now respond only if post has title "foo"
factoryGuyHelper().handleCreate('post', { title: "foo" }) 
```

**Comment by danielspaniel** [comment]
@yratanov  .. remember that discussion we had a month ago about the chainable methods. Well, one day I woke up and figured out it was not that hard, and might be fun to do, so here it is .. and it's now in version 0.9.6  .. check it out and let me know if you want to add or change anything.

```
 handleCreate('post')
 handleCreate('post').match({...})
 handleCreate('post').match({...}).andReturn({createdAt: new Date})
 handleCreate('post').andFail()
 handleCreate('post').match({...}).andFail()
```

Also, the order of the chained methods does not matter.

**Comment by yratanov** [comment]
@danielspaniel Looks great! Does it call mockjax on each chain call? Or

**Comment by danielspaniel** [comment]
No @yratanov , only calls mockjax once .. check out the code to see what its doing.

**Comment by danielspaniel** [comment]
For now, I am supporting both types of handleCreate .. with the options hash and the chainable methods

**Comment by yratanov** [comment]
@danielspaniel ok, great job!

**Comment by danielspaniel** [comment]
thanks :)
