### ISSUE TITLE
TypeError: Cannot read property 'build' of undefined

### ISSUE THREAD

**Issue by avdept** [danielspaniel/ember-data-factory-guy#364]
Hello. Getting this error while trying to build factory. Here's definition:

```
myapp/test/factories/user.js
/* eslint camelcase: [2, {properties: 'never'}] */

import FactoryGuy from 'ember-data-factory-guy';

FactoryGuy.define('user', {
  default: {
    ...omited args...
  }
});

```

Inside one of my tests - 

```
import { build } from 'ember-data-factory-guy';
....
let user = build("user");
....
```

This throws me following error:

```
Source: | TypeError: Cannot read property 'build' of undefined     at FactoryGuy.buildRaw (http://localhost:4243/assets/vendor.js:74915:25)     at FactoryGuy.build (http://localhost:4243/assets/vendor.js:74893:26)
```
ember version - 3.3.0
ember-data-factory-guy - 3.4.0(tried 3.3.0 as well)

Any ideas how to fix this?

**Comment by danielspaniel** [comment]
```let user = buildList("user",  2);```

**Comment by avdept** [comment]
Sorry, forgot to modify code. I've updated example to latest version where it crashes

**Comment by danielspaniel** [comment]
sounds like you have something really wrong in your your ember build .. i would have to look at the factory-guy package and see what is going on because this is a very very unusual situation ( never seen it before )

**Comment by avdept** [comment]
Any else info I can provide to solve this?

**Comment by danielspaniel** [comment]
I would recommend you start a new ember project ( with ember new test-project )
then 
install factory guy, ember-data , ember-source ( the fewest packages possible ) 
then 
make a user model  and make a user factory with no default attributes and write a test where you build a model  just like you did 
and you will see that this works =>  ```build('user')``` 
then 
add more models, packages, and code  till it breaks

**Comment by avdept** [comment]
Ok, will try this way. Thanks!

**Comment by avdept** [comment]
Just adding for those who will encounter this later. When using new test api, make sure to add `setupFactoryGuy(hooks);`  after test module declaration. It is mentioned in readme, but in other section than `how to use`

**Comment by lorcan** [comment]
Hey @avdept, I wonder if there's an opportunity here to open a PR to improve the README?

**Comment by danielspaniel** [comment]
good point @lorcan ... if you can fix the README @avdept .. I would be thrilled. You would be perfect to fix it because you probably know exactly where to put that info on setting up tests

**Comment by avdept** [comment]
@lorcan @danielspaniel I will submit PR with readme improvements soon.
