### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by amauryt** [danielspaniel/ember-data-factory-guy#365]
Hi Daniel, thank you for the excellent work with this add-on.

Now that jQuery is officially [optional since Ember 3.3](https://www.emberjs.com/blog/2018/07/16/ember-3-3-released.html#toc_new-features-1), I think that this add-on should not use jQuery anymore.

Doing a quick search within the repo I have only found a few instances in which `jquery` is imported and used:

- addon/payload/json-api-payload.js
- addon/mocks/mock-request.js
- addon/utils/helper-functions.js
- tests/unit/utils/helper-functions-test.js
- tests/unit/shared-adapter-behaviour.js

However, I don't know if there are other underlying uses. In any case, do you think that it would be possible to get rid of jQuery?

**Comment by danielspaniel** [comment]
There are only a few uses ( like $.params , $.extend ) which are no brainers 

but others in testing  like: 
 $(document).ajaxComplete    with are relying on jquery  $.ajax   calls ( ie jquery )   which are harder to replace

but I think if we replace those in the files you mentioned ( production ) files, we can keep jquery for a devDependency  ONLY 

 feel like doing a PR for this ?

**Comment by amauryt** [comment]
I dug in a little bit to remove jQuery from the `addon` directory. If my PR for RFC 176 is accepted the only function of jQuery outside of testing would be `$.param`, used here:

- addon/utils/helper-functions.js
- addon/mocks/mock-request.js

I tried to follow the approach of the `ember-fetch` [adapter](https://github.com/ember-cli/ember-fetch/blob/master/addon/mixins/adapter-fetch.js) for `ember-data`, in which `$.param` is partially reimplemented (see the function `serializeQueryParams`). I practically copied and pasted this function (and the respective `add` companion function and `RBRACKET` const) into `ember-data-factory-guy/addon/utils/helper-functions.js` and used it instead of `$.param`.

I had a some success, but alas this approach is not enough for `ember-data-factory-guy` as some tests still fail, such as those with body or URL params.

My guess is that it would be necessary to fully re-adapt the `$.param` function as a util helper to support these other use cases.

Unfortunately I do not have enough time to dig deeper, but I hope that this info will be a good start in case someone else would like to tackle this task.

**Comment by danielspaniel** [comment]
Thanks @amauryt , I will do that replacement ( I found some helper functions already ).  I really appreciate you taking the time to work on this.

**Comment by danielspaniel** [comment]
as of v3.6 there is no more jquery used in factory guy code addon code. there is still some left in the tests, but as of 3.6 you can use factory guy and you should not need jquery at all. 

as of v3.7 i am removing jquery entirely .. but as i said 3.6 is enough
