### ISSUE TITLE
How to count calls on model.save and other CRUD actions

### ISSUE THREAD

**Issue by BenjaminBeck** [danielspaniel/ember-data-factory-guy#376]
I want to test that a save button executes the model.save exactely once.
Not long ago i had the bug that pushing the save button would save a object twice and causing two PUT requests.

How would i do that?
I found a example using ``$.mockjax.mockedAjaxCalls()[1] [..]`` - but i thing that is outdated, right?

Thanks for any help

**Comment by danielspaniel** [comment]
yes, that is way outdated. now a days you can set up the mockUpdate or mockCreate  and then do this:

```js
 const mockSaveCompany = mockUpdate('company');
 .... blah blah 
 assert.equal(mockSaveCompany.timesCalled, 1 );
```

timesCalled is a property on any/all mock methods by the way.

**Comment by BenjaminBeck** [comment]
Thanks, that works! 
It´s in the README.txt but i must have overlooked it.
