### ISSUE TITLE
Using scenarios in addon fails with 404 errror

### ISSUE THREAD

**Issue by herzzanu** [danielspaniel/ember-data-factory-guy#384]
I've been using scenarios in a couple of addons until now without issues. But now all queries fail with a 404 error. This happens in tests as well. I've also created a new addon from scratch to see if there is anything on my side that could cause this. Tried on a different machine as well but same result.

![image](https://user-images.githubusercontent.com/2959519/57587885-af24e980-750c-11e9-863e-284b6fa0d0ee.png)

I've also set up a repo for the dummy addon that has the same issue

https://github.com/herzzanu/ember-factory-guy-test

**Comment by danielspaniel** [comment]
I was afraid this would happen one day .. and the day has arrived. 

If you =>     ember install ember-fetch
 and then add this to dummy/app/application.js 
 ```js
import DS from 'ember-data';
import AdapterFetch from 'ember-fetch/mixins/adapter-fetch';

export default DS.JSONAPIAdapter.extend(AdapterFetch);
```
it will start working

  Some tidbits to ponder 

- factory guy is on 3.7  ED and converted to using fetch and there was no issue
- i use this 3.7 factory guy on non fetch using ember project using 3.7 or 3.8 i think ( no issue ) 
-  ember-data started using fetch i think i ember-data 3.9 
- using factory guy 3.7  with ED 3.9 seems to now require you use fetch in the data adapter too when testing addons like you are doing in scenarios or whatever ( in dummy app )   ( not sure why .. might be optional might not, might be that I should not require "whatwg-fetch": "^3.0.0"  as a dependency in factory guy ( but i could not get my tests to pass without it ( i do some whacky things to check different addapters ) 
- i don't know if this is the case for dropping in factory guy to ED 3.9 applications though ? 

  so my conclusion is 

  - i think it is fine to use fetch in the adapter and call it a day 
 - other people can do this also and things would work the same 
 - i can put this in documentation and go back to watching cat videos all day 

 your thoughts ?

 

  I have a repo that is on 3.7 that does not use fetch and uses

**Comment by herzzanu** [comment]
Thanks for the explanations. I would add this to the documentation and call it a day. It's straight forward and simple enough to be done by anyone in the same position as we are here.

**Comment by danielspaniel** [comment]
readme is updated
