### ISSUE TITLE
Cannot read property 'fetch' of undefined

### ISSUE THREAD

**Issue by herzzanu** [danielspaniel/ember-data-factory-guy#387]
Seems there's again an issue with pretender.

![image](https://user-images.githubusercontent.com/2959519/58918996-d007e580-872c-11e9-83b2-44681f248555.png)

We had this type of issue before https://github.com/danielspaniel/ember-data-factory-guy/issues/353 and it was solved. Seems the pretender.js in package.json uses again the `^` and then it happens that we stumble upon these kind of issues without any warning 😕

**Comment by danielspaniel** [comment]
v3.9.1 is ready :)

**Comment by herzzanu** [comment]
Awesome 👏 Thanks!
