### ISSUE TITLE
Error: Pretender intercepted GET but no handler was defined for this type of request

### ISSUE THREAD

**Issue by gvocale** [danielspaniel/ember-data-factory-guy#422]
I am running into the error:
```
Error: Pretender intercepted GET /api/staff-members/1 but no handler was defined for this type of request
```
In my component I do:
```ts
// component/index.ts
const currentCalendar = await this.store.findRecord('admin/calendar', currentCalendarId);
console.log('currentCalendar', currentCalendar);
```
In my test:
```ts
// test.ts
describe('Integration | Component | admin/calendars', async function() {
  setupRenderingTest();

  let record;

  beforeEach(async function(this: TestContext) {
    manualSetup(this);
    record = build('admin/calendar', { id: 1 });
    this.set('currentCalendarId', record.calendar.id);
    mockFindRecord('admin/calendar').returns({ json: record });

    await render(hbs`
        <Calendars
          @currentCalendarId={{this.currentCalendarId}}
        />
    `);
  });
```

The `console.log` after `this.store.findRecord` outputs an `admin/calendar` model with the correct id, but Pretender throws the error that makes my test fail. What am I doing wrong?

**Comment by danielspaniel** [comment]
the error says  that this url => ```/api/staff-members/1```  is not being mocked 
you are looking to mock the model 'admin/calendar'  
so you did this mock 
```
mockFindRecord('admin/calendar').returns({ json: record });
```
to find out what url your mocking do this 
```
var mock = mockFindRecord('admin/calendar').returns({ json: record });
console.log(mock.getURL())
```
i am guessing that the url is either something you did not expect OR your calling for other data  (admin/staff-members) is router and that is not being mocked

**Comment by gvocale** [comment]
Thank you for your help!

Strangely I get the error:
```
var mock = mockFindRecord('admin/calendar').returns({ json: record });
console.log(mock.getURL())
// TypeError: mock.getURL is not a function
```

**Comment by danielspaniel** [comment]
look in documentation .. might be getUrl() ..  ?

**Comment by danielspaniel** [comment]
but in either case some part of your system is calling for that url  api/admin-settings/1   and your not catching it

**Comment by gvocale** [comment]
```
mock.getUrl() // "/api/admin/calendars/1"
```
Oh right!!! I was just focusing on `admin/calendar` but pretender is complaining about `staff-members/1`!!

Thanks for pointing me in the right direction
