### ISSUE TITLE
handleFindMany not correctly mocking requests?

### ISSUE THREAD

**Issue by grantovich** [danielspaniel/ember-data-factory-guy#46]
I'm setting up a new Ember project for integration testing with Factory Guy, and couldn't get a very simple test to work. It went like this:

```coffee
testHelper.handleFindMany('location', 1, name: 'DummyLoc')

visit '/'
click 'a[href="/locations"]' # This route loads all locations and displays them

andThen ->
  # Page body does not include 'DummyLoc'!
```

In the console I saw the mock being triggered, but no data was returned. Looking at the current code for [`handleFindMany`](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/src/factory_guy_test_mixin.js#L85), it looks like the mock request intentionally always returns nothing? This seems very odd. The mock *did* return actual data in the past, but that was changed in 63aee77c63e461dd3b90c53238eb25e94da40d06. The tests don't catch this because they go directly to the data store rather than hitting the mocks.

For now I am using this workaround, since `handleFindQuery` does mock requests correctly:

```coffee
location = testHelper.build('location', name: 'DummyLoc')
testHelper.handleFindQuery('location', null, [location])

visit '/'
click 'a[href="/locations"]' # This route loads all locations and displays them

andThen ->
  # Now the page body includes 'DummyLoc'
```

**Comment by danielspaniel** [comment]
@grantovich, I changed the handleFindMany code to be more like the handleFindQuery, in that it now returns an array of id's of the records that it created during the 'find'.   It was odd, because the tests still pass as before ( when it was passing back empty array, but it will probably solve the problem for you ) This will be pushed out within the week to version 0.9.3

**Comment by grantovich** [comment]
Hmm... I'd have to see the code (not pushed yet?), but I'm not sure that will fix the problem. The issue is not that the `handleFindQuery` function itself isn't returning anything, it's that the AJAX mock set up by the function isn't returning anything.

Regarding tests, I might take a look at this myself at the end of the week, but you could try using [`fetch`](http://emberjs.com/api/data/classes/DS.Store.html#method_fetch) instead of `find` to ensure that the records are reloaded and thus hit the mocks.

**Comment by grantovich** [comment]
Thanks, Daniel – I am using Bower, so I grabbed the latest commit and verified that the example in my original comment now works.

Digging a bit more into the code, I think my previous suggestion was on-target: Your tests are using `find`, which allows Ember to retrieve cached models from the store without hitting the "server". Perhaps this could be split into two assertions: Use [`all`](http://emberjs.com/api/data/classes/DS.Store.html#method_all) (which retrieves only local data) to verify the models are pushed to the store, and use `fetch` (which always retrieves remote data) to verify the mocks are set up.

Anyway, this can be closed since the issue as-reported is fixed. :+1:

**Comment by danielspaniel** [comment]
Hmm .. well ok Alex, I aill close this then.
