### ISSUE TITLE
Release incorporating `var` fix?

### ISSUE THREAD

**Issue by grantovich** [danielspaniel/ember-data-factory-guy#61]
Any chance we could get a patch release that incorporates 27ea2fc27309f005aa1486127e215bee10b69a0a? The missing `var` causes an error in strict mode, preventing us from running our Ember-CLI tests.

**Comment by danielspaniel** [comment]
Done .. v0.9.8  for bower and for gem

**Comment by grantovich** [comment]
Thanks very much Daniel!
