### ISSUE TITLE
Manually set handleCreate response.

### ISSUE THREAD

**Issue by kunerd** [danielspaniel/ember-data-factory-guy#68]
Is it possible to set the status code and response text for 'handleCreate'? I try to mock a create request that should produce a validation error on server side, therefor my response should be something like:

status: 422
respsonseText: 
```
{
   errors: {
      attr1: [error1, error2, ...],
      attr2: [error1, error2, ...]
    }
}
```

**Comment by danielspaniel** [comment]
I am working on it now @kunerd, will have something like this later today

**Comment by danielspaniel** [comment]
ok @kunerd  new version 0.9.11 has this ability to set the status and the errors in the response. Let me know how it goes, or if any problems with this release.

**Comment by kunerd** [comment]
@danielspaniel: Thank you very much. I will try it as soon as possible.
