### ISSUE TITLE
Multiple calls to handleCreate() don't work

### ISSUE THREAD

**Issue by pixelterra** [danielspaniel/ember-data-factory-guy#76]
I have a test file with multiple test() calls. Inside two I have calls to handleCreate(). Each test run individually succeeds, but together they fail since only the first call to handleCreate() "takes" or "sticks". 

https://gist.github.com/pixelterra/cd4e6d7ac3e4794bdf58

This is pretty surprising behavior to me. I would assume that only the "last" call to handleCreate() would be "active". 

I suppose that I could work around this by using the match() method and tracking which data is used in each call, but this seems unnecssary and could get messy with many calls to handleCreate(). 

Is this the only option or am I missing something?

**Comment by danielspaniel** [comment]
I'll make this a puzzle for you @pixelterra 

Check out the [sample acceptance test](https://github.com/danielspaniel/ember-data-factory-guy#sample-integrationacceptance-test) from the docs, and see if you can spot what you forgot to add to your test. 

Hints provided if you don't get it in 30 seconds.

**Comment by pixelterra** [comment]
Ah setup teardown. :) Lemme give that a go...

**Comment by pixelterra** [comment]
Ooo. that broke everything :(

**Comment by danielspaniel** [comment]
Yikes .. really .. hmm .. now I am puzzled.

**Comment by pixelterra** [comment]
I'm on 0.2.3 btw

**Comment by danielspaniel** [comment]
Me too, but let me check that gist again.

**Comment by pixelterra** [comment]
Error: Assertion Failed: You cannot use the same root element (#ember-testing) multiple times in an Ember.Application
afterEach failed on fields exist and are empty initally: No model was found for 'test'
afterEach failed on registration fails with bad data, and appropriate errors are displayed: No model was found for 'test'
etc...

**Comment by pixelterra** [comment]
Updated gist:
https://gist.github.com/pixelterra/cd4e6d7ac3e4794bdf58

**Comment by danielspaniel** [comment]
I think I know the reason. 

Get newest version of ember-data-factory-guy .. 

First: 
 remove it from package.json file 
 then:
 ``` npm prune ```
 then: 
```ember install ember-data-factory-guy ```

**Comment by pixelterra** [comment]
I have     "ember-data-factory-guy": "1.0.2",
 should I have a newer one?

**Comment by danielspaniel** [comment]
Yes, 1.0.3

**Comment by danielspaniel** [comment]
Hmm .. tricky .. actually 1.0.2 should work ok .. but if you get 1.0.3 .. at least you'll be on the same page as I am, so I can help out easier.

**Comment by pixelterra** [comment]
hm

**Comment by danielspaniel** [comment]
Yeah . I know .. sounds fishy.

**Comment by pixelterra** [comment]
installing now

**Comment by pixelterra** [comment]
actually going to standup with my team in a sec...

**Comment by pixelterra** [comment]
but I have 2 mins

**Comment by pixelterra** [comment]
actually that seems to have fixed everything

**Comment by pixelterra** [comment]
is this setup() and teardown() for FG new?

**Comment by danielspaniel** [comment]
no .. it's been there ( in that FactoryGuyTestHelper )  .. for ever ..

**Comment by pixelterra** [comment]
well for whatever reason, that fixed everything...

**Comment by danielspaniel** [comment]
whew .. glad that worked .. I was starting to think my fingernails were getting tasty there for a second. 
 I know why it worked .. but glad it's sorted out. 
 Essentially, you have to call $.mockjax.clear()  ( to clear the old mockjax handlers ) 
  which is what the teardown method is doing for you. 
  the setup call  is  setting up the response time for mockjax  to 0 .. so that will speed up your tests  ( that use mockjax ) quite alot.

**Comment by danielspaniel** [comment]
So, just for fun, try omitting the setup, and you'll see that those last 3 tests run slower

**Comment by danielspaniel** [comment]
This discussion actually showed me a bug .. which I fixed, and pushed out a new version 1.0.4. 
 You might not encounter it, but its safer to upgrade to this version so you don't get surprised.

**Comment by danielspaniel** [comment]
Closing this since issue resolved.
