### ISSUE TITLE
payload of handleFind limited to record's typeKey

### ISSUE THREAD

**Issue by tonywok** [danielspaniel/ember-data-factory-guy#82]
The API I'm working with uses single table inheritance. For example, we have a base task model, and various subclasses.

In my test I'm trying to do a `handleFind(task)`. That task happens to be of type `paper-editor-task`. The factory guy method `mapFind` will always return a json payload keyed to the pluralized version of the model name resulting in `paperEditorTasks`. My ember app expects `tasks`.

As a workaround I've monkey patched the FactoryGuy code. Would you consider supporting this? Perhaps as an option to `handleFind`? Or maybe by looking into the model's serializer instead of always using `record.constructor.typeKey`.

**Comment by danielspaniel** [comment]
Best thing you can do is do fork this project, make the code how you like it, write tests to prove it works, send me a pull request, and away you go with your new version of factory-guy .. 
 
Or you could alway override mapFind:

```js 
 FactoryGuyTestHelper.reopen({
  mapFind:function(modelName, json){
    var responseJson = {};
    if (modelName === 'paper-editor-task') {
      modelName = 'task';
    } 
    responseJson[Ember.String.pluralize(modelName)] = json;
    return responseJson;
  }
});
```
 
which is alittle bit funky .. but works.

**Comment by tonywok** [comment]
@danielspaniel Heh, that's exactly what I have right now :)

I was just wondering if it was something you were interested in supporting before I sent you a PR demanding you merge it :P

**Comment by danielspaniel** [comment]
Sure, I would support some way to modify that modelName .. but I am not sure how you are going to do it .. kind of tricky to do in a generic way  .. ( I think ) .. but if you can figure it out .. I will merge it .. ( if you have it tested properly )

**Comment by danielspaniel** [comment]
@tonywok, v2.0.1  removes mapFind from the creation of json .. so if you upgrade, you have to find another path to fix these kinds of issues,  but I refactored things to use serializer to create the keys, so maybe it will have fixed itself in this new version?  not sure.

**Comment by tonywok** [comment]
@danielspaniel I'll let my previous client know so they can address accordingly. Thanks for the update :)
