### ISSUE TITLE
Deprecation of `typeKey` in Ember Data

### ISSUE THREAD

**Issue by tarzan** [danielspaniel/ember-data-factory-guy#91]
Ember Data deprecated `typeKey` in favor of `modelName`. http://emberjs.com/blog/2015/05/21/ember-data-1-0-beta-18-released.html

When running my specs that use factoryguy I now get these deprecation warnings:
```
DEPRECATION: Usage of `typeKey` has been deprecated and will be removed in Ember Data 1.0. It has been replaced by `modelName` on the model class.
```
Would you like me to help with a PR? Or would those result in backward-compatibility issues?

**Comment by danielspaniel** [comment]
@tarzan, I am working on the new version for beta-19 .. that fixes this issue.  I had fixed this for beta-18, but there were too many bugs in beta-18 to use it so I reverted to beta-16 again. Anyway .. I am going to release a new version that fixes this ( but for beta-19 ) pretty soon,  so hopefully you can upgrade to that.

**Comment by tarzan** [comment]
Ok! Thanks for the reply. Will wait for the upcoming release then :)

**Comment by danielspaniel** [comment]
@tarzan , version 1.0.11 was just released and it is for beta-19
