### ISSUE TITLE
Error: Assertion Failed: FactoryGuy#setStore needs a valid store instance.You passed in [undefined]

### ISSUE THREAD

**Issue by gordonbisnor** [danielspaniel/ember-data-factory-guy#94]
I am new to FactoryGuy, and I am stumbling on this error with my first attempt on install/setup:

```
Error: Assertion Failed: FactoryGuy#setStore needs a valid store instance.You passed in [undefined]
```

Wondering if there is an assumption about Ember config, etc that I am not aware of, etc, or if documentation is not up to date, or if you might have any ideas about what I might be doing wrong!

## Software Versions:

* Ember 2.0.beta.1
* ember-cli 0.2.7
* Ember Data 1.0.0-beta.16.1
* "ember-data-factory-guy": "1.1.0",

## My acceptance test:

```
import Ember from 'ember';
import { make } from 'ember-data-factory-guy';
import TestHelper from 'ember-data-factory-guy/factory-guy-test-helper';

import {
  module,
  test
} from 'qunit';

import startApp from 'ckdu-ember/tests/helpers/start-app';

var application;

module('Acceptance: About', {
  beforeEach: function() {
    application = startApp();
    TestHelper.setup();
    TestHelper.handleFindAll('event', 2);
  },

  afterEach: function() {
    TestHelper.teardown();
    Ember.run(application, 'destroy');
  }
});
```

**Comment by danielspaniel** [comment]
Sorry about the lack of correct documentation @gordonbisnor, I used to have a list of factory guy versions with the ember-data version they would work with, but I stopped doing that .. and then now I realize it is a bit silly to think people are going to check the change log to find that out, so I will fix that today, but for you, using ember-data 16.1 .. you have to use factory guy 1.0.10 

and the command would be:

```
ember install ember-data-factory-guy@1.0.10
```

Let me know if you have any problems with this or if you worked out for you.

**Comment by gordonbisnor** [comment]
I tried 1.0.10, 1.0.11, 1.0.12, and 1.1.0 and I get the same error regardless of version. I've noticed that even when I remove all FactoryGuy-related code from the acceptance test, I'm still getting this error.

##This is a sample factory file:

```
import FactoryGuy from 'ember-data-factory-guy';

FactoryGuy.define('chart', {
  default: {
    formatted_position: '1',
    date: 'January 1, 2015', 
    album: 'Whine of the Mystic',
    artist: 'Nap Eyes',
    label: 'Self-released'
  }
});

export default {};
```

**Comment by danielspaniel** [comment]
How exactly are you installing factory-guy, exactly exactly .. 
 if you are using npm install that is the problem,
 has to be ember install

**Comment by gordonbisnor** [comment]
Yep, using ember install ember-data-factory-guy@xxx

**Comment by danielspaniel** [comment]
arghh .. was hoping you would not say that

**Comment by danielspaniel** [comment]
ember 2.0 .. is not running my initializer so I have to change this addon to work with ember 2.0 
 in the meantime can you use ember 1.13 or 1.12?  and let me know how far back you have to go till it works?

**Comment by gordonbisnor** [comment]
Sorry to be a troublemaker! I've gone through all versions as far back as Ember 1.10 and still getting the same error.

**Comment by danielspaniel** [comment]
whew .. @gordonbisnor, that is actually great news. I was starting to panic about having to make new versions for ember versions as well. 
 Do you think its possible for you to put that repo on github so I can clone it and try it myself?

**Comment by gordonbisnor** [comment]
Sure: https://github.com/gordonbisnor/factory-guy-issue-sample-repo

**Comment by danielspaniel** [comment]
Thanks, and your definitely not being a troublemaker .. this is pretty fascinating. I am also making new cli project to test this out, and getting similar problem, so something is going on with new cli application that was not happening with existing one.

**Comment by gordonbisnor** [comment]
Ha okay well thanks for taking a look, and if there is anything I can do to help debug etc let me know.

**Comment by danielspaniel** [comment]
Problem is here in your bower file:

    "ember-data": "1.0.0-beta.19.2"

change to:

   "ember-data": "1.0.0-beta.19.1"

  then:  
   
   bower install

 and it will work with factory-guy@1.1.0

 beta 19.2 reverted to store:main from store:application ( ugh ) .. it's difficult to keep up will all the breaking changes in ember-data .. thought I was warned about this change, just did not expect it so soon

**Comment by gordonbisnor** [comment]
Yep that did it. Thanks so much for helping debug this Daniel!

**Comment by danielspaniel** [comment]
No problem @gordonbisnor. This was a really good issue to bring up, and it's forcing me to get ready for the newer ember-data versions.
